### ISSUE TITLE
Create BEB webhooks with unique names

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#10006]
**Description**

The EventingController creates BEB webhooks based on the Kyma subscription names only, which is not collision proof.

**Expected result**

Each Kyma subscription should have a BEB webhook with a unique name created for it.

**Actual result**

Multiple Kyma subscriptions with the same name in different namespaces share the same BEB webhook.

**Steps to reproduce**

1. Create a namespace `ns1`.
2. Create a Kyma subscription `sub1` inside the namespace `ns1`.
3. Create a namespace `ns2`.
4. Create a Kyma subscription `sub1` inside the namespace `ns2`.

**Comment by sayanh** [comment]
Think about creating readable yet unique BEB webhook names.

**Comment by k15r** [comment]
* UUids ??

**Comment by pxsalehi** [comment]
The issue seems to be not webhooks, but the BEB subscriptions created on BEB. Since we only use the subscription name, the BEB subscription name will be the same for two Kyma subscriptions with the same name but in different namespaces. Which means the two Kyma subscriptions share the same BEB subscription and queue. Even if BEB allows this, the two Kyma subs will probably share the messages in the queue and each receives only a subset of the messages!

I tried to reproduce this. I could create two Kyma subs with the same name in different namespaces. They were both reported as ready. However, after a while they were both not ready and the reason was: `BEB Subscription not active`.

As for the solution, I'm not sure if we need UUIDs. As long as we also use the namespace name, it should be enough. Kubernetes wouldn't allow creating another Kyma sub with the same name in the same namespace anyway. So I'd suggest just adding 'namespaceName-` to the BEB subscription name.

**Comment by pxsalehi** [comment]
After discussion with @marcobebway and @sayanh, we should still use a schema like `namespace-subName-uuid` since different Kyma clusters could be sharing the same BEB namespace and therefore create Kyma subs with the same K8s namespace and name.

A more important issue is what to do with existing subscriptions during an upgrade (where we migrate subscriptions based on the old naming schema to the new schema).

**Comment by pxsalehi** [comment]
To solve the issue we need to address each of the following issues:
  - [ ] Change how subscription names are generated: We need to be able to reproduce the same sub name when reconciling BEB subs. Maybe the random UUID should go in another field in the sub CR (e.g. `id`) and be assigned the first time the Kyma sub is created. This would require introducing a (mutating) admission webhook for the subscriptions.
  - [ ] Pre- and post-upgrade jobs to migrate subscriptions to the new naming scheme: In the pre-upgrade job we take all subs and store them in a configmap, and delete them. In the post-job we will recreate the subs, which will follow the new naming, and then remove the configmap.
  - [ ] Performing the migration as described in the previous step, could lead to loosing messages that might be pending in the queue of the existing subscriptions. We need to do some impact analysis and decide whether this is acceptable during an upgrade, or we need to think of a new migration strategy.

**Comment by k15r** [comment]
- create a cluster wide unique value to use as an id on the beb-subscriptions (shoot name on skr)
- pre / post upgrade jobs can only be helm hooks on the 1.24 branch
- check for beb-subscription renaming

**Comment by radufa** [comment]
The name of the shoot cluster could be found with
```
k -n kube-system get cm/shoot-info -oyaml | grep shootName
```

**Comment by radufa** [comment]
Here are the EventMesh limits:
```
- webhook subscription name max length: 50
- queue name max length: 164
```
It seems that we have to restrict the BEB subscription name to "kyma-namespace + kyma-subscription-name" and this should be < 50.
The Kyma cluster instance could be identified based on the "EventMesh service key" namespace used in the associated EventMesh queue ("beb-skr-keb"). The mapping between Kyma instance and EventMEsh namespace is unique.
```
default/sap.kyma/beb-skr-keb/ce/webhook/test-noapp
```
The EventMesh namespace is also injected as "source" attributed in each CE send by Kyma (SAP convention).
To find the real cluster name of Kyma, the associated Kyma webhook info in BTP cockpit can be used ("c-05c78f3").
```
Subscription Name: test-noappQueue Namedefault/sap.kyma/beb-skr-keb/ce/webhook/test-noapp
Quality of Service: 1 
Webhook URL: https://web-ub8vzicy95.c-05c78f3.kyma-dev.shoot.canary.k8s-hana.ondemand.com/
```
