### ISSUE TITLE
application name needs to be cleaned from non alphanumeric characters before sending to BEB

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#10218]
```filter:
dialect: beb
    filters:
    - eventSource:
        property: source
        type: exact
        value: /default/sap.kyma/kh
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.commerce-mock.order.cancelled.v1
```

the application name needs to be cleaned to match `/\w+/`, otherwise this error happens on webhook creation:
DomainNamespace segment of Type attribute does not comply with SAP Event Specification

**Comment by k15r** [comment]
in the subscription this means that the eventType value needs to adhere to the same rule

**Comment by berkanercan** [comment]
Summary of the issue: We include application names in the `eventType` in order to differentiate same events that are sent from different applications. As this bug points out, having dash( ex. `commerce-mock`) in `eventType.value` is not compliant with SAP Event Specification. 

If we replace the dash in the application name with a dot, it will be compliant but there is an edge case:

Application names are following [RFC 1123](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/), which allow them to have multiple dashes. This means we can have `commerce-mock` and `commerce--mock` as separate applications. If we replace dashes with a dot, we will be casting both `commerce-mock` and `commerce--mock` into `commerce.mock`.

In the future, applications will be sending events directly to BEB and not over Kyma. This means we won't be including the application name in the event type.

Considering all these information, what is the best way to follow?

**Comment by sayanh** [comment]
On another thought, `\w+`  matches _ (underscore) but RFC 1123 doesn’t allow `_`.
So, `test-1` as application can be `test_1` in event_type.
and `test--1` as application can be `test__1` in event_type.
And BEB does not like it either. So `\w+` is not good enough.

**Comment by k15r** [comment]
Requirements:
- [ ] no event collisions for different applications
- [ ] it shall be possible to optionally omit the application name from the event type. This would make subscriptions portable between clusters.

Possible solution:
- [ ] application name cleaned from all forbidden characters will be used by default in event-types
       `sap.kyma.custom.<clean-application-name>.<event-type>`. As this can cause collisions if application exist with same cleaned name, the documentation needs to be updated to warn about this behaviour.
- [ ] a new label shall be introduced on the application resource. This label `application-type: <sometype eg. commerce>` will be used by the event-publish-proxy to replace the `clean-application-name` part in the new event-type by the value of the label.
- [ ] the eventing controller will take care of creating subscriptions according to the value of this label for applications that are configured to use the application-type over the application name.
- [ ] This feature can cause event collisions (means it is not clear who sent the event if two applications use the same label). This needs to be documented clearly

**Comment by pbochynski** [comment]
I like the solution proposed by @k15r. Application type label makes event type more predictable and still allows for full flexibility (you can use the same type or different types for 2 application instances). Go for it!

**Comment by k15r** [comment]
For now the label can be applied using kubectl, UI integration to be discussed later.

**Comment by marcobebway** [comment]
(As agreed with @k15r)

For Event publisher apps `event-publisher-nats` and `event-publisher-proxy`:

- If we receive legacy events `/v1/events`, we should clean the event-type from none-alphanumeric characters before publishing.

- If we receive cloudevents `/publish`, we should **not** clean the event-type, even if it contained none-alphanumeric characters.

For Event controller apps `eventing-controller-nats` and `eventing-controller`:

- We create NATS `subjects` cleaned from none-alphanumeric characters.

- We create `webhooks` cleaned from none-alphanumeric characters.

**Comment by marcobebway** [comment]
The documentation changes should be done in https://github.com/kyma-project/kyma/issues/10594.
