### ISSUE TITLE
Allow to switch container registry for serverless  in the runtime

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#10238]
**Description**
Allow kyma runtime administrators to reconfigure serverless module to use external docker registry ( dockerhub or vendored registry i.e ACR, ECR ) 
without running upgrade job.

> As a Kyma Admin user ( Matthew ) I want to opt out from in-cluster docker registry in favour of an external docker registry after kyma is installed. I don't want to re-install or upgrade the installation. I just want to provide secret for reference ( url, access credentials ) 

**AC**
 - registry details should be replaceable during runtime( i.e via secret)
 - once new registry is configured, all functions are reconciled to build container images in the target registry and point to new targets for the function workloads
 - upgrade job should respect existing configuration and do not force-overwrite to defaults
 
**Reasons**
In the documentation we mention that internal docker registry is not recommended for productution. We want to make it super easy to switch to a production-grade registry service ( with SLAs). 

**Attachments**

**Comment by kwiatekus** [comment]
- Configuration and troubleshooting in the runtime
If the registry config is not configured or mis-configured, we should not fail installation.
User should learn about configuration problems in the runtime ( not installation time).
We will not aim for complex fallback strategy.

 - Potential Refactoring ?? 
Think about unifying the configuration (should the internal registry be treated the same as external? but simply its installed by default)

 - How to disable unused internal docker registry
Disable vs. Scale down to 0. Check what is the response ( code ) when calling API of scaled down docker registry ( internal)

**Comment by tgorgol** [comment]
Current to-do list:
- [ ] What happens when we change format of secret in helm chart and add annotation to stop helm from managing it? How can we handle the rotating internal registry credentials? @tgorgol 
- [ ] Can we use secret with additional configuration fields such as: `username`, `password`, `registry` AND `.dockerconfigjson` as `imagePullSecret`? That way we could keep all configuration in single secret @m00g3n 
- [ ] Can we generate `.dockerconfigjson` by using admission webhook? @m00g3n 
- [ ] Investigate how the information about registry misconfiguration can be displayed in UI. @aerfio 
- [ ] Can we use https://github.com/stakater/Reloader to reload controller-manager pod when configuration secret changes?
- [ ] Implement configuration reloading depending on results of Reloader investigation - either by reading the secret in reconcilation loop or by using Reloader.
- [ ] Implement tests for the reloading logic.
- [ ] Add CLI command to set registry configuration.

**Comment by kwiatekus** [comment]
There will be a small follow up to reverse the hierarchy and allow overriding the configuration on namespace level : https://github.com/kyma-project/kyma/issues/10515
