### ISSUE TITLE
Prometheus shows duplicate targets for kubelet metrics.

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10245]
**Description**

Prometheus is showing duplicate targets for `kubelet.`

**Expected result**

Only one target should be shown for `kubelet` metrics.

**Actual result**

Two targets for `kubelet` are created.

**Steps to reproduce**

Access Prometheus UI via port-forwarding:

        kubectl port-forward -n kyma-system svc/monitoring-prometheus 9090:9090

Open Prometheus UI in browser: [http://localhost:9090/targets](http://localhost:9090/targets). Search for `kubelet`.

<img width="1460" alt="prometheus_kubelet_targets" src="https://user-images.githubusercontent.com/73824711/102775411-1b282e80-438d-11eb-8886-e2a85f0796e8.png">

**Troubleshooting**

**Comment by skhalash** [comment]
I just had a closer look and it turns out that these 2 target groups are not equal. The difference is the metric path, which is set to `/metrics` and `/metrics/cadvisor`. The weird thing about `kubelet` is that exposes multiple metric endpoints. Apart  from the usual `/metrics` it has `/metrics/cadvisor`, `/metrics/probes`, and `/metrics/resource` (for Kubernetes >= v 1.17). That's why there are multiple target groups.
