### ISSUE TITLE
Expose function does not render on Safari

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-project/kyma#10320]
**Description**
I am unable to expose created function, as it's window does not render at all.

Kyma v1.18.
Safari v14.0.2
macOS Big Sur v11.1
 
**Expected result**

I expect it to render properly as in other browsers such as Chrome.

**Actual result**

Blank window appears with no way to exposing actual function.

https://user-images.githubusercontent.com/14920383/104457528-77f0c080-55aa-11eb-9e97-4a66f9e4915e.mov

<img width="1536" alt="Kyma-v1 18-expose-function-2" src="https://user-images.githubusercontent.com/14920383/104457567-817a2880-55aa-11eb-8656-04e38fa4d925.png">

**Steps to reproduce**

1. Provision Kyma from 1.18 release version.
2. Login to Console.
3. Create any lambda function.
4. Enter deployed lambda function details.
5. Click _Configuration_ tab.
6. Click _Expose function_ button.

For more details about the behaviour please check attachments.

**Troubleshooting**

I have checked the same path and it renders properly on Google Chrome.

**Comment by kwiatekus** [comment]
Hi @mjakobczyk  thanks for reporting.
Console component will be removed from the kyma runtime and we are working on a new UI component that could be served locally or used as a centrally hosted service. 
We wont fix the safari bug as we try to avoid any low-prio fixed in the console module.
Please consider using different browser
