### ISSUE TITLE
Document new way of installation

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#10355]
**Description**

Kyma cli will offer new way of installation `kyma deploy` which needs to be documented alongside the "old way" which should be deprecated including kyma-operator, kyma-installer & overrides specifics.

AC:
- the "old way" of installation is deprecated
- installation CR is deprecated
- kyma-operator, kyma-installer is deprecated
- overrides are deprecated
- `kyma deploy` is documented
- `kyma undeploy` is documented
- components list is documented
- overrides are documented

**Area**

*Installation

**Reasons**

Documentation should follow installation changes

**Assignees**

@kyma-project/technical-writers

**Attachments**

https://github.com/kyma-project/kyma/issues/10297

**Comment by strekm** [comment]
useful links:
- example of overrides: https://github.com/kyma-incubator/hydroform/blob/master/parallel-install/example/overrides.yaml
- example of components: https://github.com/kyma-incubator/hydroform/blob/master/parallel-install/example/components.yaml
- library readme: https://github.com/kyma-incubator/hydroform/blob/master/parallel-install/README.md
- cli generated docs: https://github.com/kyma-project/cli/tree/master/docs/gen-docs

**Comment by klaudiagrz** [comment]
Just a reminder to also clean-up/update information on Kyma Lite in the [installation docs](https://kyma-project.io/docs/master/root/kyma#installation-overview) 🙂

**Comment by mmitoraj** [comment]
AC:

- [ ] the "old way" of installation is deprecated - no need to document it on the kyma-2.0-docu branch. no changes required in the kyma 1.0 docs
- [ ] installation CR is deprecated - no need to document it on the kyma-2.0-docu branch, no changes required in the kyma 1.0 docs
- [ ] kyma-operator, kyma-installer is deprecated - no need to document them on the kyma-2.0-docu branch, no changes required  in the kyma 1.0 docs
- [ ] overrides are deprecated - no need to document them on the kyma-2.0-docu branch, no changes required in the kyma 1.0 docs
- [ ] kyma deploy is documented - documented in **Operations -> Install Kyma** section
- [ ] kyma undeploy is documented
- [ ] components list is documented 
- [ ] overrides are documented - documented in the **Operations -> Change Kyma settings** section

**Comment by mmitoraj** [comment]
Together with @pbochynski we agreed that the installation docs should be as short and concise as possible. 
- I will only add prerequisites and the provisioning command so that the installation can be done in three easy steps. 
- Cluster installation on GKE, AKS or Gardener is not needed on the website. The details are not necessary from the user's perspective.
- I will also add a link to the [components.yaml](https://github.com/kyma-project/kyma/blob/main/installation/resources/components.yaml) to refer a user to all the Kyma components they can install instead of listing them on the website.
- No post-installation steps should be included - accessing the console moved to the Getting Started section.
