### ISSUE TITLE
istio-pilot pod has memory limit set to 2176Mi in local installation 

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#1051]
Without load istio pilot consumes 61Mi, see:

```
kubectl top pods -n istio-system
NAME                                        CPU(cores)   MEMORY(bytes)
...
istio-pilot-7888b94bf8-8mbmn                7m           61Mi
...
```

Do we need to allocate 2176Mi which is 27% of whole kyma local minkube installation (8GB)?
```kubectl describe nodes
  Namespace                  Name                                                               CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                                               ------------  ----------  ---------------  -------------
  istio-system               istio-pilot-7888b94bf8-8mbmn                                       510m (12%)    600m (15%)  640Mi (8%)       2176Mi (27%)
```

if this is production value, please adjust local settings (isLocalEnv), try first with memory request 128Mi and limit 256Mi.

**Comment by sjanota** [comment]
When introducing isito 1.0 I have tested pilot with 1 GB memory and it failed. That's why default (2GB) was left in place. Also as per comment [here](https://github.com/kyma-project/kyma/blob/master/resources/istio/values.yaml#L380) those are "Resources for small pilot install". I suggest:
* adding limit to pilot (as it was in our version of charts) via overrides.
* running again tests with lower memory limit for pilot.
