### ISSUE TITLE
Adjust serverless tests and documentation to new cluster certificate prerequisite

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#10624]
**Description**

Serverless will not support internal docker registry on clusters running k8s >=1.19 and self-signed certificate.
This is because kubernetes will fail to deploy images pulled from untrusted registries.
We don't want to invest in hacks for internal docker registry to ensure trust between kubernetes and internal deocker registry that is served w/o valid cert.

We should
- make user aware of the prerequisites. We could add a section for kyma installation section and make user aware that in order to have serverless working he either must install kyma with valid certificate for kyma  OR configure own docker registry override
- assure Internal docker registry is tested on gardener pipeline that runs kyma with valid certificate (as current pipelines were disabled https://github.com/kyma-project/test-infra/pull/3282)
- remove deamon set responsible for copying self-signed certs
- assure easy troubleshooting - in case pull image fails due to cert problem 

**AC**
 - [ ] document prerequisites for serverless (either valid certificate for kyma  OR own docker registry override)
 - [ ] e2e integration test for serverless and included internal registry

**Reasons**
As of k8s >=1.19 kubernetes will fail to deploy images pulled from untrusted registries.

**Related**
https://github.com/kyma-project/kyma/issues/10572

**Comment by pPrecel** [comment]
Important information about injecting custom ca certs with the containerd: https://github.com/containerd/cri/blob/master/docs/registry.md

**Comment by pPrecel** [comment]
We can simply improve our actual solution of injecting certs to the nodes to disable cert verification for the `containerd` but the problem is that the `containerd` needs to be restart after an operation like this. To restart `containerd` we have to achieve host namespace and run the privileged daemonSet. The workaround is needed only for clusters with the `containerd` instead of the `docker` so, in my opinion, we should describe this in the docs if we don't want to invest in this solution.

Some important links:
[My draft PR where I tested solution](https://github.com/kyma-project/kyma/pull/10786/files)
[Cri documentation about tls certs](https://github.com/containerd/cri/blob/master/docs/registry.md#configure-registry-tls-communication)
[How to achieve host namespace](https://github.com/kvaps/kubectl-node-shell/blob/master/kubectl-node_shell)
