### ISSUE TITLE
Pipelines failing due to `Permission denied (publickey)`

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/kyma#10818]
**Description**

Pipelines are sometimes failing due to 
```
Pseudo-terminal will not be allocated because stdin is not a terminal.
Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-cli-compatibility-2/1368758672389312512
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-cli-compatibility-2/1367671498189312000
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-integration/1367154211145388033

**Expected result**

Pipelines should be stable.

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by adamwalach** [comment]
This problem happens on all kind of jobs:
![Screenshot 2021-03-11 at 13 41 37](https://user-images.githubusercontent.com/8530211/110788942-93f1a500-826f-11eb-857b-ff2c5ac4dd32.png)

I'll try to increase verbosity of ssh commands

**Comment by adamwalach** [comment]
Follow up - create a gcp support case

**Comment by Ressetkk** [comment]
The issue seems to be related to the GCP [OS Login](https://cloud.google.com/compute/docs/oslogin). This feature allows using IAM permissions to grant access to the VMS for specified users/groups. When user is SSH'ing to the VM `cloud` command generates the private/public SSH key pair - the private key is stored locally and the public key is assigned to the GCP user profile and is used later for authentication to the VMs. 

The issue appears in the CI. Each time the job that does something on the external VM over SSH regenerates the private/public SSH key pair. That leads to frequent rotation of the public keys assigned to the Service Account and delays in populating the correct public keys assigned to the SA. 

The solution is to use pre-generated key pair in the CI to avoid regeneration of these keys.
