### ISSUE TITLE
Investigations on prometheus scraping without mtls

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11179]
**Description**
At the moment prometheus is running outside of the service-mesh. That sounds reasonable as it should observe the mesh and with that should not be part of it. Seeing istio demos and documentation, it appears to run outside of the mesh as well.

However, that conclusion results in a problem. Whenever prometheus should scrape an endpoint for metrics, it can not do that using mTLS. So usually the application needs to losen the requirements for client and needs to configure a permissive mode.

That is a not desired solution security wise and also not convenient.

Goal: Apply the recommended solution of istio a try by running a sidecar without intercepting the traffic and re-using the certificates inside prometheus.

Criterias:
- Documentation reflects the changes, also stating how and why prometheus is doing TLS by itself and not via envoy 
- Recommendation of istio is applied
- All unneded permissive modes for port of kyma components are removed

**Reasons**

**Attachments**
There seem to be a solution coming from istio itself by running a sidecar with prometheus which will not intercept any traffic but writes the certificates to a volume. That certificates prometheus will use for scraping the applications inside the mesh. See https://istio.io/latest/docs/ops/integrations/prometheus/#tls-settings

**Comment by jeremyharisch** [comment]
The recommended solution of Istio was applied, meaning Prometheus is deployed including a sidecar without intercepting the traffic. Furthermore, Prometheus reuses the certificates of Istio to enable mTLS.

All possible kyma components, have been configured to scrape the metrics using mTLS. `Kiali` and `Grafana` will not use mTLS for now, due to some implementation issues. We need to have a second look at it in future.

The tutorial, as well as the documentation, have been adapted.


The pre-described changes will be done, by merging the following PRs in this given order:
1. [#11994](https://github.com/kyma-project/kyma/pull/11994)
2. [#182](https://github.com/kyma-project/examples/pull/182)
3. [#12013](https://github.com/kyma-project/kyma/pull/12013)
