### ISSUE TITLE
Upgrade deprecated K8s resource API versions

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#11170]
**Description**

Several resource versions have been deprecated and will soon be removed from Kubernetes.
The current resources need to be updated as follows (list ongoing):
- [ ] `rbac.authorization.k8s.io/v1beta1:ClusterRole` -> `rbac.authorization.k8s.io/v1:ClusterRole`
- [ ] `apiextensions.k8s.io/v1beta1:CustomResourceDefinition` -> `apiextensions.k8s.io/v1:CustomResourceDefinition`

**Reasons**
Prepare to be compatible with future Kubernetes versions

**Comment by Halamix2** [comment]
Copied from  #10497:

- [ ] `rbac.authorization.k8s.io/v1beta1:ClusterRoleBinding` -> `rbac.authorization.k8s.io/v1:ClusterRoleBinding`  
- [ ] `rbac.authorization.k8s.io/v1beta1:Role` -> `rbac.authorization.k8s.io/v1:Role`  
- [ ] `rbac.authorization.k8s.io/v1beta1:RoleBinding` -> `rbac.authorization.k8s.io/v1:RoleBinding`

**Comment by strekm** [comment]
it was agreed that:
- service-catalog crds won't be touched in this task, @PK85 will handle that if we really need it
- application-connector crds PR was pushed to frogs team: https://github.com/kyma-project/kyma/pull/11456

other than that we found bunch ofc crds which are not located in cluster-essentials or installation/resources/crd:
- components/compass-runtime-agent/internal/compassconnection/testdata/compass-connection.crd.yaml -> i proposed to handle it in application-connector PR mentioned above
- components/eventing-controller/config/crd/external/apirules-gateway-kyma-project-io.yaml -> will be handled by @k15r team
-  installation/resources (installer-local, installer, release-adder): @werdes72 lets bump it
-  installation/resources/crds/compass-runtime-agent/compass-connection.crd.yam
-  installation/resources/crds/compass-runtime-agent/compass-connection.crd.yam -> can be handled with PR to application-connector crds
- installation/resources/crds/tracing/jaegers.jaegertracing.crd.yaml: don't know yet
- resources/cert-manager/templates/crds.legacy.yaml -> this one will be gone soon

**Comment by rakesh-garimella** [comment]
@werdes72 Created the [PR](https://github.com/kyma-project/kyma/pull/11531/files) for bumping the `apiextensions.k8s.io/v1beta1` -> `apiextensions.k8s.io/v1`. However this requires additional change in installation package in hydroform which has been performed in this [PR](https://github.com/kyma-project/hydroform/pull/330). But these changes when applied to kyma cli will break the installation for the kyma version upto 1.24 and so the installer needs to be made aware of the kyma version. 

However in my opinion the effort of making this work would be huge compared to the result achieved since anyways as the changes performed in the PRs would be obsolete once we have kyma 2.0

**Comment by strekm** [comment]
all PRs have been merged, we ccan close this task
