### ISSUE TITLE
Configurable auth proxy for grafana/kiali

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11181]
**Description**
To unify the exposure of kiali/jaeger and grafana a keycloak proxy is placed in front taking care of the authentication and group checks. With [Kyma 2](https://github.com/kyma-project/kyma/issues/11337) a default way of authenticating the user will not be possible anymore, so the configuration of the proxy at runtime becomes an important feature.

Goal: make the proxy future-ready by migrating to the recommended application "oauth2-proxy" and have the authentication settings configurable at runtime so that an upgrade will not reset them.

Criterias:
- keycloak-proxy is not used anymore as it is not maintained
- the OIDC settings can be configured at runtime so that it does not get overriden by an upgrade
- the OIDC settings can be configured via overwrites
- exposure is active by default (for kyma 2) having a declining policy
- changes are applied for kiali/grafana/jaeger

**Reasons**

**Attachments**

**Comment by chrkl** [comment]
For release notes:

# Replace keycloak-gatekeeper with OAuth2 Proxy

Keycloak-gatekeeper was used to secure access to Kiali, Grafana and Jaeger. It's development has been discontinued and been replaced by [OAuth2 Proxy](https://github.com/oauth2-proxy/oauth2-proxy) in this Kyma release.

Due to different capabilities of OAuth2 Proxy, the available override values to expose Kiali, Grafana and Jaeger also changed.

Summary:
- Configuring the exposure of individual resources is not possible anymore
- Matching custom OAuth2 claims is not supported anymore
- The available override values can be found at https://github.com/kyma-project/kyma/blob/main/resources/kiali/values.yaml#L30 for Kiali, at https://github.com/kyma-project/kyma/blob/main/resources/monitoring/charts/grafana/values.yaml#L714 for Grafana and at https://github.com/kyma-project/kyma/blob/main/resources/tracing/values.yaml#L123 for Jaeger

**Comment by NHingerl** [comment]
=> It's in https://github.com/kyma-project/website/pull/744
