### ISSUE TITLE
Fix HA set up of NATS cluster

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#11376]
**Description**

It is found the HA setup of NATS is not working as expected.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by radufa** [comment]
Tested on SKR: AWS, Kyma 1.22, two nodes.
Steps:
- use the new anti-affinity distribution fixed in PR: https://github.com/kyma-project/kyma/pull/11452
- drain one node (as a simulation of upgrading K8S by our SRE team)
Findings:
- the Nats subscriptions are correctly replicated from one Nats instance to another during the redistribution of Nats instances, as long as a least one Nats instance is active. This is the current behavior of K8S. 
- The eventing-controller continue to work all the time 
- The publisher has to be restarted cause it's connection with Nats was closed and it doesn't reconnect. It return 502:
```
time="2021-06-10T15:47:22Z" level=info msg="Event received id:[A234-1234-1234]"
time="2021-06-10T15:47:22Z" level=info msg="Sending event to NATS, id:[A234-1234-1234]"
time="2021-06-10T15:47:22Z" level=error msg="Failed to send: nats: connection closed"
time="2021-06-10T15:47:22Z" level=info msg="Event dispatched" duration="117.959µs" id=A234-1234-1234 responseBody="[110 97 116 115 58 32 99 111 110 110 101 99 116 105 111 110 32 99 108 111 115 101 100]" source=commerce statusCode=502 type=sap.kyma.custom.commerce.order.created.v1
```

**Comment by radufa** [comment]
The current deployment which specifies to have only 2 nodes in Kyma cluster is error prone, cause after the first "drain", all Nats instances are running on the same node (the only one). And if now this node is drained too, to finish the K8S migration, no Nats instance remains active to "save" the subscriptions (the Nats susbcriptions are saved only in memory).
As a consequence, to have always subscription replication, Nats HA needs to have at least 3 K8S active nodes.

**Comment by radufa** [comment]
The for for the connection closed issue is done in: https://github.com/kyma-project/kyma/pull/11467

**Comment by radufa** [comment]
The eventing-controller related issues are still not solved.

**Comment by radufa** [comment]
No other issues were found during the manual tests. Both publisher and controller survive restarting NATS cluster. so that the eventing flow continue to work without any operational actions.
