### ISSUE TITLE
Event data no delivered properly

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#11482]
**Description**
The SKR-AWS-Integration-Test is failing because of event data not being delivered properly

```
 order.created.v1 event should trigger the lastorder function:
     AssertionError: expected { Object (order, event) } to have nested property 'event.data.orderCode'
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:136:43
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async sendEventAndCheckResponse (test/fixtures/commerce-mock/index.js:107:3)
      at async Context.<anonymous> (skr-test/skr-test.js:79:5)

```

**Expected result**

The event data should be delivered properly

**Actual result**
Example failures:
https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-integration-dev/1404968266614444032/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-integration-dev/1404605870116966400/build-log.txt

**Steps to reproduce**

**Troubleshooting**
Past issue looking similar: https://github.com/kyma-project/kyma/issues/10720

Yesterday re-triggering the pipeline passed the test.

**Comment by marcobebway** [comment]
This is fixed by increasing resource limits for the Eventing controller to be able to reconcile the subscriptions (when evaluation profile is active).

Successful runs:
- https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-integration-dev/1415477632895553536/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-integration-dev/1415115240600768512/build-log.txt
