### ISSUE TITLE
Kyma pipelines inventory and target state

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#11530]
**Description**

Create the inventory of current pipeline with the information about:
- environment (gardener-azure, gardener-aws, gke, k3s, etc)
- installation method (legacy installer, kyma CLI, node-js installer, KEB, reconciler, etc)
- executed tests (octopus, octopus-upggrade, fast-integration, fast-integratio-upgrade)

For each pipeline in the inventory decide if it stays, requires changes, or should be replaced. Out of that we should get a list of the pipelines that should be in the target state (Kyma 2.0)

**Acceptance criteria**
- [x] inventory of existing pipelines
- [x] decision what to do with each pipeline (keep, add, modify, delete/replace)
- [ ] target pipelines

**Reasons**
We introduce pipelines on demand and we do not see a big picture. It should be clear what pipelines are mandatory, what optional and we need to have a clear policy on which of them have to be green all the time.

**Comment by k15r** [comment]
In order to keep this inventory up-to-date and to ease the process of creating it i suggest to update the `rendertemplates` tool https://github.com/kyma-project/test-infra/tree/main/development/tools/cmd/rendertemplates.
* update the *-data.yaml files used by the tool to include metadata for the required information.
* create a markdown template that puts this metadata into a readable format.
* prepare an initial list of metadata tags / patterns to be used in our job definitions
* prepare a presentation for eg. SIG-Quality so that the teams can put this information on their jobs

**Comment by k15r** [comment]
https://github.com/kyma-project/test-infra/pull/3868

**Comment by k15r** [comment]
defining target pipelines has been moved to this issue: 
https://github.com/kyma-project/test-infra/issues/4087
