### ISSUE TITLE
Json log parsing not working anymore when displaying Loki logs in grafana in kyma 1.23

### ISSUE THREAD

**Issue by FullyScaled** [kyma-project/kyma#11546]
**Description**
After upgrading kyma from 1.20 to 1.23 our logs do not get displayed correctly anymore. Json-Formatting (Splitting) is not working anymore when displaying the Loki logs in grafana explore.

Kyma 1.20:
![image](https://user-images.githubusercontent.com/28532557/123273187-b51a9080-d502-11eb-8d38-f67b5d4df3cd.png)

Kyma 1.23: 
![image](https://user-images.githubusercontent.com/28532557/123273539-062a8480-d503-11eb-9e7e-ed1cbc691404.png)

**Expected result**

Json parsing of logs should still work with the same fluent bit configuration.

**Actual result**

No fields are beeing parsed out of the json.

```  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               *
        **Merge_Log           On**
        Keep_Log            On
        Merge_Log_Trim      On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Buffer_Size         32k
        Kube_URL            https://kubernetes.default.svc:443
        Kube_Tag_Prefix     kube.var.log.containers.
        Use_Journal         Off
        Labels              On
        Annotations         On```

**Comment by a-thaler** [comment]
I can indeed reproduce the problem, thanks for the report.
I boiled it already down to the used fluent-bit output plugin for loki. Between 1.20 and 1.22 we updated the plugin version (causing also the rename from "loki" to "grafana-loki"). It looks like the used version 2.1.0 is having that bug.
Potentially that issue caused it as a side-effect: https://github.com/grafana/loki/issues/3245

Downgrading to the previous version and updating to the newest version both fixed the problem. So in order to solve the problem, I will upgrade Loki and the plugin to latest version 2.2.1
