### ISSUE TITLE
Duplicated jobs on PRs to release branches

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#11592]
**Description**

We noticed that when a commit (from main branch?) that was used on a PR to the `main` branch is cherry-picked to a PR against the release branch there are some job statuses for (among others) gke-integration jobs.

Examples:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/11583/pre-main-kyma-gke-upgrade/1409904532602753024
- https://github.com/kyma-project/kyma/pull/11588

When I tried to re-run this job it failed (as it should, because its not in the definition):
![Screenshot 2021-06-30 at 09 48 26](https://user-images.githubusercontent.com/8530211/123932823-1b376580-d992-11eb-8422-2742078b9d3e.png)

**Comment by Ressetkk** [comment]
We won't be able to fix this issue. We cannot remove the statuses from the GitHub. Once the statuses are reported they will stay until Prow updates them. And if the specific branch does not have the jobs the status will stay but will be out-of-date. We can't do much about it as it's an expected behaviour.

The only solution is just refresh a commit id to generate new set of statuses.
