### ISSUE TITLE
Move Central Application Gateway and Central Connectivity Validator to `kyma-system`

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#11620]
**Description**

Right now all Application-Connector-related components are created and running in `kyma-integration` namespace. With the reduction in the number of components, we should move them back to the `kyma-system`.

**Reasons**

We want to have a clear separation of system and user-created components.

**Acceptance Criteria**
- [x] CAG and CCV moved to `kyma-system`
- [ ] tutorials corrected

**Comment by janmedrek** [comment]
We should consider moving other components (App Registry, Conn. Service and Compass Runtime Agent) to `kyma-system` as well.

**Comment by franpog859** [comment]
As we work parallelly on [this story](https://github.com/kyma-project/kyma/issues/11611) I think I'd go for only CAG and CCV migrations. There would be too many conflicts otherwise.
There are three options as I see:
1. Remove CAG and CCV subcharts from Application Connectivity chart and create two separate charts for these components
2. Remove CAG and CCV subcharts from Application Connectivity chart and create one Application Connectivity System charts with two subcharts for CAG and CCV
3. Use `kyma-system` namespace for the CAG and CCV still being the Application Connectivity subcharts

I think I'll go with the third option right now. In this one, it'll be easier to migrate other components later on as well. Only one concern is that some subcharts of the Application Connectivity will be installed in a different namespace but I think it should not be a big deal. If you have other suggestions, please, jump into the discussion!

**Comment by franpog859** [comment]
#documentation/tutorials, @kyma-project/technical-writers 

In [this PR](https://github.com/kyma-project/kyma/pull/11631) the CAG and CCV will be moved to the `kyma-system` namespace. I also renamed CAG `namespace` flag to `applicationSecretsNamespace` as it's more descriptive in my opinion. In terms of the documentation, I updated the components' READMEs. If there is any documentation/ tutorial regarding CAG or CCV, it should be updated as well. The change is nothing more than I just described
