### ISSUE TITLE
Feature Request: cicd component set

### ISSUE THREAD

**Issue by Kiddinglife** [kyma-project/kyma#11625]
**Description**
My understand is that kyma is functioning as a fully-battery-included PAAS plateteform heavily used for dev & ops people. What is the surprise, kyma does NOT come with battery-included cicd components. A possible cicd component set is Tekton used as CI component, ArgoCD used as CD component and Harbour used as private registry for helm charts and docker images. Those coponents can also benifit from the already-running monitoring & logging components in kyma.
**Reasons**
 I believe those cicd component set will bring significant values to kyma and kyma's users.
**Attachments**
https://argoproj.github.io/argo-cd/
https://tekton.dev/
https://goharbor.io/

**Comment by pbochynski** [comment]
We started Kyma because we missed many essential features in Kubernetes, but we didn't want to build a full PaaS solution. I think having CI/CD component in Kyma can be a value, but on the other hand, we refactor Kyma to reduce its footprint and we focus more on the runtime aspect (one example here is that for production workload we recommend using an external docker registry instead of build-in as a more resilient solution). 
Therefore, CI/CD is not on a priority list for Kyma and we are not going to work on it this year. We can revisit that decision later, but for now it is not part of our plan.
