### ISSUE TITLE
Remove installer from fast-integration suite

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11668]
**Description**
The test suite has it's own way of installing kyma which is not aligned with the recommended way. Anyway the installation should not be part of  a test suite.

Goal: remove it

Criteria:
- The logic is removed from the test folder
- all pipelines are still working by installing kyma using the CLI

**Reasons**

**Attachments**

**Comment by lindnerby** [comment]
This has been done:
* Replace k3s as cluster base for fast-integration tests with k3d, which will now be pre-installed on the custom VM image
* Install Kyma via CLI on pipeline jobs that run fast-integration
* Remove Kyma install tests and redundant make targets
* Keep JS based Kyma installer, since it's actively used by people (would be nice to extract that though, since it's still part of the module tests/fast-integration although it's not referenced from any tests anymore)
