### ISSUE TITLE
[Telemetry Operator] Add a Helm chart

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#11822]
**Description**

Create a Helm chart for a new `telemetry` component with 2 sub-charts: `telemetry-operator` and `fluent-bit`. 

* `telemetry-operator` should be based on the resources auto-generated by `kubebuilder` (see #11663). The auto-generated resources (YAML, customize) should not be colocated with the code (the way `kubebuilder` does it) and have to be cleaned up/ignored.
* `fluent-bit` should be just carried over from the latest upstream. In the long-term, it should replace `fluent-bit` from the `logging` component. But, for now, they will co-exist.

The new component should not be installable by kyma CLI by default.

**Acceptance Criteria**

* Add a Helm Chart
* Clean up `kubebuilder`-generated files

**Attachments**

**Comment by elchead** [comment]
IMPORTANT: the helm chart is temporarily placed under `components` because the POs were not present for approval

The new helm chart installs the new telemetry operator and fluent-bit (new version compared to logging version). The PR also includes this story: https://github.com/kyma-project/kyma/issues/11824?

After installation, the user can dynamically configure this fluent-bit installation by creating a `loggingconfiguration`. The functionality is validated under `fast-integration/telemetry-test`

**Comment by skhalash** [comment]
It was decided to leave the kubebuilder-generated files as is for now, since that's how some other homebrewn Kyma operators do that (eventing operator).

**Comment by skhalash** [comment]
The helm chart was also moved under `resources`, where the rest of the charts reside.
