### ISSUE TITLE
Child reconciler for eventing component

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#12017]
**Description**
Eventing depends on ory component, so for the reconciliation of eventing we need to first resolve/verify if the dependent components (i.e. ory) are installed or not. 
We need to find out whether there is any such option provided by reconciler to define dependencies or not. If not, then we need to implement a separate child reconciler for eventing component.

**Comment by pxsalehi** [comment]
I don't think we have the (installation time) dependency on Ory anymore (since a while actually):
https://github.com/kyma-project/kyma/pull/11507
https://github.com/kyma-project/kyma/pull/11993

Implementing an eventing reconciler just for that is an overkill IMO. As long as Ory is installed along with Kyma, it should be enough.

**Comment by k15r** [comment]
Not required anymore
