### ISSUE TITLE
Switch to the official fluent-bit loki plugin

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#12026]
**Description**
fluent-bit nowadays bundles the loki output plugin, so there is no need to bundle it manual (save maintenance) and anyway the support for the custom loki plugin is not guaranteed.
Be aware of that the config for the labelling changed heavily and there is no simple conversion possible. The main problem is that all label keys of the custom mapping must be present for every log which is not the case for the labels of functions.

- [ ] Adjust fluent-bit config so that it uses the built-in plugin and results in the same behaviour (check the label mapping, the config is quite different)
- [ ] Verify that everything works as before (logs arrive in grafana and kyma console) and the log stream set is the same

**Reasons**

**Attachments**

Relates to https://github.com/kyma-project/kyma/issues/10582

**Comment by a-thaler** [comment]
Tried to switch to the plugin once more. Here are the changes I did: https://github.com/a-thaler/kyma/tree/loki-plugin
The used image is based on https://github.com/kyma-project/third-party-images/pull/184

Blocking issue is that the remove_keys feature is not yet working with nested log records, see https://github.com/fluent/fluent-bit/issues/3875 which most probably gets released with 1.9.x

**Comment by a-thaler** [comment]
We decided to go with the kubernetes attribute as part of the log, so gave it another try. Unfortunately, when switching the plugin to the official one provided by fluent-bit a performance degradation happened heavily. Instead of seeing the fluent-bit output processing around 2 MB/s now the maximum was around 100KB/s. Found a report of another user, see https://github.com/fluent/fluent-bit/issues/4754

**Comment by a-thaler** [comment]
Setting "workers 1" for the loki output increased the performance, but only for one instance which is really strange.. And still the tail plugin of that one instance is pausing without obvious reason like resource exhaustion..

**Comment by hisarbalik** [comment]
Current version (1.9.3) of fluent-bit loki output plugin has some issues causing instability and lost of logs. Event under moderate load causing "entry out of order" issue on loki side, that happening seem time stamp of log pushes from fluent-bit loki output plugin are not precise enough on nano seconds level and causing on loki side "entry out of order" problem and such log entries will be ignored from loki.

There is a fix from loki side which is available from loki version 2.6.x, this fix will adjust log timestamp on loki side on nanosecond level to avoid duplicate log entries. (configuration parameter **increment_duplicate_timestamp**)

Another issue is hight latency of pushed toward to loki, it seems fluent-bit loki output plugin pushes log chunks  often which causing high network latency and risk of issue "entry out of order" because of un-precise timestamp higher.

Unfortunately there is no much possibilities to tweak this behavior, any changes to reduce push frequency drive after a while result to "buffer limit exceeded" and which will result stoping of log file tailing on fluent-bit side.

Current used fluent-bit loki output plugin version from grafana seems to be stable enough. This plugin tested under high load over 5 days constantly, test scenario was up to 120 log spammer pods constantly produce every half second 1K logs and this logs are collected fully from fluent-bit and pushed to the loki, there was no issues like "entry out of order" or buffer limit issues observed with fluent-bit loki output plugin. Memory and CPU consumption was moderate, push latency was low stable.

**Comment by a-thaler** [comment]
Above investigations showed that a switch on base of the apache2 licensed Loki instance is not possible. With that, first a solution for Loki itself need to be found.
