### ISSUE TITLE
Kyma stuck in upgrade with faulty configuration overrides

### ISSUE THREAD

**Issue by 4kills** [kyma-project/kyma#12073]
**Description**
If a configuration override triggered via `kyma upgrade -s {CUR_VER} -o {FAULTY_OVERRIDE_YAML_FILE_PATH}` has a faulty configuration file, the kyma upgrade/installation will fail building that component, retry 5 (by default) times and then fail the installation completely. However, it is not possible to provide a new, non-faulty overrides.yaml, as another call to `kyma upgrade -s {CUR_VER} -o {PROPER_OVERRIDE_YAML_FILE_PATH}`. Returns an error, stating that the kyma installation is already in progress. This way, you are stuck in the upgrade and can't cancel it, as far as I know (I've looked extensively at the docs and other issues). 

Kubernetes cluster version 1.20.9 with Kyma version 1.24.4 on Gardener 1.51.3 with GCP hyperscaler and Gardenlinux 318.8.0. 

**Expected result**

Possibility to provide a non faulty file or cancel the installation. 

**Actual result**

Stuck in installation - with no (apparent/documented) way out of it. Had to delete cluster.

**Steps to reproduce**

1. Use this (faulty) logging-overrides.yaml. It is faulty because an **empty** `removeKeys` causes an issue when plugging the values into the template during the helm installation. 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: logging
    kyma-project.io/installation: ""
data:
  fluent-bit.config.outputs.loki.config.removeKeys:
 ```

2. Execute `kyma upgrade -s 1.24.4 -o logging-overrides.yaml`

3. Wait for the installation to reach the logging component and find the faulty logs via `kubectl logs -n kyma-installer kyma-installer-{YOUR_ID}` 
(in my example: 
```txt 
. . .
2021/09/09 10:00:38 [debug] StatefulSet is not ready: kyma-system/logging-loki. 0 out of 1 expected pods are ready
2021/09/09 10:00:40 [debug] StatefulSet is not ready: kyma-system/logging-loki. 0 out of 1 expected pods are ready
2021/09/09 10:00:42 [debug] StatefulSet is not ready: kyma-system/logging-loki. 0 out of 1 expected pods are ready
2021/09/09 10:00:44 [debug] superseding previous deployment 7
2021/09/09 10:00:44 [debug] updating status for rolled back release for logging
2021/09/09 10:00:44 Step error:  Details: Helm upgrade of release "logging" failed: template: logging/charts/fluent-bit/templates/daemonset.yaml:19:28: executing "logging/charts/fluent-bit/templates/daemonset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: logging/charts/fluent-bit/templates/configmap.yaml:124:30: executing "logging/charts/fluent-bit/templates/configmap.yaml" at <include "helm-toolkit.utils.joinListWithComma" .Values.config.outputs.loki.config.removeKeys>: error calling include: template: logging/charts/fluent-bit/templates/_helpers.tpl:67:20: executing "helm-toolkit.utils.joinListWithComma" at <.>: range can't iterate over nothingToIgnoreButStupidMethodNeedsIt.
Finding last known deployed revision to rollback to.
Performing rollback to last known deployed revision: 7
Helm rollback of release "logging" was successfull
2021/09/09 10:00:44 Warning: Retry number 1 (sleeping for 10[s]).
. . .
```
 ) 

4. Wait for the 5 retries
5. Try to apply a corrected yaml (adding some elements to the `removeKeys` field) via `kyma upgrade -s 1.24.4 -o {CORRECT_YAML}` 
6. See the error message that kyma is already installing. 

**Troubleshooting**

I tried: 
- `kubectl apply -f {PROPER_YAML}` which doesn't work, since lists are not allowed in config maps. 
- `kubectl apply -f {STRING_YAML}` where I tried placing a string for the `removeKeys` field, but that also crashed as the templating engine can't iterate over a string. 
- Modify the generated config map that can be found via `kubectl get conifgmaps -n kyma-installer`, which had no effect. 

What worked:  
Delete cluster, create  new one and install kyma with proper configuration file.

**Comment by a-thaler** [comment]
Hi @4kills, thanks for the detailed report. I can confirm that this is a problem. The installation is happening on server-side and the CLI mainly attaches to the running procedure. The installation state is determined by the status attribute of the installation resource and in case of an error it talks a long time till it gives up (so that the state will be "error".
I agree that this is a bad experience and we are changing the overall approach in the scope of [Kyma 2](https://github.com/kyma-project/kyma/issues/11337).
We mainly switch to a client-side installation which is not using any jobs but just plain resources to apply. With that it will be fast and only will apply the desired resource state.

As a workaround you can just modify the overrides manually in the cluster and re-trigger the upgrade by deleting the "kyma-installer" pod in the "kyma-installer" namespace. That will cause a new installation process which starts from the beginning, reading the new override set. Double-check that the label "action=install" is present on the installation resource.
