### ISSUE TITLE
Update Backend CR to allow additional Backend that leverages Jetstream

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12390]
Update the Backend CR to:

- [ ] create a proposal for the updated Backend CRD
  - [ ] multiple different backend types with their specific configuration
  - [x] https://github.com/kyma-project/kyma/issues/11368
  - [ ] the proposal should also investigate how the deployment mechanism would work in combination with the reconciler: the reconciler must not revert user made changes to the eventingbackend-cr as this would change the behaviour of the eventing system
- [ ] allow switching the Backend by specifying the active backend in the CR
- [ ] allow specifying the BEB secret using a reference to the secret (namespace / name )

**Comment by pxsalehi** [comment]
After spending a little bit of time trying to work on “Backend CR Proposal”, I find it very difficult to define the scope and requirements that I’m supposed to address in the proposal. The ticket only defines a few bullet points. However, as this is not a purely internal/technical topic (and will have impact on how a user would use Eventing), IMO it needs a much better defined user story, requirements and acceptance criteria. For example the expected behaviour in the following cases is not clear:

- Do subscriptions point to a specific backend or to no backend and are automatically assigned to the active backend?
- Do we have a CR for all supported backends already in the cluster after installation of Kyma Eventing? Or do we wait for the CR to be defined by the user? Or do we start with just one default backend, and wait for the creation of further backend CRs?
- If we are using an active backend which will be used by all subscriptions, does changing the active backend switch existing subscriptions?
- Assuming we have defined a CRD for `EvantingBackendType` (e.g. one for NATS, one for BEB), how does its lifecycle related to the subscriptions? E.g. if the user deletes a specific `EventingBackendCR`?
- In case of BEB, what is the expected behaviour when a user removes the secret that is pointed by the CR?

Questions like this (and many more) could be addressed in many different ways, and unless we agree on a specific user story, I believe writing a useful proposal might not be possible.

**Comment by mfaizanse** [comment]
Points to clarify:
- Do we have a default active backend for subscriptions?
- What about switching of subscriptions between different backends?
- And what about backend-specific configurations on subscriptions?

**Comment by k15r** [comment]
Will be covered as part of #13798
