### ISSUE TITLE
Proposal for jetstream stream usage

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12391]
- [x] proposal for how many streams we need: one per event-type or one global stream for all events
- [x] when to create streams: on first publishing vs. first subscription

**Comment by k15r** [comment]
The benefits of having multiple streams (eg one per app) are:
* we can per stream configure storage, max message size etc
* we can create the streams only when a subscriber exists for a given app
The drawbacks are: 
* the controller will be more complicated as it needs to configure and potentially remove streams during subscription reconciliation
* our goal is to reduce complexity for the user. Exposing all this configuration will have the opposite effect.

For now we will use only one stream for all event-types regardless of application.

**Comment by mfaizanse** [comment]
Would it be better to use separate stream per app from start? Once we start using persistence (with single stream for all) for events, won't it be difficult to migrate towards using separate streams later?

**Comment by marcobebway** [comment]
Assumption: One stream vs multiple does not have significant performance impact.

I think the [stream retention policy](https://docs.nats.io/using-nats/developer/develop_jetstream/model_deep_dive#stream-limits-retention-and-policy) should play a big part in the decision, because -from that perspective- if all event-types are treated the same then one stream should make sense, otherwise multiple streams would give more retention control per event-type/app/...etc.

**Comment by radufa** [comment]
If we will have multiple applications or tenants, each of them using different namespaces for Kyma subscriptions, we could uses a JS stream for each application/tenant/namespace. And so, an application/tenant with huge injection rate of events will not disturb the events processing for the other applications/tenants.
