### ISSUE TITLE
Generate helm charts automatically for usage in reconciler and local development

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12452]
**Description**

try to have one source of truth. That is being able to have `ko-apply` make targets which can use the output of `helm template`. We only need to keep changes in our Helm charts.

Flow should be:
1. go generate ; kustomize build helmchart > helm charts
2a. `helm template | kustomize build localdev | ko-apply`
2b. `helm template | k apply`

**Tasks**:
- [ ] investigate which kustomize/ko targets we already have and if they should be changed
- [ ] add make targets for both eventing-controller and EPP to render the helm templates and sync it with the kustomize manifest and do `ko apply`

**Comment by mfaizanse** [comment]
TODO: check if we can use the ko url for event-publisher-proxy instead of doing:
```
$(shell cd ../event-publisher-proxy; ko publish github.com/kyma-project/kyma/components/event-publisher-proxy/cmd/event-publisher-proxy -B > /dev/null)
```

**Comment by mfaizanse** [comment]
Currently `ko` only applies to the current working directory, and since `event-publisher-proxy` resides outside of the `eventing-controller` directory, `ko publish/build` cannot be applied from Makefile of eventing-controller. 

There is a feature request going on to add `-C` flag to KO to accept working directory, once that feature is added we can move to use the ko based url for event-publisher-proxy as well.

For now, lets keep:
```
$(shell cd ../event-publisher-proxy; ko publish github.com/kyma-project/kyma/components/event-publisher-proxy/cmd/event-publisher-proxy -B > /dev/null)
```

**Comment by mfaizanse** [comment]
The `make deploy` flow will be further optimised as part of [this](https://github.com/kyma-project/kyma/issues/13795) issue.
