### ISSUE TITLE
Allow developers to deploy their function code from git faster

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#12527]
**Description**

Currently fetching code changes from git repos is happening on main reconciliation loop which happens once every 5 minutes. As a developer using kyma runtime as a test environment that is causing bad development experience.

We should:
 - define poling interval in the GitRepository CRD
 - define a controller for GitRepository CRD and drive code pulling for git functions in that controller.
 
 
**Reasons**

Don't make users wait 5 minutes until their code changes are pulled and deployed as a new version of git function

**Comment by paschdan** [comment]
I think, this should be customizable in the git repo cr.

Additionally the sources should be fetched, after a function is created/updated, that is using a git repo as reference.

Usecase:

Imagine you have the following workflow:

* Code in Git Repo is merged to main brachn
* a tag is created
* a function cr, that points to an old tag is updated to use the just created tag

When the repo is not synced between tag creation and function build for the new reference (tag) and then the build will fail, because the reference is not found

**Comment by kwiatekus** [comment]
Instead of introducing dedicated re-queuing periods fro git functions, let's define a controller for GitRepository CRD and drive code pulling for git functions in that controller.

**Comment by kwiatekus** [comment]
GitOps related topics are tracked here 
https://github.com/kyma-project/kyma/issues/13125
