### ISSUE TITLE
skr-aws-svcat-migration-dev test fails

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12671]
**Description**

One test is failing (3 times today):
```
  1) SKR SVCAT migration test
       Should restart functions pods:
     Error: getaddrinfo ENOTFOUND api.a7427c9.kyma-dev.shoot.canary.k8s-hana.ondemand.comundefined
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
```

**Steps to reproduce**

See logs: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-aws-svcat-migration-dev/1462994334331703296

**Comment by wozniakjan** [comment]
root cause is that kube-apiserver no longer sends `selfLink` - https://github.com/kubernetes/kubernetes/pull/94397.
The javascript library we use for e2e tests relies on `selfLink` with dynamic deletion
https://github.com/kyma-project/kyma/blob/04da27f7a5e17cb8b91dd2e5ba5f35a2f8ac0f52/tests/fast-integration/utils/index.js#L221-L224
