### ISSUE TITLE
kyma-preview-integration-dev timeouts after 3 hours

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12727]
**Description**
The job kyma-preview-integration-dev fails regularly due to provisioning timeout. From the logs, you cannot say what is the root cause (which step). 

**Expected result**

Provisioning should be finished in less than 30 minutes. If some step takes more time it should be reported.

**Actual result**

These build failed due to timeout:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-preview-integration-dev/1464443900620967936
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-preview-integration-dev/1464383502295240704
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-preview-integration-dev/1464262705232744448
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-preview-integration-dev/1464202306714079232

**Comment by ksputo** [comment]
When reaching timeout, the runtime information and last operation status for the runtime will be fetched from KEB

**Comment by PK85** [comment]
@ksputo not only when timeout, always display runtime status from our runtime endpoint, where we are with that improvement?

**Comment by ksputo** [comment]
@PK85 added fetching runtime state in both cases: ordinary failure (operation status != succeeded) and exceeding timeout, details: https://github.com/kyma-project/kyma/pull/12787

please note that
>From the logs, you cannot say what is the root cause (which step).

is not technically possible at the moment, because KEB does not update the operation description with the "current" step during provisioning. Exceeding timeout without operation reaching state `failed` usually means that the operation takes longer than it should and is still `in progress` - in this case we have no additional information (for example on which step are we stuck), but this additional log contains operation ID, so the corresponding logs can be tracked. In case of failures other than timeout in the test (operation state == `failed`), the description should contain the proper error message.
