### ISSUE TITLE
Installation of ORY with gcloud-mysql database fails

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#12730]
**Description**

ORY installation with gcloud-mysql database fails.

**Expected result**

ORY installation succeeds with no errors.

**Actual result**

ORY installation fails with the following error:
```sh
 invalid json file "/secrets/cloudsql/gcp-sa.json": open /secrets/cloudsql/gcp-sa.json: no such file or directory
```

**Steps to reproduce**

- Update the production profile for ORY that includes the gcloud-mysql configuration details like sajson, instance name, DB name, DB type etc.
- Install kyma 2.0 using the command `kyma deploy -s local -w <local path> -p production`

**Troubleshooting**

**Comment by veichtj** [comment]
Quick spot on the root cause:
During DSN creation the DBType "mysql" is always checked before the "gcloud" persistence case, so thats why the DSN is for gcloud+mysql always created like for external mysql. In the following the gcloud-sqlproxy can not read the saJson as it was not created.

**At least following references needs to be adjusted:**

- https://github.com/kyma-incubator/reconciler/blob/267ffd2ab61a762fc46143af30c610698829df46/pkg/reconciler/instances/ory/db/db.go#L169
- https://github.com/kyma-incubator/reconciler/blob/267ffd2ab61a762fc46143af30c610698829df46/pkg/reconciler/instances/ory/db/db.go#L91

**Comment by strekm** [comment]
ORY Hydra is deprecated
