### ISSUE TITLE
Replace google-containers_pause-amd64 with low-maintanance container

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#12897]
**Description**

Its unjustified to have high maintanance `google-containers_pause-amd64` with vulnerable glibc as an idle container image 

**Reasons**

We use `google-containers_pause-amd64` as an idle container for the serverless docker registry cert deamon set.
Due to the fact that it includes `glibc` dependency it is high maintenance regarding security. Maybe instead of constantly triaging the vulnerabilities we should replace the pause container with simpler idle container w/o glibc

**Comment by Cortey** [comment]
Pause containers use glibc, because of [this logic](https://github.com/kubernetes/kubernetes/blob/master/build/pause/linux/pause.c) that they use to make sure they're the first process and to clean up any orphaned processes. It makes it impossible to find a pause container image that wouldn't rely on glibc.
[More detailed explanation](https://www.ianlewis.org/en/almighty-pause-containe)
