### ISSUE TITLE
Restore blocker: Service instance in error state after restore from ark backup

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/kyma#1294]
**Description**

When a service instance is restored from Ark's backup helm broker is trying to create the helm release once again. 

Because such release already exists (helm config maps with releases data are also restored) helm broker get's an error. And finally the service instance is also in error state.

From helm broker logs:
```
{"level":"info","log":{"message":"started handling request","method":"PUT","remote":"10.20.0.23:46452","request":"/v2/service_instances/faa1cadb-d148-11e8-98ce-0a580a10001d?accepts_incomplete=true","time":"2018-10-16T14:16:58.317Z"}}
{"level":"info","log":{"action":"provision","message":"action response","resp:async":true,"resp:operation:id":"01CSYKS96PPA3PX4X1V17ME2ZC","service":"server","time":"2018-10-16T14:16:58.445Z"}}
{"level":"info","log":{"message":"completed handling request","method":"PUT","remote":"10.20.0.23:46452","request":"/v2/service_instances/faa1cadb-d148-11e8-98ce-0a580a10001d?accepts_incomplete=true","size":63,"status":202,"time":"2018-10-16T14:16:58.445Z","took":128609498}}
{"level":"info","log":{"message":"Merging values for operation [01CSYKS96PPA3PX4X1V17ME2ZC], releaseName [hb-redis-enterprise-faa1cadb-d148-11e8-98ce-0a580a100], namespace [qa], bundlePlan [enterprise]. Plan values are: [map[resources:map[requests:map[memory:96Mi]]]], overrides: [map[redisPassword:SWxwQmNVVjJlbU5QUVc4aQo= resources:map[requests:map[memory:96Mi]]]], merged: [map[resources:map[requests:map[memory:96Mi]] redisPassword:SWxwQmNVVjJlbU5QUVc4aQo=]] ","service":"provisioner","time":"2018-10-16T14:16:58.446Z"}}
{"level":"info","log":{"message":"Installing chart with release name [hb-redis-enterprise-faa1cadb-d148-11e8-98ce-0a580a100] in namespace [qa]","service":"helm_client","time":"2018-10-16T14:16:58.446Z"}}
{"level":"info","log":{"message":"started handling request","method":"GET","remote":"[::1]:59086","request":"/statusz","time":"2018-10-16T14:16:58.514Z"}}
{"level":"info","log":{"message":"completed handling request","method":"GET","remote":"[::1]:59086","request":"/statusz","size":2,"status":200,"time":"2018-10-16T14:16:58.514Z","took":113937}}
{"level":"info","log":{"message":"started handling request","method":"GET","remote":"10.20.0.23:46452","request":"/v2/service_instances/faa1cadb-d148-11e8-98ce-0a580a10001d/last_operation?operation=01CSYKS96PPA3PX4X1V17ME2ZC\u0026plan_id=a6078798-70a1-4674-af90-aba364dd6a56\u0026service_id=a2257daa-0e26-4c61-a68d-8a7453c1b767","time":"2018-10-16T14:16:59.58Z"}}
{"level":"info","log":{"action":"getLastOperation","instance:id":"faa1cadb-d148-11e8-98ce-0a580a10001d","message":"action response","operation:id":"01CSYKS96PPA3PX4X1V17ME2ZC","resp:operation:desc":"provisioning failed on error: while installing helm release: while installing release from chart with name [hb-redis-enterprise-faa1cadb-d148-11e8-98ce-0a580a100] in namespace [qa]: rpc error: code = Unknown desc = a release named hb-redis-enterprise-faa1cadb-d148-11e8-98ce-0a580a100 already exists.\nRun: helm ls --all hb-redis-enterprise-faa1cadb-d148-11e8-98ce-0a580a100; to check the status of the release\nOr run: helm del --purge hb-redis-enterprise-faa1cadb-d148-11e8-98ce-0a580a100; to delete it","resp:operation:state":"failed","service":"server","time":"2018-10-16T14:16:59.584Z"}}
{"level":"info","log":{"message":"completed handling request","method":"GET","remote":"10.20.0.23:46452","request":"/v2/service_instances/faa1cadb-d148-11e8-98ce-0a580a10001d/last_operation?operation=01CSYKS96PPA3PX4X1V17ME2ZC\u0026plan_id=a6078798-70a1-4674-af90-aba364dd6a56\u0026service_id=a2257daa-0e26-4c61-a68d-8a7453c1b767","size":539,"status":200,"time":"2018-10-16T14:16:59.584Z","took":4264952}}
{"level":"info","log":{"message":"started handling request","method":"GET","remote":"[::1]:59100","request":"/statusz","time":"2018-10-16T14:17:00.098Z"}}
```

Describe of service instance:
```
 Name:        redis-instance
  Namespace:   qa
  Status:      OrphanMitigation - Provision call failed: provisioning failed on error: while installing helm release: while installing release from chart with name [hb-redis-enterprise-faa1cadb-d148-11e8-98ce-0a580a100] in namespace [qa]: rpc error: code = Unknown desc = a release named hb-redis-enterprise-faa1cadb-d148-11e8-98ce-0a580a100 already exists.
               Run: helm ls --all hb-redis-enterprise-faa1cadb-d148-11e8-98ce-0a580a100; to check the status of the release
               Or run: helm del --purge hb-redis-enterprise-faa1cadb-d148-11e8-98ce-0a580a100; to delete it @ 2018-10-16 14:16:59 +0000 UTC
  Class:       redis
  Plan:        enterprise

Parameters:
  redisPassword: SWxwQmNVVjJlbU5QUVc4aQo=
  resources:
    requests:
      memory: 96Mi

Bindings:
           NAME                   STATUS
+------------------------+-----------------------+
  redis-instance-binding   ErrorInstanceNotReady
```

**Steps to reproduce**

1. Install kyma
2. Execute example from https://github.com/kyma-project/examples/blob/master/service-binding/lambda/README.md
3. Create backup with heptio ark (version >= v0.9.7)
4. Install new kyma cluster
5. Restore the backup

**Troubleshooting**

**Comment by mjasinski5** [comment]
Remember about testing this change with other task relateds to backup: #1398

**Comment by PK85** [comment]
What's a status? I see no plan how to solve it and no PR.

**Comment by jasiu001** [comment]
**Causes of the problem**

During restore backup operation in the first place they are restored all resources connected with helm`s chart (like Pods) and information about
releases (including state of release). After this step Service Instance is restored together with unique id connected with specific instance. Because of
release name is created from mentioned id, bundle name and plan name there is a conflict between helm list with releases name and "new" instance name.

After restore backup, helm broker etcd storage is empty so method `IsProvisioning()` which should check if release already exist returns false. Other explanation
why `IsProvisioning()` method returns false and etcd storage wouldn't be empty is restore entry in etcd about instance has no `succeeded` state.

Pull Request #2150 before install check on releases list if release already exist and if is in `deployed` state and if do then helm broker update release.

**Issues occurring during backup single namespace**

During restore backup operation for one namespace could occur problems for the following reasons:
1) If before restore backup we want to remove namespace, first we need to remove (deprovision) all instances. Remove instance does not remove information
   about this instance from etcd storage (it changes entry state). After restore `IsProvisioning()` method returns false because key in etcd already exist but
   is not in `succeeded` state and `create` type, error occurse during insert entry to etcd operation.
2) Information about helm releases are saved in confingmap in `kube-system` namespace, rest of the release resources are in removed and restored namespace.

**ServiceBinding issue**

After restore backup there is also bug connected with ServiceBinding. After restore resources `ownerReferences` field for `Secrets` are missing so Service Catalog will return
error `Secret is not owned by ServiceBinding`, this issue is reported here https://github.com/heptio/ark/issues/816 and to fix it is necessary to use ark plugin
https://github.com/kyma-project/kyma/blob/master/tools/ark-plugins/internal/plugins/owner_reference.go.
