### ISSUE TITLE
`RBAC: access denied` when opening grafana after kyma 2.0 migration

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#12983]
**Description**

Cant access grafana UI after migration to kyma 2.0 (I followed migration docs. See _Steps to reproduce_)

**Expected result**

I would like to access grafana via custom OIDC of my choice

**Actual result**

`https://grafana.{mydomain}`

<img width="429" alt="Screenshot 2022-01-04 at 12 33 34" src="https://user-images.githubusercontent.com/6783567/148053159-f692d437-67f5-4168-8767-ae33eda31cba.png">

Also, there are navigation nodes to Kiali and Jeager - none of which work
<img width="290" alt="Screenshot 2022-01-04 at 12 50 32" src="https://user-images.githubusercontent.com/6783567/148054984-d2402796-73b3-4a42-ae0c-2701dba848cc.png">

**Steps to reproduce**

I installed v1.24.8 on gardener cluster via kyma cli (`kyma install -s 1.24.8`)
I deployed my functions and could monitor them via grafana exposed via DEX. (*Open Grafana on 1.24.8 Kyma*!)
I migrated  to 2.0 via kyma 2 cli (`kyma deploy -s main`)
I cleaned up orphaned resources via the [script](https://raw.githubusercontent.com/kyma-project/kyma/main/docs/assets/1.24-2.0-remove-deprecated-resources.sh)
I followed a [guide](https://kyma-project.io/docs/kyma/latest/04-operation-guides/security/sec-06-access-expose-kiali-grafana/#documentation-content) to expose grafana in secure way
I opened kyma dashboard via CLI (`kyma dashboard`)

Kyma CLI version: stable-43-g813bcd9
Kubernetes version: 1.20.12

**Comment by skhalash** [comment]
After some investigation, I found out the root cause. Due to some unknown reason the Grafana virtual service was pointing to the `monitoring-grafana` host instead of the `monitoring-grafana-secured`. The traffic was routed from the ingress gateway directly to the Grafana server, skipping the proxy. It would be a disaster if we didn't have the authorization policy in place since Grafana is running in the unprotected anonymous mode.

However, it is still not clear why the virtual service was not upgraded during the upgrade.

**Comment by kwiatekus** [comment]
I used some old kyma CLI version.
When I run the kyma deploy operation with `Kyma CLI version: 2.0.0` everything works as expected
