### ISSUE TITLE
Improve Install section on website entrypoint

### ISSUE THREAD

**Issue by nachtmaar** [kyma-project/kyma#13014]
**Description**

The short installation instructions for Kyma are listed here: https://kyma-project.io/ and look as in the attached screenshot.
<img width="1490" alt="Screenshot 2022-01-10 at 13 31 23" src="https://user-images.githubusercontent.com/8013145/148766308-0136267b-90f8-4d27-9484-6f24cfcc0348.png">

After a discussion with @tobiscr we propose two improvements:

1. We  wonder why for the installation of Kyma `curl` is used. The installation is hardcoded for Mac OS only, hence it could use `brew install kyma-cli` instead which would be even shorter.
2. The second improvement would be to list the kyma cli installation instructions for `every supported Operating System` directly on the main website via a `tab` like here
<img width="402" alt="Screenshot 2022-01-10 at 13 37 08" src="https://user-images.githubusercontent.com/8013145/148767011-d7fb75fe-eb2f-409b-8135-236111b423fb.png">

**Area**

CLI

**Reasons**

- The entrypoint of the Kyma website should be as short as possible while still providing the necessary information to the end user. While curl is a valid option for installing the kyma cli, using `brew` (on Mac OS) is even shorter.
- Having a tab to select the Operating System is not taking a lot of space on the website and allows to use the package manager on each OS (brew, choco etc.)

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by skhalash** [comment]
I've recently tried out installing Kyma on Ubuntu and bumped into the following issue: the Docker version I installed previously via `apt` as described [here](https://docs.docker.com/engine/install/ubuntu/) was less than the one k3d v5 requires. The error message was cryptic and I found the problem by just trying out different things. So, we need to add installing the right version of Docker to the docs as a prerequisite. Again, on a Mac, we assume that `brew install docker` would always install the most recent version. However, on Linux it is different for every package manager.

**Comment by NHingerl** [comment]
Looking at @nachtmaar 's screenshot, I also don't like that the set of instructions in the code box and in the fake screenshot aren't identical. That's confusing. 
- If someone just scrolls down and looks at the screenshot without reading the text, they'll fail because they don't have kyma cli installed, but they'll have the impression that installing dashboard is required. 
- If someone only reads the left-hand instructions, they'll successfully install kyma cli and kyma (provided they're on macOS), but they're clueless what's up with that dashboard thingy.

Also, if we choose to present only mac instructions on the landing page, we should point out where the instructions for other OS are.

**Comment by NHingerl** [comment]
The instructions on the left side have been removed.

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/76950046/158345599-0f3efd71-5ccd-4558-93e5-80f48f0f8a43.png">

**Comment by nachtmaar** [comment]
I like the proposed solution. Installation instructions are detailed in the `options` link.
