### ISSUE TITLE
Document how to fix failing kaniko builds on k3d

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/kyma#13085]
**Description**

Describe what the user can do in case `Kyma` is installed locally on k3d and failing Kaniko builds with error `kaniko should only be run inside of a container, run with the --force flag if you are sure you want to continue`. 

We can add mini-tutorial or simple notes only with information on how and where override kaniko arguments to add `--force` flag before installation

**Area**

* Serverless

**Reasons**

User should know what he can do with a bug like this and how it can be easily fixed

**Assignees**

@kyma-project/technical-writers

**Attachments**

- https://github.com/kyma-project/kyma/issues/13051

**Comment by a-thaler** [comment]
Can we add the additional step maybe to the CLI command logic? I think otherwise it is a very bad user experience. Can you provide the instructions when to do what in the setup phase?

**Comment by nachtmaar** [comment]
@a-thaler The workaround is only required in certain cases (which we do not have yet figured out). It is currently affecting me and one more person. Would you still like to add a step to the CLI-command logic ? 🤔
The CLI would have to figure out that we are in this `special case` and then change the specification of the serverless-controller to use the `--force` flag. Because if we change it for very Kyma user, you will get the following message:

````
$ k logs myapp-build-gmzhz-9rnmm
time="2022-01-14T08:25:16Z" level=warning msg="kaniko is being run outside of a container. This can have dangerous effects on your system"
```

Which does not sound too good

**Comment by a-thaler** [comment]
Then a troubleshooting guide sounds better, I agree
