### ISSUE TITLE
Automate bumping images on PRs

### ISSUE THREAD

**Issue by ammarlakis** [kyma-project/kyma#13225]
**Description**

We need to update images automatically on PRs.

**Reasons**

Automate the manual task of updating images tags.

**Attachments**

**Comment by dekiel** [comment]
Please research on this topic. We need to understand how images are updated and used in other repos and how we can apply some automation there.

**Comment by Ressetkk** [comment]
Automation can be done using generic-autobumper tool. There are some prerequisites to do:
* [ ] All images we build need to be tagged with [semantic versioning principles ](https://semver.org/) in consideration - improvements in building scripts. Since all of our images in kyma repo are tagged only by commit short SHA it needs to be adjusted to other format compatible with semver, like `vDATE-shortSHA`.
* [ ] All repositories must have properly configured autobump config and periodic prowjob. Otherwise it will not work.

@ammarlakis is this issue only affecting kyma repo? If so then this issue should be transferred there. In test-infra we have automatic bumps for images.

**Comment by dekiel** [comment]
By using `vDate-shortSHA` are we able to order more than one update per day? How ordering works for tag schema?
How using periodic job for bumping images versions in values.yaml files would work for developers using PR-number tags?

**Comment by Ressetkk** [comment]
> By using `vDate-shortSHA` are we able to order more than one update per day? How ordering works for tag schema?

Of course. Once there is a new commit there will be totally different tag since commit sha will differ. Generic bumper will then pick a new tag and update the files accordingly.

> How using periodic job for bumping images versions in values.yaml files would work for developers using PR-number tags?

Simply will not work. Our pr images tag convention is not compliant with semver principles.

Additionally there is problem because right now we had recent changes in image structure and instead of simple image we have a struct that contains granular information about Images. The tool we use does not support such structs

**Comment by ammarlakis** [comment]
The initial proposal was to provide tool to the developers that can be run to update the images locally, and this tool would use a config file like the following:
```yaml
- trigger: /path/to/app/dir
  update_file: /path/to/yaml/where/app/image/used
  key: ".image.something"
  value: "PR-123"
```
Such file can help link directory changes to change in image tag, so by updating the trigger directory you know you should update this image tag. Enforcing the update can be added as a prow guard job.

After a talking with @Ressetkk and @dbadura , the following main concerns were raised:
- introducing a central config file will be a cause for merge conflicts, degrading developer experience
- the manual step is still there, what we remove is the need of knowledge to where each image is being used
- developers already know what resource to change in case of image update, and it's usually just one change, so not a big deal
- some PRs are expected to go differently, like security updates, as the change and the bump are raised in two different PRs
- we may need to change the workflow altogether to autobump the images after pushing to master, not in the PR

There may still be some value in using validation on PRs to check if the right tag is being applied, but using meta information from dockerfile itself without the need to a central config file.

**Comment by dekiel** [comment]
The question is do developers should update image tag in yaml definitions every time? I believe they should. If they don't then all tests which use this yaml files will not test their changes. With that assumptions introducing this validation make sense. We should then invest in implementing initial idea of automated changes on PR in case validation failed.

**Comment by ammarlakis** [comment]
Following sig-quality meeting, the final iteration would be:
- Add a notation in dockerfile that would indicate the location of the file where the image is being used and the tag key to be updated
- Add a pre-job that will update the image tag automatically with PR tag
- Add a post-job that will update the image tag automatically with commit sha tag.

**Comment by ammarlakis** [comment]
The initial idea was being implemented [here](https://github.com/kyma-project/test-infra/pull/5201), but following several discussions we had to pivot. Now in the pre-job, we don't want to automatically update the images but to create a guard that provides the command for the devs to update the images.
We need two functionalities for this;
1. Know which images were built/updated in this PR;
    Which we can know with either by
        1. Querying the collection `gcr-kyma-project` in firestore, which stores the results of gcr scanning, which in turn reflects the images that have been built. The downside is that we will have to write code to query firestore, and filter the results to get only the objects where `outdated: false`, since firestore doesn't support compound queries with `and` or `or`. The following query can be used to get the initial result `.collection("gcr-kyma-project").where("tags", "array-contains", "PR-12345")`
        2. Querying gcr repository for images that have the tag `PR-12345`. This can be done on two steps, first getting all the images repositories in gcr, then querying each for tags that match a filter. Filtering tags is included in gcloud cli options, but listing images needs pagination.
2. Update these images in `values.yaml` files.
    First thought, we can use `image-url-helper` to update the tags, but it doesn't have options to update a specific image. Another suggestion is to do the update using `yq`, with which we can create a more complicated query.

**Comment by dekiel** [comment]
@kyma-project/prow
For both solutions for functionality one I see following problems.
1. From query of firestore or GCR we can get two images with the same tag. This two images can come from two different repositories, where we have the same PR number. We don't have an easy way to identify which image is the one we are looking for.
2. We need a condition when to start our prowjob which will do such queries. This condition ideally will trigger a prowjob only when there was a new image build. We don't have a way to ensure that. We could run such prowjob for any change in files containing any code, dockerfiles or yaml files. I'm not sure if this will not trigger a prowjob for scenarios where new image was not build. If yes we need some way to finish prowjob with success without getting na image URL. This approach will be not reliable.

Crucial part is get an image URL which is build and get it at the time of building. I was thinking about following solution.

For updates on PRs.
1. We hook in to the build process in Makefile. A execution of makefile is aware of full image URL. We hook by adding new .PHONY target and force it execution using [makefile feature](https://www.gnu.org/software/make/manual/html_node/Force-Targets.html). Because a makefile is executed when a new image is build we make sure our logic is executed too. Let's call this logic as tag_bumper.
2. The tag_bumper logic will collect a full image URL, an org and repo where files where changed and check if it's running as part of presubmit job. All this details will be published to pubsub topic for Prow [sub](https://github.com/kubernetes/test-infra/blob/7d33423d30a6ed94eb6ff276db3e1d0ca98e6e41/prow/cmd/sub/README.md#sub) component. A data which we need to transfer from this prowjob to another one can be transfered as environment variables, labels or maybe as annotations. The tag_bumper will listen on another pubsub subscription to get confirmation a message it send triggered new prowjob or we can use a job_guard which will monitor PR contexts to make sure next prowjob was started. If next prowjob was started report success otherwise failure. 
3. Prow sub will get a pubsub message and run a presubmit prowjob. It will use data from pubsub message to update a values.yml file. Because a pubsub message will contain image full URL it's easy to find locations where to update an image tag. A pubsub message will contain a PR number too, so sub will add a prowjob execution as a context to the PR.
4. A prowjob started by sub will check if values.yml files need an update and commit to the PR updated image tags. A new commit on PR will cause a tests to start again and run with correct image tags.

For updates on main branch.
1 - 3. First three steps will be exactly the same with the difference a prowjob scheduled by sub will be a postsubmit. This will be detected by tag_bumper when it checks if it runs in a presubmit or postsubmit prowjob. Based on this check tag_bumper will publish valid pubsub message accordingly.
4. Postsubmit triggered by sub will generate a semver compatible tag, and create a PR with changes in values.yml files.
5. A PR with changes in values.yml file will trigger test if a new tag is newer than the one already present on main branch. In case newer tag is present a PR will be closed.
6. A bot will provide automated approval of changes based on condition that PR was created by automation dedicated bot user and the only changed files are values.yml.
7. Tide will merge changes.

As a next step we can detect such postsubmit prowjobs were merged and run protecode scans for semver tag immediately.

**Comment by Ressetkk** [comment]
The PR images are used for testing the workflow. Those are used for convenience of the devs so they can use their functionalities quick, after the PR is merged.

I see some problems with the flow itself:
* PR images are built from the current branch of the fork the dev is working
* The image tag is not compliant with the semantic versioning, which I said earlier in the thread
* We don't want PR images at all on the repo

I know that on pull requests we run integration and perf tests that need to use kyma resources and images to install Kyma. Using PR images is a hard requirement and I fully acknowledge that. However as a developer I wouldn't want my PR to be edited by an automation every time I push the changes to the repo. It gives me problem with updating my local repository and keeping change history both on my local git and on published fork.

I would rather tackle the problem a little bit differently:
1. How can I notify my jobs that PR image has been built if ProwJobs are separate entities and don't depend on each other?
2. How can I fetch the PR image and operate on that inside the job?

For the first concern I see no problem with using firestore. For storing the images that have been built in specific PR is actually nice to have.
The actual problem comes with the second part. As developers don't give a damn about bumping the images manually, I think they will certainly have problems if something updates their PR every time they change the component without their consent. So with that - we can actually use the functionality of installing Kyma from local sources. Here's how:

1. PR image gets built and pushed to the registry. After that a new record is created in firestore that contains all information about which images were built.
2. Another tool which is running before provisioning phase blocks the test pipeline and waits until the image is ready.
3. Once the images are fetched the automation does **in-place** replacement in the `values.yaml` for the images that have been created, provisions Kyma cluster and installs Kyma from edited local sources.

With that Developer doesn't need to update their local development branch every time they push something, because the automation made a commit into their branch.

For the updates on main branch:
As the values.yaml have not been changed at all we can rely on autobump solutions that we have in our test-infra, so the bumps are fully automated.
1. New image is built for component
2. Periodic auto bumper job runs every 15 minutes and listens for the changes in the defined images on registry
3. If there is a new image creates PR with updated images
4. Ideally PR is merged unattended and everyone is happy

Of course this will require to completely overhaul the tags and force it to meet the semantic versioning, as I stated in my previous comment. But it will give us more flexibility in the future.

Additionally we will have to reconsider if the struct we created for the images really satisfies our needs and maybe instead of adding sophisticated structure we should consider switching back to usual `path/to/registry:tag` and accomodate String parsing in our tools, so we can re-use our current auto bumping solution...

**Comment by dekiel** [comment]
Here @ammarlakis wrote devs already agreed to have something automatically update their PRs.
> Following sig-quality meeting, the final iteration would be:
> 
> * Add a notation in dockerfile that would indicate the location of the file where the image is being used and the tag key to be updated
> * Add a pre-job that will update the image tag automatically with PR tag
> * Add a post-job that will update the image tag automatically with commit sha tag.

With your solution there is a delay between merging a PR and updating image tag in values.yaml file on main branch, to point to the current version. This might be the source of issues if something will run with such setup. I expect this kind of issues are difficult to troubleshoot.
We created the data structure in values.yaml file for some purposes. What is an impact of such change on the solution relaying on that structure? What changes that requires in tools using that data structure? If I'm not wrong protescan use it. We plan to use it for pushing to different OCI registries too.
We said today that firestore as a source can produce two or more image URLs for the same PR number. How you plan to deal with that?
How you plan to hook to tests a tool that updating image tag before installation?

**Comment by ammarlakis** [comment]
After discussions with several developers, we ended up with the following conclusion;
1. Developers prefer explicitly updates and tests and keeping the git branch reflection of truth.
2. We are using forks not branches, so we can't push changes.
This leaves us with only one approach for pre-jobs that is a guard that checks whether an image was update in `values.yaml` files or not, and notifies the developer in case an update was needed.

**Comment by kasiakepka** [comment]
With the fact that we are going through SLC-29 certification and that we are going to sign images we must not allow pushing PR images to the main branch. With the modularisation we will treat master like release and each commit could result in a release.

**Comment by dekiel** [comment]
This is not clear yet that we will use CD from main branch. Even with CD approach we need to run some validation at the time of release if all pieces are in places. For example if image was promoted from PR repo to PROD repo.
With such validation at release time we can relay on automation updating main branch on PR merge. We can replace PR tags with commit SHA tags, replace image name to image hash digest, sign image or even build a new image if we will stick to squash merge. Main branch state would be invalid for short period of time.

**Comment by dekiel** [comment]
Requirements and possibly needs for such solution will change because of modularisation.
