### ISSUE TITLE
Installation timeout on eventing component

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#13283]
**Description**

Some pipelines fail due to timeout on installing eventing component:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-alpha-integration-production-gardener-azure/1489525613466226688/build-log.txt

**Comment by marcobebway** [comment]
Triggered the job 28 times, and there was 9 failures.

Summary of the failures:

1. Random components failed to be reconciled (e.g. istio-configuration, ory, rafter, tracing, helm-broker, service-catalog):
  - https://storage.googleapis.com/kyma-prow-logs/logs/marcobebway_test_of_prowjob_kyma-alpha-integration-production-g/1490726424435232768/build-log.txt
  - https://storage.googleapis.com/kyma-prow-logs/logs/marcobebway_test_of_prowjob_kyma-alpha-integration-production-g/1490726999621111808/build-log.txt
  - https://storage.googleapis.com/kyma-prow-logs/logs/marcobebway_test_of_prowjob_kyma-alpha-integration-production-g/1490727241670201344/build-log.txt
  - https://storage.googleapis.com/kyma-prow-logs/logs/marcobebway_test_of_prowjob_kyma-alpha-integration-production-g/1490727489721339904/build-log.txt

2. Eventing component failed to be reconciled:
  - Because of Kubernetes scheduling issue: https://storage.googleapis.com/kyma-prow-logs/logs/marcobebway_test_of_prowjob_kyma-alpha-integration-production-g/1490726916129296384/build-log.txt

  ```bash
  $ kubectl describe pod eventing-nats-0 -n kyma-system

  Name:           eventing-nats-0
  Namespace:      kyma-system
  Priority:       0
  Node:           <none>
  Status:         Pending  
  Events:
    Type     Reason            Age   From               Message
    ----     ------            ----  ----               -------
    Warning  FailedScheduling  11m   default-scheduler  0/1 nodes are available: 1 Insufficient cpu.
    Warning  FailedScheduling  11m   default-scheduler  0/1 nodes are available: 1 Insufficient cpu.
  ```
  - Because of `istio` issue: https://storage.googleapis.com/kyma-prow-logs/logs/marcobebway_test_of_prowjob_kyma-alpha-integration-production-g/1490997239097593856/build-log.txt

  ```bash
  $ kubectl describe statefulset eventing-nats

  Name:               eventing-nats
  Namespace:          kyma-system
  Replicas:           3 desired | 1 total
  Events:
    Type     Reason            Age                   From                    Message
    ----     ------            ----                  ----                    -------
    Normal   SuccessfulCreate  22m                   statefulset-controller  create Pod eventing-nats-0 in StatefulSet eventing-nats successful
    Normal   SuccessfulCreate  22m                   statefulset-controller  create Pod eventing-nats-1 in StatefulSet eventing-nats successful
    Normal   SuccessfulCreate  22m                   statefulset-controller  create Pod eventing-nats-2 in StatefulSet eventing-nats successful
    Warning  FailedCreate      18m                   statefulset-controller  create Pod eventing-nats-1 in StatefulSet eventing-nats failed error: Internal error occurred: failed calling webhook "auto.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": context deadline exceeded
    Warning  FailedCreate      18m (x8 over 18m)     statefulset-controller  create Pod eventing-nats-1 in StatefulSet eventing-nats failed error: Internal error occurred: failed calling webhook "auto.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": dial tcp 10.243.110.67:9443: connect: connection refused
    Warning  FailedCreate      18m                   statefulset-controller  create Pod eventing-nats-1 in StatefulSet eventing-nats failed error: Internal error occurred: failed calling webhook "auto.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": no endpoints available for service "istiod"
    Warning  FailedCreate      6m14s (x18 over 17m)  statefulset-controller  create Pod eventing-nats-0 in StatefulSet eventing-nats failed error: Internal error occurred: failed calling webhook "auto.sidecar-injector.istio.io": Post "https://istiod.istio-system.svc:443/inject?timeout=10s": no endpoints available for service "istiod"
  ```

I think we can close this ticket for now because the failures are not related to the Eventing component reconciler or the Eventing tests.
