### ISSUE TITLE
Fix socket hangup during test execution

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13375]
**Description**
The job kyma-alpha-integration-production-gardener-azure failed once with socket hang up errors in monitoring test. It happened in other jobs as well, not only in the monitoring area. Please check if we can make the port-forwarding more resilient (re-connect on every usage) or maybe use an alternative approach like using the apiserver proxy feature.

See https://storage.googleapis.com/kyma-prow-logs/logs/kyma-alpha-integration-production-gardener-azure/1493088901512826880/build-log.txt

**Comment by dennis-ge** [comment]
The test failed because the Port-Forwarding of the Prometheus UI broke. The reason for this is unclear, it is possible that the Prometheus pod stopped working and then the socket connection got closed but it is also possible that the connection broke because of a network issue. 
My proposal is to explicitly check at the beginning of the [monitoring](https://github.com/kyma-project/kyma/blob/main/tests/fast-integration/monitoring/index.js) if the Prometheus UI is accessible/reachable. If this is the case, everything should work as expected. If not, we can fail the test with a message, e.g. `Prometheus UI is not reachable`.

**Comment by Sawthis** [comment]
The job [kyma-alpha-integration-production-gardener-azure](https://status.build.kyma-project.io/?type=periodic&job=kyma-alpha-integration-production-gardener-azure) is green since Apr 02 10:05:40. @a-thaler @dennis-ge please reopen the issue if needed.

**Comment by a-thaler** [comment]
The solution is not enough, it is happen more frequent and just improving the error message is not sufficient.

Here just one evidence: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1519/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1511388569774592000#1:build-log.txt%3A466-552

As a port forwarding connection can be ended at any time from the server side, I suggest to check the connection before executing the actual test call and re-establish the connection in case it was ended.

Alternatively, why not simply using the apiserver api for doing proxy calls like busola is doing it? Might be a more simple solution then doing actual port-forwarding via the local machine

**Comment by jakobmoellersap** [comment]
Does this also affect pre-main-control-plane-reconciler-e2e-latest-release as can be seen in https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1519/pre-main-control-plane-reconciler-e2e-latest-release/1511267705750032384#1:build-log.txt%3A473-744 ? Or is this a different issue?

**Comment by a-thaler** [comment]
As far as I understand the problem still exists for the logging test case, reopening the ticket

**Comment by skhalash** [comment]
/retitle Fix socket hangup during test execution
