### ISSUE TITLE
Provide a way to integrate a log UI dynamically into the pod and lambda view

### ISSUE THREAD

**Issue by brendandobbs** [kyma-project/kyma#140]
The logging ui should be integrated smoothly into the existing pod and lambda views. Investigate how that can be achieved having in mind that the logging ui might be optional. And apply it.

AC:
- Propose a way how to integrate the view (for example by adding a new option to the actions dropdown) and apply it.
- Assure that the integration can be done dynamically (for example the action is configured by the log UI and will be displayed only if installed)

**Comment by a-thaler** [comment]
I integrated the issue into the overall epic and re-phrased it to solve the integration aspect. The initial scope of the issue will be solved by the epic itself.

**Comment by hardl** [comment]
Proposal for an MVP solution, in addition to the above ACs:
Action in Pods and Lambdas list link to single log ui cmf we already have (only if installed ofc) with (node-)parameter(s) that pre-selects the "instance(?)" there.
For lambdas, do a query for labels "function={lambdaName}", if possible. Otherwise determine the pod(s) by this label.

**Comment by a-thaler** [comment]
Sounds awesome, let's do it

**Comment by brendandobbs** [comment]
Sounds good to me. Any chance we could also filter the health checks from the logs as well? e.g.
`::ffff:127.0.0.1 - - [13/Mar/2019:21:31:06 +0000] "GET /healthz HTTP/1.1" 200 2 "-" "curl/7.38.0"`

The health check is adding a lot of noise to the logs at the moment.

**Comment by kwiatekus** [comment]
Please provide input for : https://github.com/kyma-project/console/issues/594
