### ISSUE TITLE
Kyma Envoy sidecar Access Log

### ISSUE THREAD

**Issue by MTAttic** [kyma-project/kyma#14277]
Hey! 

I have deployed a nginx image on my kyma instance. A sidecar was automatically injected so my pod consists of a nginx and a istio-proxy container. My goal is to log the traffic with the envoy proxy so that I can see what requests were send to the nginx from the user. Unfortunately I cannot find any logs from that envoy sidecar in my Loki dashboard and when I open the logs from the istio-proxy container directly I only get this entry: 

`2022-05-12T07:33:09.438931Z warning envoy config Double registration for type: 'envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication' by 'envoy.filters.http.jwt_authn' and 'io.solo.filters.http.solo_jwt_authn'`

I am aware of the fact that nginx also provide logs with the data but I want to use the envoy logs. Am I missing something there?

**Comment by a-thaler** [comment]
Hi @MTAttic ,
you either can enable and configure access log at installation time via the istio config (including access log format), see https://github.com/kyma-project/kyma/blob/4c1cd65aadda28c1932fa3a86c7b6052e5a32b20/resources/istio/values.yaml#L40, or you can enable access logs dynamically at runtime per pod/namespace, see https://kyma-project.io/docs/kyma/latest/04-operation-guides/operations/obsv-01-access-logs/ With the dynamic approach you cannot configure the format yet.

About the specific log message you pasted, most probably that will be fixed with the switch back from solo images with https://github.com/kyma-project/kyma/issues/13618, maybe @strekm can confirm.

I assume the request is answered and I will close the ticket, feel free to re-open if you doubt that.
