### ISSUE TITLE
document the testing situation in eventing

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#14343]
For the components `eventing-controller` and `event-publisher-proxy`, in the `README.md` add a section about testing that does:

Give an overview of all the tests that exist for this component.
1. is a test automatic or manual
2. are they mandatory
3. where to find the files for any given tests
4. pre, post, periodic
5. is this test currently flaky

tests|automatic|files|pre|post|periodic|stable
--|--|--|--|--|--|--
main-kyma-skr-eventing|yes|[here]()|[yes](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-skr-eventing)|yes|no|[flaky](https://github.com/kyma-project/kyma/issues/13976)

Further:
how to add a test of a certain kind in very simple way that points to the right documentation, eg:
> to add a type x test please do something (see [how to do something]())

Bonus points for [diagrams](https://mermaid-js.github.io/mermaid/#/) that explains how test are organized, how/ by what image/ pipeline/ is getting executed. 

Make it mandatory to update this section whenever the test are touched.

**Comment by nachtmaar** [comment]
@FriedrichWilken We have a similar list to what you are proposing: https://github.com/kyma-project/test-infra/blob/main/test-inventory-integration.md
It is also auto-generated.
@mfaizanse and me like the idea of the `pre`,`post`,`periodic` columns. They would be nice to use then you quickly want to check if a specific job is flaky or not.
What about the `stable` column ? What do we do if there are multiple issues ? Also this field cannot be auto-generated ?

**Comment by nachtmaar** [comment]
@mfaizanse and me had another idea. We **don't care** about the **test names** (e.g. skr-azure-nightly) because they are **not telling us what the test is actually testing**. Instead we **are interested** in the **name of the fast integration test** (e.g. [skr-test](https://github.com/kyma-project/kyma/tree/main/tests/fast-integration/skr-test) or [eventing-test](https://github.com/kyma-project/kyma/tree/main/tests/fast-integration/eventing-test))

**Each teams knows** for **which fast integration** test they are **responsible**. But with the **many flavours of prow jobs** it can be very hard to keep an overview. Therefore we think adding the fast integration test names could make sense.

**Comment by nachtmaar** [comment]
@FriedrichWilken I think the dashboard where @kyma-project/pandas are working on might be even more helpful. From where you can see in which pipelines a `feature` was tested or failed.

> I want to look up in this proposed chart the name of the failing test to see, if there are known issues or if I need to create a new issue.
In case we will use the dashboard, we could link the known issues to the dashboard.
Having a central place to lookup the pipelines, features and known issues would be amazing ❤️

**Comment by friedrichwilken** [comment]
I think for now I will leave this as closed.
