### ISSUE TITLE
Commerce-Mock-/Helm-Fixture not ready +  kubeClient failed to update AuthorizationPolicy/Gateway/DestinationPolicy

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#14538]
**Description**
The following pipelines are failing due to several reasons:
- [kyma-upgrade-gardener-kyma2-to-main-reconciler-main](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma2-to-main-reconciler-main)
- [kyma-upgrade-gardener-kyma2-minor-versions](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma2-minor-versions)

The main reasons, which are appearing since a couple of days multiple times in different  executions:
- Commerce-Mock-Fixture is not ready
- Helm Fixture is not ready
- kubeClient failed to update AuthorizationPolicy/ Gateway/ DestinationPolicy/ ...

**Comment by varbanv** [comment]
[kyma-upgrade-gardener-kyma2-minor-versions](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma2-minor-versions) has been green for the past 2 days.
[kyma-upgrade-gardener-kyma2-to-main-reconciler-main](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma2-to-main-reconciler-main) is failing due to different errors and will be handled as part of https://github.com/kyma-project/kyma/issues/14697
