### ISSUE TITLE
Migration from serverless.kyma-project.io/v1alpha1 to serverless.kyma-project.io/v1alpha2

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#14593]
**Description**

As part of https://github.com/kyma-project/kyma/issues/13828 we plan to implement a migration of customers' functions from serverless.kyma-project.io/v1alpha1 to serverless.kyma-project.io/v1
We assume that there is only one valid function CR version per kyma version.

 - Document the migration steps (for Kyma OSS users)
 - Migrate customer's function automatically via reconciler
 - Cleanup GitRepo CRs

**Reason**
Releasing of stable Function CRD version

**Comment by moelsayed** [comment]
a quick update on the status of the conversion webhook task:
I restored the v1alpha1 types
I added the required gen comments to be able to regenerate the crd with both versions
I implemented a webhook and 95% of the conversion code.

The controller-runtime uses a very simple hub-spoke pattern to implement version conversion. You just implement a couple of interfaces with your types and write the conversion code. The problem with this is that it's very rigid and abstracted. Our conversion code actually needs to "merge" two CRDs (function and the gitrepo) into one. It's not possible to do that with the hub-spoke pattern (at least I couldn't do it).

I went in another direction and tried to implement the webhook server from scratch. At this point, everything seems to be working, but the API (kubernetes API!) is sending an incorrect request. Instead of getting a conversionReview request from the API, I am getting a AdmissionRewiew request .. I am still trying to figure out why. I think it's a configuration issue, but can't figure out where exactly..

for now, the changes are all here: https://github.com/m00g3n/kyma/compare/fn-crd-refactor...moelsayed:migration_wip2?expand=1 . This is just experimental code, please excuse the quality.
I will have some time today, so I might keep trying to get it working. If not, I will be available on slack to answer any questions, please do feel free to ping me at any time. If I am not on a plane, I will respond :D

**Comment by kwiatekus** [comment]
Leftovers
 - [ ] Inject CA bundle cert into converting webhook definition @Cortey 
 - [ ] Implement conversion from `v1alpha1` into `v1` @pPrecel @anoipm

**Comment by anoipm** [comment]
State for now.

Newest sources: 
https://github.com/m00g3n/kyma/tree/fn-crd-refactor-tests

TODO in webhook:
- [ ] function controller doesn't create services after conversion,
- [ ] "apply function" says the function name does not match,
- [ ] in the logs of pod we can see infinite attempts to convert v1alpha2->v1alpha1,
- [ ] conversion v1alpha1->v1alpha2 don't fill default values (e.g. resources),
- [ ] conversion v1alpha1->v1alpha2 create empty values (probably we should use "ommit empty").

TODO outside webhook:
- [ ] adapting CLI,
- [ ] adapting Busola.

**Comment by kwiatekus** [comment]
We don't support the downgrade scenario like that:

> If a user creates v1 version via kubectl (all information combined in function cr) and then reads it using old client, we dont need to recreate git repo cr to contain the git  information.

We need to deprecate Git Repo CRD  and Function v1alpha1 CRD

We need to maintain the git  information in Function v1 whenever user edits git data in the deprecated GitRepo CR   (i.e via webhook)
