### ISSUE TITLE
Custom namespaces and workloads are not presented in Istio Workload Dashboard

### ISSUE THREAD

**Issue by dariusztutaj** [kyma-project/kyma#14751]
**Description**

Custom namespaces and workloads are not presented in Istio Workload Dashboard.

**Expected result**

Custom namespaces and workloads are visible in dashboard. Workload is properly monitored.
Like in Kyma-system namespace:
![Zrzut ekranu 2022-07-5 o 14 39 33](https://user-images.githubusercontent.com/89071551/177331457-7caa3453-d068-4fb0-bde2-c0f313247c17.png)

**Actual result**

Custom namespace and workload are displayed as _unknown_. Metrics are not presented.
![Zrzut ekranu 2022-07-5 o 14 38 15](https://user-images.githubusercontent.com/89071551/177331508-485f8a73-1f04-4b51-9efb-a2ced3fef758.png)

![Zrzut ekranu 2022-07-5 o 14 38 02](https://user-images.githubusercontent.com/89071551/177331542-5201776f-bddd-4f60-97a8-d959ef335453.png)

**Comment by a-thaler** [comment]
The available namespaces are getting determined by the query: `sum(istio_requests_total) by (destination_workload_namespace)`, so it lists only namespaces having workload with actual traffic (as otherwise the charts would be empty anyway).

I created a function in a namespace "test". After I called the function via an apirule, the namespace popped up in the selector:
<img width="507" alt="Screenshot 2022-07-06 at 11 34 27" src="https://user-images.githubusercontent.com/7479371/177520327-09c7f8e2-6fcd-4b3a-bab6-6c3dbd6b6898.png">

So this is not a bug but a feature and I would recommend to close it as invalid

**Comment by dariusztutaj** [comment]
Thanks for clarification. Closing as invalid
