### ISSUE TITLE
[Telemetry Operator] Improved secret rotation concept

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14793]
**Description**
At the moment, a change in a referenced secret will be detected in a 1h loop only. So when a secret value is rotated, it can take up to 1 hour till the rotation is reflected. Having a TTL for the old secret lower than one hour will be a problem. Also, the user experience is not smooth when modifying a secret manually.

**Criteria**
- Come up with a technical solution on how: A change in a secret will be detected and applied in a time span comparable to other resource changes, like editing a LogPipeline directly.
- Adjust documentation by mainly removing documented workaround
- Have tests in place

**Reasons**
- User Experience:  After secret change, simply nothing happens for a long time, the user will not know if there was a user mistake.
- TTL risk: Avoid running without valid secret in case of too low secret TTL configuration.

**Attachments**

**Potential solutions**
- Watch all secrets having BTP operator labels attached.
- Add custom labels to referenced secrets (and cleanup at de-referencing) and watch them.

**Comment by skhalash** [comment]
## Summary

The operator maintains an in-memory cache of all the secrets that are referenced by all watched log pipelines (except the ones marked for deletion). Whenever a log pipeline is reconciled, its referenced secrets are added to the cache. Additionally, the operator is watching all the secrets in the cluster. If any secret is updated and it's in the cache, a reconciliation request is created for every log pipeline that is referencing it.

The following setup has been tested with a cluster that contains 5000 secrets, which are continuously updated by 200 parallel workers, and a single log pipeline. It means that most of the time the secret watch handler will return early due to a cache miss. Such a test does not put a lot pressure on the operator. One can see a very slight CPU usage increase, memory usage does not increase.

**Comment by a-thaler** [comment]
Please remove the unnecessary workaround from the documentation.
Also link the ticket for further improvement of the implementation by using the cache of the indexer

**Comment by skhalash** [comment]
Here is the follow-up improvement issue: https://github.com/kyma-project/kyma/issues/15675
