### ISSUE TITLE
Service endpoint with secured API does not accept authorisation bearer token

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#1518]
**Description**

Hi,
During working with the examples from [examples repo](https://github.com/kyma-project/examples/tree/master/gateway) I have encountered a problem with the secured API endpoint. I was able to create the rule and retrieve a token, however I was not able to authenticate using it and the following curl command:

```bash
curl -ik https://hellos.kyma.local -H 'Authorization: Bearer FOO'
```

**Expected result**

I should be granted access to my application as documented in the example

**Actual result**

The command returns:

```
HTTP/2 401
content-length: 29
content-type: text/plain
date: Mon, 05 Nov 2018 10:06:02 GMT
server: envoy
x-envoy-upstream-service-time: 0

Origin authentication failed
```

**Steps to reproduce**

Following the instruction with the service deployment.yaml
During the instruction I have noticed that there was no information regarding if we should delete the previous (unsecured) endpoint before creating the second (secured) one. So for some time I have had 2 endpoints for a single service. 

**Troubleshooting**

* I have checked the envoy logs, but there was nothing in the term of errors or warnings.
* I have tried to open the console in incognito mode and on several tabs. Each one produced a different token, however I was unable to access the application with either.
* I have tried to restart the application pod, the behaviour was the same.

**Comment by kubadz** [comment]
The problem here is that we allow the creation of multiple APIs bound to the same service. For secured APIs the Api-controller creates a pair of Istio Resources - VirtualService and Policy. For unsecured it is only the VirtualService. The Policy is bound to the specific service, so if you expose the unsecured API after exposing the secured API, the unsecured endpoint will be also secured.

**Comment by piotrmsc** [comment]
We should check if an API already exists for a given service, if yes then do not create new istio resources but put an error in the API CR status which should describe already existing api for given service.

**Comment by mpern** [comment]
I have the same issue, but I don't even exposed the API unauthorized before.

I've exposed the API using the web console, using the provided default values

Kyma 0.6.1

```
- apiVersion: gateway.kyma-project.io/v1alpha2
  kind: Api
  metadata:
    clusterName: ""
    creationTimestamp: "2019-01-16T10:27:18Z"
    generation: 1
    name: hello
    namespace: production
    resourceVersion: "24660"
    selfLink: /apis/gateway.kyma-project.io/v1alpha2/namespaces/production/apis/hello
    uid: 4d3ea489-1979-11e9-8f2e-0eb0617eb7c9
  spec:
    authentication:
    - jwt:
        issuer: https://dex.kyma.local
        jwksUri: https://dex.kyma.local/keys
      type: JWT
    hostname: hello.kyma.local
    service:
      name: hello
      port: 8080
  status:
    authenticationStatus:
      code: 2
      resource:
        name: hello
        uid: 4d7f21c2-1979-11e9-8f2e-0eb0617eb7c9
        version: "24659"
    virtualServiceStatus:
      code: 2
      resource:
        name: hello
        uid: 4d7e68b4-1979-11e9-8f2e-0eb0617eb7c9
        version: "24658"
```

**Comment by kubadz** [comment]
@mpern In your case the issue is different. Your problem is a wrong jwksUri. For local Kyma instances (on minikube) that URI is not resolvable, as the component responsible for fetching the public keys for token verification can't use host DNS (that dex URI is exposed on the host localhost). You should use in-cluster FQDN of dex service instead. [this example](https://github.com/kyma-project/examples/blob/master/gateway/service/api-with-auth.yaml) shows how to do that. You can also use default authentication settings for your environment by simply using `authenticationEnabled: true` like in [this example](https://github.com/kyma-project/examples/blob/master/gateway/service/api-with-default-auth.yaml). Api-controller sets that default value depending on which environment it is installed (cluster or local installation).

**Comment by piotrmsc** [comment]
Acceptance criteria:
- api-controller validates if an API already exists for given **k8s** service
- if an api already exists for given service, error is set on new api status object mentioning that api already exists for given service. Do not process further such API
- documentation describes this behaviour (remember about crd docu)

**Comment by piotrmsc** [comment]
@jakkab  Review comment: please create a follow up task for extending validationStatus with code and description of an error.
