### ISSUE TITLE
Migrate deprecated PodSecurity Policy to PodSecurity Admission in serverless charts

### ISSUE THREAD

**Issue by grego952** [kyma-project/kyma#15245]
**Description**

Deprecated PSP is used in serverless charts and mentioned in documentation

 - [x] Investigate the required security standard levels for functions (as customer workloads in their namespaces)
 - [x] Investigate the required security standard levels for serverless workloads in kyma system namespace
 - [x] Remove PSPs `severless-build` and `serverless-function` and their service accounts and roles - https://github.com/kyma-project/kyma/issues/15921
 - [x] Apply security context for `baseline` level to the function build job and runtime pod - https://github.com/kyma-project/kyma/issues/15923
 - [x] Apply `restricted` security context in serverless charts for serverless controller and webhook - https://github.com/kyma-project/kyma/pull/16104
 - [x] Update documentation:
    - [x] update [Security considerations](https://kyma-project.io/docs/kyma/main/01-overview/main-areas/serverless/svls-06-security-considerations) document 
    - [x] document maximum restriction level ( applied on namespace ) that allows to run and build functions
    
    
**Reasons**
 PodSecurity Policy were deprecated in kubernetes 1.21 and will be removed in 1.25

**Attachments**
[migration guide](https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/)

**Comment by kwiatekus** [comment]
@dbadura pls document the findings about removing PSP in serverless charts

**Comment by dbadura** [comment]
I removed PSP for function pod and add PSA label: `pod-security.kubernetes.io/warn: restricted`. It worked.

**Comment by kwiatekus** [comment]
@dbadura should'nt we use enforce mode to really test the PSP removal ?
`pod-security.kubernetes.io/enforce: restricted`
https://kubernetes.io/docs/concepts/security/pod-security-admission/

**Comment by kwiatekus** [comment]
We need to find out if build jobs can run with baseline- level  PSA enforced

**Comment by kwiatekus** [comment]
With PSA the restrictions are enforced on namespace level. Its fundamentally different usability concept comparing to PSPs.
If we need to enforce restrictions for function-managed workloads ( runtime pod and build job ) we'd need to control PSA labels in user namespaces as function workloads dont live in kyma-system.

My standpoint is that it's up to the user where ( in which namespaces ) the PSAs are enforced.

@pPrecel Lets check if function would build and run in a namespace with `restricted` or `baseline` level enforced in the namespace. Depending on the result we may need to look into defining exemptions for serverless

**Comment by pPrecel** [comment]
Output from my little investigation:

Functions would build and run in namespaces with the `baseline` level but NOT with the `restricted` one. I've created functions in the specified namespace and then I labeled this namespace with the `restricted` label then I got the following warnings:

```
kubectl label namespace psa-poc pod-security.kubernetes.io/enforce=restricted --overwrite

Warning: existing pods in namespace "psa-poc" violate the new PodSecurity enforce level "restricted:latest"
Warning: nodejs12-65gs2-7db9bcf7cd-hpvfq (and 3 other pods): seccompProfile
Warning: nodejs12-build-d6ms4-t8lph (and 3 other pods): allowPrivilegeEscalation != false, unrestricted capabilities, runAsNonRoot != true, runAsUser=0, seccompProfile
namespace/psa-poc labeled
```

What about serverless components in the `kyma-system` namespace you would ask. Almost perfect :D Most of our components would work even with the `restricted` level. problem is with the DaemonSet installing docker-registry certs on every node and I can't see a possibility to reduce his privileges. Warning that I've got (restricted lvl):

```
Warning: serverless-docker-registry-self-signed-cert-zmsfd: hostPath volumes, unrestricted capabilities, restricted volume types, runAsNonRoot != true, runAsUser=0, seccompProfile
```

with the `baseline` level it looks a little bit more acceptable:

```
Warning: serverless-docker-registry-self-signed-cert-87gv6: hostPath volumes
```

Summary: I think regarding functions we should document that functions would work only in namespaces without the `restricted` PSA level and everything should be ok. The problem is with the DaemonSet and we should investigate how to avoid problems with this element.
