### ISSUE TITLE
Exposing App Connector command in docs says 'error upgrading connection'

### ISSUE THREAD

**Issue by atakanyenel** [kyma-project/kyma#1537]
**Description**

I'm using the command ( `kubectl -n=kyma-integration port-forward svc/connector-service-internal-api 8080:8080`) in the docs to expose application connector so that I can get a token by sending a curl. [application connector docs](https://kyma-project.io/docs/components/application-connector)

That command used to work , then I made a fresh install of Kyma and now this command says `error: error upgrading connection:`. 

**Expected result**

I expected this command to port forward localhost request to application connector. 
**Actual result**

this command says `error: error upgrading connection:`. 
**Steps to reproduce**

- Have a fresh installation of Kyma
- Run the command `kubectl -n=kyma-integration port-forward svc/connector-service-internal-api 8080:8080`
**Troubleshooting**

I believe the problem is with the **docs** and not with the application connector itself. Maybe the name of the pod has changed during development. When I get the token through the UI, it works as expected.

**Comment by lszymik** [comment]
Hello @atakanyenel ,

That is an error related to the Application Connector or its documentation.

The issue is that you are using the wrong kubeconfig file. The kubeconfig from the Console UI is not having a proper right to the port-forward functionality.

There are undergoing efforts to get rid of the port-forward in the whole Kyma. Please check that https://github.com/kyma-project/kyma/issues/1152 regarding improvements in the Application Connector.

Cheers
Lukasz
