### ISSUE TITLE
SSL Authorty certificate not accepted NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by hokandil** [kyma-project/kyma#15697]
I am trying to install Kyma locally on my windows 10 machine with docker desktop (WSL2 is disabled)
I run the command 
`Kyma provision k3s` 
`kyma deploy`
`kuma dashboard`

the dashboard opens fine as localhost:3001 , but when I navigate to kiali , jaeger or grafana . it gives an error related to the ssl certificate.
![error](https://user-images.githubusercontent.com/28161747/193465379-10475955-f28d-4725-a2eb-349ceaa46941.PNG)
I tried to provide custom certificate during the deployment after generating it using openssl but unfortunately the certificate never change.
`kyma deploy  --tls-crt tls.csr --tls-key tls.key`
the same issue are happening with any api rule I add to kyma . ssl is not accepted.

**Comment by a-thaler** [comment]
The certificates bundled with the local installation are self-signed and need to be installed into your local trust storage so that the browser can validate them. For that you can call `kyma import certs`, see also https://github.com/kyma-project/cli/blob/main/docs/gen-docs/kyma_import_certs.md.

Setting custom certificates for the installation should work as described. @clebs is it mandatory to also set the domain to get it active as described here? https://kyma-project.io/docs/kyma/latest/04-operation-guides/operations/02-install-kyma/#install-with-custom-domain

Be aware of that kiali/jaeger/grafana are not exposed by default, see also https://kyma-project.io/docs/kyma/latest/04-operation-guides/security/sec-06-access-expose-kiali-grafana/

**Comment by clebs** [comment]
Hi,
As far as I know, the domain flag should only be necessary if the domain on the custom certificate differs from the default domain.

**Comment by hokandil** [comment]
Thank you @a-thaler., after running the `kyma import certs` command as administrator , now I can access the API rule . but only if no authorizationis configured in the AOI rule , but once I enable authorization on the API rule I face issues again with SSL and get this error :
` upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`

**Comment by a-thaler** [comment]
Hi @hokandil,
sorry for the late response. So to summarize. You have a local installation using a custom certificate using `foo.localhost` domain. You imported the cert to your local trust storage. Now you created an APIRule to expose a service. That exposed service you can call using https via your browser. When adding authorization to the APIRule, then the https call is not working anymore because of a certificate validation problem.
What kind of authorization you added? @strekm do you have an idea what could be wrong?

**Comment by werdes72** [comment]
We are still waiting for a response, but in the meantime I have checked everything with the latest Kyma from main branch.
By default we do not expose Grafana, you can access it through port-forward or expose it using oauth2proxy:
https://kyma-project.io/docs/kyma/latest/04-operation-guides/security/sec-06-access-expose-grafana

For Kiali and Jaeger, see the following examples:
https://github.com/kyma-project/examples/tree/main/kiali
https://github.com/kyma-project/examples/tree/main/jaeger

Let us know if you need further help and if the issue still persists.

**Comment by hokandil** [comment]
Thank you for the update, the issue with ssl is resolved after importing the ssl using the command
`kyma import certs`
Regarding the kali , I am using port forwarding as of now.
