### ISSUE TITLE
Remove PSP and set security context for istio, ory and api-gateway components

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#15916]
**Description**

Since PSP will be removed with k83 1.25 remove it from following kyma components:
- istio -> S -> @dariusztutaj 
- ory -> M -> @barchw 
- api-gateway -> XS -> @triffer 

Make sure proper security context is applied for pods in mentioned components.

**Reasons**

Applying POD Security Standards

**Attachments**

https://github.com/kyma-project/kyma/issues/15897

**Comment by dariusztutaj** [comment]
ecause of using Istio CNI plugin, it's not needed to change anything. Istio is already compliant.
The CNI handling the netns setup replaces the current Istio approach using a NET_ADMIN privileged initContainers container, istio-init, injected in the pods along with istio-proxy sidecars. This removes the need for a privileged, NET_ADMIN container in the Istio users' application pods. https://github.com/istio/istio/tree/master/cni

**Comment by dariusztutaj** [comment]
Installing Istio with CNI plugin deploys _istio-cni-node_ DaemonSet.  Install container, which is part of this daemonset, requires to be run with aid and gid 0, because of using host path directories.
**Related links**:
https://istio.io/latest/docs/setup/additional-setup/cni/#install-istio-with-cni-plugin
https://github.com/istio/istio/issues/35902
