### ISSUE TITLE
Make EC Unit Test Job Stable

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma#15937]
**Description**

Make the `pull-eventing-controller-unit-test` job stable. It is very flaky and failing with different errors. It is making a developer life a bit difficult as one needs to restart the job multiple times until it is green.

**Actual result**

Please see the [job history](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pull-eventing-controller-unit-test)

Steps:
- Investigate why it is failing
- Make it stable
  -  Maybe just increase kcp start timeout `KUBEBUILDER_CONTROLPLANE_START_TIMEOUT`
  -  Fix the test coding issues according the job history failures

Acceptance criteria:

- [ ] Stable `pull-eventing-controller-unit-test` job

**Comment by VladislavPaskar** [comment]
this [PR](https://github.com/kyma-project/kyma/pull/16008) introduced a fix for the failing jobs with the [following problem ](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/15681/pull-eventing-controller-unit-test/1588469215126360064), this [PR](https://github.com/kyma-project/test-infra/pull/6336) should fix the PRs with the kubebuilder timeout. 

There is still a problem like [this](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/16008/k15r_test_of_prowjob_pull-eventing-controller-unit-test/1588522498519994368), which should be resolved with by implementing this [PoC](https://github.com/kyma-project/kyma/issues/15925). So, let's keep this issue closed and observe if the fixes really helped. Otherwise we can reopen it.
