### ISSUE TITLE
`application-connector` context deadline exceeded while reconciling

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#16454]
**Description**

The following pipelines are failing due to the `application-connector` component:

- [pre-main-control-plane-reconciler-e2e-latest-release](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release)
- [pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener)

```
{"level":"DEBUG","time":"2022-12-29T01:24:11.247Z","message":"Bookkeeper evaluated reconciliation (schedulingID:6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5--8fc6f2e0-d294-4e18-9dac-608440660a5e) for cluster '6f8ec1bc-f300-4f00-bb65-6fec5dcd0ba5' to cluster status 'error': Done=logging[3],certificates[2],istio[2],istio-resources[3],monitoring[3],CRDs[1],cluster-essentials[2],cluster-users[3],api-gateway[3],tracing[3],ory[3],eventing[3],serverless[3],kiali[3],telemetry[3] / Error=application-connector[3][error: context deadline exceeded] / New= / Running="}
```

**Comment by akgalwas** [comment]
Findings:
- The pipelines install release **2.9.3**
- It started to fail after merging [this commit](https://github.com/kyma-project/control-plane/commit/11df642c6d41a5de7735c692c103173aaf66b026) to the Control Plane

The commit changed the namespace where Application Connector is installed from `kyma-integration` to `kyma-system`. I'm working to confirm the behaviour with `kyma-cli`, but me impression is that it shouldn't be a release blocker.

**Comment by akgalwas** [comment]
It seems that reverting the change from [this commit](https://github.com/kyma-project/control-plane/commit/11df642c6d41a5de7735c692c103173aaf66b026) solved the problem with Kyma reconciliation. Log for `pre-main-control-plane-reconciler-e2e-latest-release pipeline after` revert is [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2382/pre-main-control-plane-reconciler-e2e-latest-release/1612702855049777152/build-log.txt). Log for `pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener` is [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2367/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1612434306355957760/build-log.txt).

**Comment by akgalwas** [comment]
I still suspect some specific configuration in the pipeline. I was not able to reproduce the problem with kyma cli. I also tried to execute the bash scripts from the pipeline and Kyma reconciled correctly.

**Comment by akgalwas** [comment]
The problem with pipelines is caused by [this commit](https://github.com/kyma-project/control-plane/commit/11df642c6d41a5de7735c692c103173aaf66b026). Application Connector in Kyma 2.9.3 creates `LimitRange` object in `kyma-integration` namespace. Since the configuration of the Reconciler e2e test was changed to install Application Connector to `kyma-system` and `kyma-integration` doesn't exist it is not possible to apply 'LimitRange' object.

**Comment by akgalwas** [comment]
This [PR](https://github.com/kyma-project/control-plane/pull/2382) solved the problem with Application Connector but revealed another issue with the pipelines. 
```
  1) Executing Standard Testsuite:
       Tracing Tests:
         with Nats backend
           in-cluster structured event should have correct tracing spans:
     TypeError: Cannot read property 'spanID' of undefined
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/utils/index.js:1749:74 
```
As @rakesh-garimella suggested this is directly caused by the fact, that the pipelines run test from `main` on Kyma `2.9.3`. There were some changes to `fast-integration` tests recently that caused this incompatibility. The most bullet-proof solution to this problem is to make sure that the pipelines use integration test from the same version as installed Kyma release.

**Comment by jeremyharisch** [comment]
FIx is prepared: https://github.com/kyma-project/test-infra/pull/6726

But pjtester is not able to test it. I am waiting for some support from the neighbours

**Comment by jeremyharisch** [comment]
All pipelines are fixed, closing this issue
