### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by cloudcompute** [kyma-project/kyma#16498]
a. Does Kyma support Event-Sourcing/CQRS out-of-the-box.. Is there any demo application that demonstrates it? If not, could we use the built-in NATS JetStream for event sourcing?

b. Is it possible to write functions and microservices using other languages like NodeJs, Kotlin?

c. Does Kyma use Knative Serving for implementing serverless or does it have its own solution?

d. Is Kyma mainly for extending the existing applications or can we use it to write cloud-native business apps from scratch?

e. The request would flow like this?

Request ---> Caddy HTTP server (load balancing would take place here) ---> Kubernetes Ingress ----> Kyma Cluster  ---> Serverless function within the cluster

f. Where can we deploy our Serverless Kubernetes cluster so that we need to pay only for the resources we consume, does SAP has any such managed service?

Thanks

**Comment by abbi-gaurav** [comment]
Hi Cloudcompute,
Please find some details below.

- Does Kyma support Event-Sourcing/CQRS out-of-the-box? Is there any demo application that demonstrates it? If not, could we use the built-in NATS JetStream for event sourcing?
  - Kyma supports an eventing infrastructure where events are published and consumed via HTTP. AMQP is next on line #13154. If you want to incorporate event sourcing, you can build on top of it.

- Is it possible to write functions and microservices using other languages like NodeJs, Kotlin?
  - Microservices : you can use any technology of your choice. You just need to dockerize your application
  - Functions: Currently Python and NodeJs are supported, Java support is planned (#14357). 

- Does Kyma use Knative Serving for implementing serverless or does it have its own solution?
  - It has its own solution 

- Is Kyma mainly for extending the existing applications or can we use it to write cloud-native business apps from scratch?
  - Both can be achieved. SAP Managed Kyma runtime supports extending SAP Solutions as well as building applications from scratch. [SAP Blog](https://blogs.sap.com/2020/05/12/get-a-fully-managed-runtime-based-on-kyma-and-kubernetes/)

- The request would flow like this?

  - Request ---> Caddy HTTP server (load balancing would take place here) ---> Kubernetes Ingress ----> Kyma Cluster ---> Serverless function within the cluster
  - Kyma offers Istio and APIRules that does not require user to deploy its own ingress. Please refer to these set of [tutorials](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/)
- Where can we deploy our Serverless Kubernetes cluster so that we need to pay only for the resources we consume, does SAP has any such managed service?
  - This [SAP Blog](https://blogs.sap.com/2020/05/12/get-a-fully-managed-runtime-based-on-kyma-and-kubernetes/)
  - Please notice, SAP managed Kyma comes with a minimal capacity and cluster autoscaling. Please refer to this [estimator](https://estimator-don4txf2p3.dispatcher.ap1.hana.ondemand.com/index.html)
  - You can have your microservices and functions configured with elastic scaling using Kubernetes semantics such as horizontal pod auto-scaling

**Comment by k15r** [comment]
@cloudcompute 
> ... If not, could we use the built-in NATS JetStream for event sourcing?
You can use the installed JetStream Cluster for your purposes. Only the configured stream named `sap` cannot be used by you directly without using kyma eventing.

**Comment by cloudcompute** [comment]
Thanks for the detailed answer @abbi-gaurav and @k15r 

Can we deploy our application on other platforms like AWS, Azure. I am asking this because a customer might be interested to switch the deployment to some other platform because of vendor-lock in.

Any plans to switch to Knative Serving because it is quickly becoming a defacto standard.

I will read the blogs/articles (whose links are) shared by you.  Thanks once again.
