### ISSUE TITLE
Revisit Eventing manual release testing flow

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#16650]
We are spending so much time in doing the manual release testing. We should revisit the sequence of tests we perform to optimised the flow. 

We should define a sequence of tests and steps we should perform for the release-testing. Also, we some later point we can automate these steps.

**Comment by raypinto** [comment]
Also its important to note that, the oss cluster automatically provisioned by the bot does not allow eventmesh to communicate with this cluster (the error is as shown in the image below). We should make the release manager aware of this so that an oss cluster is provisioned for us or the root cause for this is determined and are able to use the cluster with the fix)

![Screenshot 2023-01-23 at 14 29 19](https://user-images.githubusercontent.com/45314732/214263588-d7e3404b-4a7e-4ca3-896c-f1d0f4d3df7b.png)
