### ISSUE TITLE
ServiceBindingUsage doesn't work

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#1676]
**Description**

When ServiceBindingUsage created nothing happen, credentials are not injected. ServiceBindingUsage controller logs show that informers for CSC and SC are failing. I've seen that ServiceCatalog apiserver and controller were restarted in the past, but work as expected. See logs.

**Expected result**

SBU works.

**Actual result**

SBU doesn't work.

**Steps to reproduce**
Restart ServiceCatalog apiserver and  CSC and SC will disappear.

**Troubleshooting**
SBU controller restart solves

**Comment by PK85** [comment]
[buc-cannot-start-sc-was-restarted.txt](https://github.com/kyma-project/kyma/files/2584159/buc-cannot-start-sc-was-restarted.txt)

**Comment by jasiu001** [comment]
**Recap**
I tried reproduce the issue but neither locally neither on azure cluster I could not achieve state from description. 

**Steps to try reproduce on minikube**
- I reset Service Catalog for some period of time 1m, 5m, after starting everything was working fine
- I reset Service Catalog for more than 10m (max idle time 30m), sometimes after starting BindingServiceController could not fetch BindingUsage from cache during 15 attempts, which is default max retires for controller. Information about that wasn't shown in status message of ServiceBindingUsage, I updated it in PR #1761. This issue is not connected with bug description.

**Steps on azure cluster**
- I created 5 instances of redis and 4 lambda functions, I made ServiceBindingUsage between them
- I reset Service catalog for more than one hour, after starting I could create new ServiceBindingUsages and old connections worked correct.
