### ISSUE TITLE
Improve logs of central-application-gateway

### ISSUE THREAD

**Issue by Disper** [kyma-project/kyma#17265]
**Description**

@ebensom pointed out that logs in `central-application-gateway` should be improved. 

Acceptance criteria:
- [x] Distinguish return codes returned from the target API and those returned by Application Gateway (is this 5xx mine or not) 
- [x] Consider adding possibility to define multiple log levels. 
- [x] Consider using tools for logging in a structured way (kyma/common) 
- [x] Consider ability to change log level without component restart (there is a solution in function controller)
- [ ] Consider using tracing to observe how the request is modified 

**Reasons**

Better logs will make it easier to find issues faster.

**Comment by Disper** [comment]
See additional suggestions https://github.tools.sap/kyma/backlog/issues/3801#issuecomment-3219811

**Comment by akgalwas** [comment]
In the first step we must ensure that:
- it is possible to distinguish whether the error code was returned by the target API or the Application Gateway (please ind [this comment](https://github.com/kyma-project/kyma/issues/17265#issuecomment-1630627600))
- for 5xx errors Application Gateway should return 502 so that SLA calculation for Application Gateway doesn't include errors returned by the target API
