### ISSUE TITLE
Monitoring of console component

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#1767]
**Description**

Monitor 
 - (requests) rate
 - (requests) error rate
 - (requests) duration
of the console in graphana

AC:
 - User can see the graphs (peak values) for request rate, error rate, request duration in the graphana UI

See the monitoring being applied for lambda ui:
https://github.com/kyma-project/kyma/pull/3100/files

**References**
https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/

**Comment by kwiatekus** [comment]
Some resources found on the internet:
https://grafana.com/dashboards/49

**Comment by y-kkamil** [comment]
talked with @a-thaler . it would be beneficial to wait for the kyma-wide solution for monitoring ui components.

**Comment by jesusreal** [comment]
This task is not blocked anymore. Pull request ([here](https://github.com/kyma-project/kyma/pull/3100/files)) for [blocking task](https://github.com/kyma-project/console/issues/343) has been merged.

**Comment by jesusreal** [comment]
This is how the dashboard looks like after implementation:
![Screenshot 2019-04-01 at 18.48.27.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/48a7c9bb-65c0-4af4-a66d-1dacb32dbe80)

*How to test it:*
Instructions on pr: https://github.com/kyma-project/kyma/pull/3496

*Notes:*
Alert rules aren´t currently automatically applied to every new webapp. Instead of added console core to the existing hardcoded list, @rakesh-garimella will implement that in scope of this issue: https://github.com/kyma-project/kyma/issues/3071. After that, rules will be automatically applied to console core.
