### ISSUE TITLE
how to install Kyma in local k3s cluster not inside k3d?

### ISSUE THREAD

**Issue by ay4m** [kyma-project/kyma#18067]
**Description**

I apologize if this issue is a duplicate but I could not find anything as there are ~18000 closed issues.

I'm just getting started with Kyma on k3d, and I was wondering how to install all the kyma components without using k3d? I want to install it on just K3S without the K3D wrapper. Is there an easy way that the cli provides? 

If there is no option in the cli, how would I proceed? By helm installing the crds and the components?

**Expected result**

I've setup my dev environment using k3d, and for production I want to migrate to just k3s. But I want the environment to match exactly between dev and prod. So I wish to know how to install the kyma runtime on k3s (without using k3d) in a way that exactly matches the environment in k3d.

Tried refactoring the install-kyma.sh from [this repo](https://github.com/kyma-incubator/local-kyma), but the code has changed so much, and I don't have much experience in golang, helm and kubernetes to fully understand all the stuff in this repo.

**Comment by ruanxin** [comment]
Hi @ay4m,

kyma cli can work with any k8s clusters, what you need is just provide the kubeconfig profile so that cli can access your cluster, for example, by providing it as an environment variable, then you can use `kyma deploy` command to deploy kyma.

Example:
```
export KUBECONFIG=[your kubeconfig yaml]
kyma deploy
```
you can use `kyma deploy -h` for more detailed help.
