### ISSUE TITLE
Investigate possible approaches for migrating from the Connectivity Proxy Reconciler to the Connectivity Proxy module

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#18451]
**Description**
The Connectivity Proxy Reconciler will be at some point replaced with the Connectivity Proxy module. We must prepare a plan for migrating it to the Connectivity Proxy module.

The migration plan should include:
- functionalities that are missing in the Connectivity Operator to work on Kyma clusters
- list of steps to perform in order to switch from the Connectivity Proxy Reconciler to the module
- plan for upgrading the current Connectivity Proxy version to 2.9.3 to fix the following [issue](https://jira.tools.sap/browse/NGPBUG-355416) (we should consider if the upgrade is feasible as a part of migration activities)
- responsibilities of the Connectivity Proxy, and Kyma team

**Comment by akgalwas** [comment]
Workplan
- [ ] Answer CP guy's questions: **In progress**
  - [x] How to get `subaccountId`, and `serviceKey`? **In progress**
  - [x] How to get `businessTunnelURL`? 
  - [ ] How to implement the migration script?
- [x] Prepare cluster on STAGE with the Connectivity Proxy installed
- [ ] Learn how to install their module on a clean Gardener cluster
- [ ] Analyse k8s objects the module installs
- [ ] Come up with migration plan
  - [ ] Verify blue-green approach (installing the module on top of the existing Connectivity Proxy) **Not feasible now**
  - [ ] Verify the possibility on their side to rename k8s objects so that the module will smoothly install it's resources **Not feasible now**
  - [ ] Verify the information that the Reconciler skips reconciliation when the  CRD exists [see this](https://github.com/kyma-project/community/blob/main/concepts/modularization/migration.md). How the Reconciler knows what is the CRD type?
- [ ] Come up with a plan of upgrading the Connectivity Proxy to 2.9.3
  - [ ] Verify option with upgrading before migration to the module within the same maintenance window
  - [ ] Verify option with incorporating 2.9.3 changes into the module. Learn why they claim it is not possible.

**Comment by akgalwas** [comment]
There are the following ideas for migration to the module:
- Connectivity Proxy operator will apply k8s objects with the same names as old Connectivity Proxy reconciler does
- Blue green deployment
- Removing all objects created by the Connectivity Proxy reconciler, and installing the Connectivity Proxy module

The first two options allow to perform smooth migrations so this is the preferred approach. The last option will cause downtime, and we should avoid it if possible.

**Comment by akgalwas** [comment]
**Migration option number 2 (blue green deployment)**

The general idea would be to install the Connectivity Proxy module on top of the existent installation in two steps:

1. Create CR, and wait until the Connectivity Proxy is installed by the module's operator
2. Remove objects installed by the old Connectivity Proxy Reconciler

There are the following variants:

1. The Connectivity Proxy module installs the k8s objects to `kyma-system` namespace
2. The Connectivity Proxy module installs the k8s objects to some other namespace

**Option number 1**
The module should rename objects (such as stateful set, deployments, etc) to allow to apply the objects in the `kyma-namespace`. There are the following problems:
- The Connectivity Proxy service name must be the same to make sure that the users workloads will work
- The operator applies cluster scope resources (e.g. ServiceMapping CRD, RBACs) so the operator will fail to install the resources (the Java Operator Framework limitation)
**This approach is infeasible with the current Connectivity Proxy module implementation**

**Option number 2**
There are the following problems:
- Since the Connectivity Proxy k8s objects will be installed in some other namespace there will be a need to change users wokloads (as they use `connectivity-proxy.kyma-system.svc.cluster.local` to access the Connectivity Proxy)
- The operator applies cluster scope resources (e.g. ServiceMapping CRD, RBACs) so the operator will fail to install the resources (the Java Operator Framework limitation)
**This approach is not feasible as it impacts the users workloads**

**Comment by akgalwas** [comment]
**Migration option number 3 (Uninstall the old reconciler, and enable module)**

Steps: 

1. Add the Connectivity Proxy module resource name to this config file: https://github.com/tobiscr/control-plane/blob/d43ad59ec47b9815efa1683c1f3b467b2ae3a5a1/resources/kcp/charts/mothership-reconciler/values.yaml#L153
2. Prepare a script that will read the current CP configuration (installed via the old Reconciler), and create a CR. It should work for cases, no matter if CP is installed or not.  
3. Prepare a script that removes the old Connectivity Proxy (use kubectl) 
4. Perform the migration on runtimes: 
- Run the script to prepare a CR. 
- Apply the CR for the module 
- Remove all k8s objects for the "old" Connectivity Proxy

**Comment by akgalwas** [comment]
Connectivity Proxy module requirements to integrate with Kyma infrastructure:

- [ ] The operator should make sure that Istio CRDs such as `VirtualService` are available
- [ ] The operator should make sure that BTP related CRDs are available (`serviceinstance.services.cloud.sap.com`, and `servicebinding.services.cloud.sap.com`)
- [ ] Fetch the configuration data (such as `subaccount id` ). The operator should read Service Instance, Service Binding, and secret created by the BTPOperator.
- [ ] Fetch business tunnel URL
- [ ] Consider the ability to take over k8s objects that are created by the old Connectivity Proxy Reconciler
- [ ] Consider what options should be available in the module's UI. Probably it can be skipped for the initial release, and the operator can rely on fallback logic.

**Comment by akgalwas** [comment]
We need to remember to remove the Connectivity Proxy from the list of additional components in the KEB. Before we do that we need to:
- Disable reconciliation for new and existing clusters
- Perform the migration.

There are two ways of disabling reconciliation:
- [In the KCP config](https://github.tools.sap/kyma/management-plane-config/blob/main/argoenv/kcp/dev/values.yaml#L162)
- [In the Mothership Reconciler](https://github.com/kyma-project/control-plane/blob/797dd7916d906bc8411c2d28205bce0a7b4aaea7/resources/kcp/charts/mothership-reconciler/values.yaml#L161). This option disables reconciliation only if particular CRD exists on a SKR.

**Comment by tobiscr** [comment]
JFYI:

> * [In the Mothership Reconciler](https://github.com/kyma-project/control-plane/blob/797dd7916d906bc8411c2d28205bce0a7b4aaea7/resources/kcp/charts/mothership-reconciler/values.yaml#L161). This option disables reconciliation only if particular CRD exists on a SKR.

There is also the option to disable the reconciliation of a old Kyma component completely - independent whether a CRD exists (configurable here: https://github.com/kyma-project/control-plane/blob/797dd7916d906bc8411c2d28205bce0a7b4aaea7/resources/kcp/values.yaml#L141)

**Comment by akgalwas** [comment]
Plan for migration to 2.9.3 is proposed here: https://github.tools.sap/kyma/backlog/issues/4334#issuecomment-4767995

**Comment by akgalwas** [comment]
There is an issue for creating migration script: https://github.com/kyma-project/kyma/issues/18482 .

**Comment by akgalwas** [comment]
The following has been decided:
- The operator will require to remove objects such as stateful set, service mapping operator, restart watcher etc.
- Service Mappings created by the users will be taken over.
- There will be automatic migration implemented in a form of a bunch of init containers
