### ISSUE TITLE
Pipeline Failing: kyma-upgrade-gardener-kyma2-to-main-reconciler-main

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#18478]
**Description**
The pipeline `kyma-upgrade-gardener-kyma2-to-main-reconciler-main` is failing due to the following reason:
```
Could not find the authorization token for https://github.com/kyma-project/kyma repository, GIT_CLONE_TOKEN environment variable is not set
```

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main

**Expected result**
Pipeline should succeed

**Comment by nesmabadr** [comment]
This is because the istio component was removed.
Error from the pipeline logs:
 `Error: failed to get istio version: open /home/prow/go/src/github.com/kyma-project/kyma/main/resources/istio/Chart.yaml: no such file or directory`

This should be fixed with the new CLI release since the fix for the `kyma deploy command` is already merged: https://github.com/kyma-project/cli/pull/1876

**Comment by janmedrek** [comment]
We have decided to drop the support for the mothership Reconciler pipelines (it reconciles nothing currently). Only component reconcilers are important now.
