### ISSUE TITLE
Static content in Console UI is not protected

### ISSUE THREAD

**Issue by evilyeti** [kyma-project/kyma#1884]
# Static content in Console UI is not protected

**Description**

When logging into the console admin tool, the user experience first shows the Kyma logo + the overal frame and only then kicks the request towards DEX for authentication. 
That's due to the /assets folder not requiring authentication. 

Imho we should not serve any parts of the console without authentication, besides the login flow selector, robots.txt and favicon.ico. This has no negative impact on resource caching, assuming that they still serve the corresponding cache headers properly.

**Expected result**

I'd expect to get redirected to login page without being able to download anything from the console admin tools. 

**Actual result**

I get a blink of an empty screen with the top header + the Kyma logo, then it 

**Steps to reproduce**

1. Open a new browser
2. Enable request tracing
3. Open console.cluster.url
4. look for the logo.svg download attempt. Today it returns the file - should return a redirect request. 

Cheers. 
   Krassi

**Comment by meeque** [comment]
I do not consider this to be a security vulnerability. All resources that are hosted on console.cluster.url are publicly available by design. I.e. they do not require confidentiality, therefore no authentication and authorization checks are performed. 

The visual experience of the redirect to the DEX authorization server is debatable of course. Personally, I find the current implementation satisfactory though.

**Comment by hardl** [comment]
Visual experience improvement covered by this ticket https://github.com/kyma-project/luigi/issues/449
