### ISSUE TITLE
Rename environments to namespaces

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#1899]
The decision has been made to rename environments to namespaces, with that the following components need to be changed :
-  the `environment controller` needs to be renamed to `namespace controller`
- view in the console needs to be updated + core ui calls to ui-api-layer
- documentation must be updated
- update ui-api-layer sources in the domains : api-controller, service-catalog, kubless

**Comment by polskikiel** [comment]
IMO, there was no reason to split renaming of UI-API-layer between modules and teams. There are many shared places in the UI-API-layer which also were to change like e.g. `kyma/components/ui-api-layer/internal/gqlerror/errors.go`. The task was easy enough to let one person do the job. Now, because of the task separation among different people, the PRs have conflicts and it's also more likely to create a bug (e.g. forget to rename some endpoint: https://github.com/kyma-project/console/pull/535).
