### ISSUE TITLE
Add test user password to readme file instead of providing path + filename

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/kyma#197]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.

**Description**

People deploying Kyma locally have to find the password for the test user in a file. In readme file currently path + filename is provided. I would suggest to write the password directly in the readme file or if this not desired provide a link to the file instead of the current approach.

**Comment by derberg** [comment]
actually maybe instead of doing it in the docs, better to do it in the UI actually. This is going to be the easiest and nicest solution for Kyma local users

**Comment by meeque** [comment]
I believe that having hard-coded default passwords is a bad idea altogether. Some users might expose even their local Kyma clusters to the local network or the Internet. Their Kyma clusters, and all connected systems would become vulnerable, since default passwords are known to attackers.

Instead, generate strong, securely random passphrases during the install process. Print these passphrases (and the corresponding users) to the console. Or emit them to a local file (which should only be readable by the current OS user.)

Alternatively, let the install script elicit the passphrases interactively. Or make them configurable via env-vars or CLI arguments.

In fact, a combination of all the above options would be preferable for best usability.

**Comment by derberg** [comment]
@pbochynski could you please take a look. I guess that at the moment it is true right? that if I do not connect any identity provider I can end up with going to a cluster with static user.

**Comment by sjanota** [comment]
Invalid after fixing #741
