### ISSUE TITLE
Rename environments to namespaces in ui-api-layer under application domain

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#2214]
As a part of renaming environments to namespaces, we have to update namespaces in `application` domain in the ui-api-layer as well.
Take a look at https://github.com/kyma-project/kyma/tree/master/components/ui-api-layer/internal/domain/application there are references to environments for example in application service.

Tests if necessary should be updated as well.

We have to keep in sync with console ui and other components: api-controller, service-catalog, kubeless which also need to make such changes in ui-api-layer.

**Comment by franpog859** [comment]
- Under Application domain queries `Applications`, `EventActivations`, `EnableApplicationMutation` and `DisableApplicationMutation` use parameter `namespace` instead of `environment`. `ApplicationMapping` type has `namespace` instead of `environment`. See the [PR with API change](https://github.com/kyma-project/kyma/pull/2328).
- Queries in console repository are changed to match the parameter. See the [PR with queries change](https://github.com/kyma-project/console/pull/506).
- Bump PR changes images of ui-api-layer and console to sustain compatibility. See the [PR with images bump](https://github.com/kyma-project/kyma/pull/2339).

**Comment by lszymik** [comment]
@framefrog team,
Unfortunately, I am not able to accept that issue due to regression caused in Lambda UI.

Please apply required changes in Lambda UI code.

Cheers
Lukasz
