### ISSUE TITLE
Install Kyma on AKS

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#2233]
**Description**

Part of our release theme: Generalize deployment and operational aspects so that also Microsoft AKS can be supported.

**Acceptance Criteria**

- prepare installation instruction (use GKE installation guide as a template)
- make sure kyma works (installation process and test are green)
- create unified documentation about GKE and AKS with wildcard DNS

**Attachments**

- Kyma on GKE installation guide, see: 
  - https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/032-inst-gke-installation.md
  - https://kyma-project.io/docs/master/root/kyma#installation-install-kyma-on-a-gke-cluster
- Kyma on GKE with wildcard DNS installation guide
  - https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/036-inst-xip.io-domain.md
  - https://kyma-project.io/docs/master/root/kyma#installation-install-kyma-on-a-gke-cluster-with-wildcard-dns

**Comment by adamwalach** [comment]
There are two issues with running Kyma on AKS. 
1. During installation the readiness probe on service-catalog-apiserver fails with 403
This is a known issue: https://github.com/Azure/AKS/issues/417
A bit more description can be found here: https://github.com/appscode/voyager/issues/1296
Suggested solution is to allow "system:unauthenticated" group to access ["/healthz", "/healthz/*"] endpoints: https://github.com/helm/charts/issues/10222#issuecomment-450924832. This is not perfect cause this policy is to open
2. Kyma UI cannot access Pods, Services and all other resources that are fetched through K8S dashboard. <img width="1440" alt="screen shot 2019-01-18 at 15 00 59" src="https://user-images.githubusercontent.com/8530211/51391499-811d3300-1b32-11e9-83fa-d2aae33cf59e.png">
This issue has two causes:  
- istio network setup 
It is also known: https://github.com/Azure/AKS/issues/561.
Directly after installation we've got error 403. When we added `global.proxy.excludeIPRanges` to the installation yaml 
![screen shot 2019-01-18 at 15 07 51](https://user-images.githubusercontent.com/8530211/51391629-dc4f2580-1b32-11e9-9e3f-ec009f7380ef.png) the error changed to 503.
 - dashboard is exposed using http instead of https.
It causes the 503 error. This port cannot be changed in the SVC, we tried to modify that and it always preserves original values. The only solution is to add configuration parameter to Kyma so we can set url for K8s dashboard to a proper value during installation. Or we could stop using the dashboard as a datasource.

**Comment by adamwalach** [comment]
Logs from tests:
* standard installation [test-on-aks-standard.log](https://github.com/kyma-project/kyma/files/2783186/test-on-aks-standard.log)
* with xip enabled [test-on-aks-xip.log](https://github.com/kyma-project/kyma/files/2783187/test-on-aks-xip.log)
Overall test results looks good, there are some failed checks but they are caused by the k8s dashboard issue.

**Comment by adamwalach** [comment]
Follow ups:
* https://github.com/kyma-project/kyma/issues/2273

**Comment by PK85** [comment]
Findings:

1. Kubectl configuration duplicated, see:
  - point 2 - https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/04-05-aks-installation.md#prepare-the-aks-cluster
  - point 2 - https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/04-05-aks-installation.md#deploy-kyma
