### ISSUE TITLE
Installer is not able to upgrade cluster-essentials release

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#2560]
**Description**

One new resource (CRD: clustermicrofrontends.ui.kyma-project.io) has been added into cluster-essentials chart and since that time, upgrade plan is failing, see [here](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/2486/pre-master-kyma-gke-upgrade/1092336274313842690)

Looks like a bug in helm itself, please see issues I've added to Troubleshooting section.
When we release 0.7 and run gke-upgrade plan that issue will disappear, but it will happen if someone will add any new resource again.

**Expected result**

Cluster-essentials release update should pass without errors.

**Actual result**

Upgrade plan fails on cluster-essentials step with below error:

```
2019/02/04 08:44:08 Step error: Details: Helm upgrade error: rpc error: code = Unknown desc = no CustomResourceDefinition with the name "clustermicrofrontends.ui.kyma-project.io" found
--
524 | 2019/02/04 08:44:08 Error during install/update: Details: Helm upgrade error: rpc error: code = Unknown desc = no CustomResourceDefinition with the name "clustermicrofrontends.ui.kyma-project.io" found
525 | E0204 08:44:09.004258 1 controller.go:286] Helm upgrade error: rpc error: code = Unknown desc = no CustomResourceDefinition with the name "clustermicrofrontends.ui.kyma-project.io" found
```

**Steps to reproduce**

Could be reproduced on every new resource:
- https://github.com/helm/helm/issues/1193#issue-176719112

**Troubleshooting**

- https://github.com/helm/helm/issues/1193#issuecomment-459846500
- https://github.com/helm/helm/issues/3275

**Comment by strekm** [comment]
just verified workaround scenario:
- create a simple chart containing simple resource e.g. namespace
- helm install the chart
- add another resource e.g crd
- helm upgrade will fail with `Error: UPGRADE FAILED: no CustomResourceDefinition with the name "backendmodules.ui.kyma-project.io" found`
- helm rollback the release to previous version
- helm upgrade should be ok this time

```
helm install ./resources/cluster-essentials-ms --name ms --namespace kyma-system
NAME:   ms
LAST DEPLOYED: Wed Feb 13 10:59:46 2019
NAMESPACE: kyma-system
STATUS: DEPLOYED

RESOURCES:
==> v1/Namespace
NAME           STATUS  AGE
production-ms  Active  1s
```

```
kc get ns
NAME             STATUS   AGE
default          Active   1h
istio-system     Active   1h
kube-public      Active   1h
kube-system      Active   1h
kyma-installer   Active   1h
kyma-system      Active   1h
natss            Active   39m
production       Active   1h
production-ms    Active   8s
```
here happened one successfull upgrade not relevant for this scenario
```
helm upgrade ms ./resources/cluster-essentials-ms --namespace kyma-system --reuse-values
Error: UPGRADE FAILED: no CustomResourceDefinition with the name "backendmodules.ui.kyma-project.io" found
```
that's why at this moment i have 3 revisions and rollback to 2 revision
```
helm rollback ms 2
Rollback was a success! Happy Helming!
```

```
helm upgrade ms ./resources/cluster-essentials-ms --namespace kyma-system --reuse-values
Release "ms" has been upgraded. Happy Helming!
LAST DEPLOYED: Wed Feb 13 11:04:52 2019
NAMESPACE: kyma-system
STATUS: DEPLOYED

RESOURCES:
==> v1/Namespace
NAME           STATUS  AGE
stage-ms       Active  3m
production-ms  Active  5m

==> v1beta1/CustomResourceDefinition
NAME                               AGE
backendmodules.ui.kyma-project.io  0s
```

**Comment by strekm** [comment]
To workaround this bug in installer i would propose following:
- catch failed upgrade and determine whether it is `no * with the name "*" found`
- rollback
- retry upgrade

In any other upgrade fails we should NOT rollback.

Have a look in https://github.com/kyma-project/kyma/blob/bc1d615e9090ad3871ca8aef6e630dd1c6baf557/components/installer/pkg/kymainstallation/step.go#L86

**Comment by piotrmsc** [comment]
We should check if adding `crd-install` hook will help in case of crds, however https://github.com/helm/helm/issues/4697 :) 
We have to distinguish when to make rollback, there are already 2 different errors returned on different resources(crd and configmap) which gets tricky. 
Taking this into account, we can think of doing rollback on each release upgrade error but only **once**

**Comment by Demonsthere** [comment]
Update:
We have found the root of this problem, and it is not exactly what was suggested by the error message (which, lets be honest, are kinda bad). 

**What is happening**
We are performing an upgrade from 0.6.1 to the current master/PR 

**Problem**
Some resource (CRD in this case) has been moved from one chart to another (probably from core to cluster-essentials). During the upgrade we start from 0.6.1 in which the CRD is installed as part of the core chart. We try to upgrade the cluster to master, in which the same CRD (the same name) is now a part of core-essentials. 

**What happens**
During upgrade helm sees that the object (CRD) already exists, so it tries to update it. However, as the object is not a part of that chart, it does not exist in the tiller db, and the upgrade fails. 

**Conclusions**
- Moving resources from one chart to another requires a change of the resource name. Because of that moving CRDs **is a breaking change**
- The upgrade job will start working again, once we try to upgrade from 0.7 to master, as at that point the CRD in question will already by a part of cluster-essentials

**Comment by sjanota** [comment]
Further investigation showed that `rollback` behaves weird. Imagine a scenario:
1. Release `cluster-essentials` is installed. It does not contain mentioned CRD
2. Release `core` is installed with the CRD.
3. CRD is moved to `cluster-essentials`.
4. Release `cluster-essentials` is upgraded. The upgrade fails because of a conflict.
5. We do a rollback as [suggested](https://github.com/kyma-project/kyma/issues/2560#issuecomment-463147015)
 
At this point it appears that during rollback helm **has removed the CRD** even though the upgrade failed and CRD belongs to different release. Along with CRD all its implementations has been removed.

**Comment by sjanota** [comment]
Here's helm issue for that: helm/helm#5315
