### ISSUE TITLE
Enable xip integration as default behaviour

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#2563]
**Description**
For cluster environments, we should enable our xip.io integration as a default mechanism in kyma.
However, it should work in the following manner:

- if the domain and TLS certs are provided do not modify anything
- if TLS certs and domain are **not** provided then generate new TLS certs and deploy kyma with xip domain
- if the domain is provided but TLS certs not then generate self-signed TLS certs for that domain
- if cert is provided but the domain is not, then return an error with message indicating incomplete setup
- minikube setup remains the same - no changes here

By enabling xip as default behavior we can merge **xip-patch** with **istio-kyma-patch**. 

Because the application connector is using nginx ingerss controller, we need to create a job that will do the same thing for nginx after installation of app gateway - create a domain and TLS cert but under the same conditions as mentioned above.

**Reasons**

It will simplify kyma installation on the cluster envs. It will be easier to try out kyma out of the box.

**Attachments**

Acceptance criteria:

- [ ] xip handling enabled by default, working under conditions mentioned in task description @jakkab 
- [ ] the same job is created for application gateway as a post install job - the copy paste is acceptable as this is **temporary** untill istio 1.1 will be released and nginx ingress controller will be deleted in kyma (@Tomasz-Smelcerz-SAP )
- [ ] Documentation is updated, DNS setup sections are refactored, mentioning xip is default but you can set it up and refer to existing documents
- [ ] Tests are passing on a cluster 
- [ ] minikube setup remains the same - no changes here
- [ ] @kfurgol notify breaking pixels about this change :)

**Comment by Tomasz-Smelcerz-SAP** [comment]
Application connector can't be easily handled by just a job - bigger refactoring is necessary.
The problem is: The domain and certs are input parameters for application connector chart. These values are then used as arguments for processes running in pods created with Deployments/StatefulSets.
In existing setup it's not a problem because IP Address, Domain and certs are prepared before application connector chart is installed.
In xip scenario the value for domain and corresponding certs depends on IP Address. But IP Address is known only after a LoadBalancer Service is created, which is a part of application connector chart. It means we have a chicken-or-egg problem.
To break this dependency chain, we have to extract the Service (LoadBalancer) from application connector chart and install it as a separate component earlier in the installation pipeline.
Then we have access to IP Address for nginx ingress, we can configure proper Domain and Certs for the remaining application connector chart.
