### ISSUE TITLE
Graceful shutdown and restart for subscription controller. 

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#2609]
**Description**
When the subscription-controller receives an interrupt or a KILL SIGNAL, it should first finish all on-going work on handling events for custom resources.

New events should not be acted upon. Refer Knative controller implementations.

**Related issues**
See the related bug: https://github.com/kyma-project/kyma/issues/2427

**AC**
- [x] Handling on controller events is done gracefully when the pod is getting killed. This should be visible in the logs.

**Comment by suleymanakbas91** [comment]
I implemented the same shutdown logic with Knative controllers. It handles graceful shutdown for the HTTP server, and the controller manager. However, it is nowhere possible for a controller to finish up reconciling before shutting down. It can receive a kill signal in the middle of reconciling and it will simply die. We can only count on the next one coming alive to reconcile and create anything missing from the previous one.

**Comment by suleymanakbas91** [comment]
Right now, when a subscription controller Pod is killed, the next one can reconcile the object that couldn't be reconciled by the previous one. This can be tested by putting a sleep inside the reconcile method and killing the Pod. 

If the Pod is killed during deleting the external dependencies, it is still fine because the finalizer won't be deleted until the external dependency deletion succeeds. 

We just need to keep this in mind while writing new controllers. They should be desinged in a way that even though it is killed, the next one should be able to start over the reconcile.
