### ISSUE TITLE
Provisioning more than one service instance of GCP Service Broker Provider should be prevented

### ISSUE THREAD

**Issue by arifC** [kyma-project/kyma#2612]
**Description**
Kyma version: 0.6.1
It is possible to create more than one instance of the service class "GCP Service Broker Provider". The description of this service class states that you cannot do this. Also, having more than one running instance of this service class leads to unexpected behavior such as e.g. failing GCP PubSub instance when one of the GCP Service Broker instance is deprovisioned. I might open an issue for that as well.

<img width="777" alt="bug" src="https://user-images.githubusercontent.com/11600883/52335953-f4b0b280-2a03-11e9-9738-0a253dfafec9.PNG">

**Expected result**
There is at most one running service instance in a namespace serving the GCP Service Broker Provider.

**Actual result**
There can be two and more running service instances for a namespace.

**Steps to reproduce**
This was observed for a Kyma 0.6.1 installation running on GCP.
Select a namespace and add the GCP Service Broker Provider multiple times to your namespace.

**Comment by PK85** [comment]
Already addressed and fixed in 0.7. Both GCP and Azure Service classes are now marked with label "provisionOnlyOnce" which is a new feature in helm-broker and bundles. See details: 
- https://github.com/kyma-project/kyma/issues/1716
- https://kyma-project.io/docs/0.7/components/helm-broker#configuration-how-to-create-a-bundle-the-bundle-meta-yaml-file

The 0.8 will have support in UI itself, see details:
- https://github.com/kyma-project/kyma/issues/2489
