### ISSUE TITLE
Dex issues tokens that have expiry date set in the past

### ISSUE THREAD

**Issue by y-kkamil** [kyma-project/kyma#2839]
**Description**

If you leave a locally running kyma cluster (on minikube) for a prolonged period of time (don't know exact numbers, but leaving overnight is ok) it is impossible to log in to console. Console reports: 
`Error: exp is in the past:1550816826
    at Function._validateJwt (oidc-client.min.js:46)
    at Function.validateJwt (oidc-client.min.js:46)
    at oidc-client.min.js:46
Could not instantate openIdConnect provider : Error: exp is in the past:1550816826`

Looking at the expiry date it is clear that it's already in the past.

**Expected result**

Dex issues valid token and one can log in to the console.

**Actual result**

Described above.

**Steps to reproduce**

Start kyma locally, try to log in to console with `admin@kyma.cx` and credentials obtained with `kubectl get secret ...` - it should work. Leave it for several hours. Now try to log in again with the same credentials. You'll receive the error described above.

**Comment by piotrmsc** [comment]
@y-kkamil can you still reproduce the issue? And  did you stop & restart the minikube when the error occurred?

**Comment by y-kkamil** [comment]
@piotrmsc i can confirm it still exists, minikube restart does not help

**Comment by piotrmsc** [comment]
@y-kkamil I was able to reproduce it and according to https://kyma-project.io/docs/root/kyma/#installation-install-kyma-locally-troubleshooting 
given command `minikube ssh -- docker run -i --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i date -u $(date -u +%m%d%H%M%Y)` helped. After that I was able to log in into console. It happens because with sleep or stop&start system clock settings are not synced with the machine. 
Please verify if it helps for you as well

**Comment by y-kkamil** [comment]
it works with the command you provided
