### ISSUE TITLE
Ensure eventing and tracing works post mTLS enablement

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3026]
**AC**
- [x] E2E eventing scenario has been verified and any issues have been fixed
- [x] Event Tracing works with mTLS enabled
- [x] Tracing for an exposed API has been verified and any issues have been fixed

**Comment by abbi-gaurav** [comment]
This story is targeted for 1.0

**Comment by montaro** [comment]
Blocked by https://github.com/kyma-project/kyma/issues/3320

**Comment by marcobebway** [comment]
I was able to verify:
- Publish events using port-forward to the event-service app:
```bash
$ curl -i -H "Content-Type:application/json" -X POST http://localhost:8081/sample-external-solution/v1/events -d '{"event-type": "order.created", "event-type-version": "v1", "event-time": "2018-11-02T22:08:41+00:00", "data": {"event":{"customer":{"customerID": "1234", "uid": "rick.sanchez@mail.com"}}}}'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Fri, 12 Apr 2019 13:15:44 GMT
Content-Length: 130

{"event-id":"a895c50d-02c0-4343-9c37-c78cf1a396d4","status":"published","reason":"Message successfully published to the channel"}
```
- Receive events from lambda app: 
```bash
$ kubectl logs -f -n workshop test-8fcb6f457-7l7f8 -c test
::1 - - [12/Apr/2019:13:15:40 +0000] "GET /healthz HTTP/1.1" 200 2 "-" "curl/7.52.1"
event: [object Object]
::ffff:127.0.0.1 - - [12/Apr/2019:13:15:44 +0000] "POST / HTTP/1.1" 200 - "-" "Go-http-client/1.1"
::1 - - [12/Apr/2019:13:15:45 +0000] "GET /healthz HTTP/1.1" 200 2 "-" "curl/7.52.1"
```
- Trace spans are created from the publish-app to lambda.
![tracing](https://user-images.githubusercontent.com/24314423/56047399-9aa2d500-5d45-11e9-8696-f45945d4aebe.png)

I was **not** able to verify:
- Sending events from an application outside of Kyma, because of some issues related the gateway which causes **502 Bad Gateway** responses.
- If the whole trace spans are created or not for the whole end-to-end scenario.

**Comment by montaro** [comment]
To be confirmed after releasing the RC-1

**Comment by abbi-gaurav** [comment]
@montaro , please add the snapshot of the detailed event trace in the task.

**Comment by montaro** [comment]
![image](https://user-images.githubusercontent.com/531945/56600746-c05b9400-65f9-11e9-930a-a0c50fc51073.png)

**Comment by montaro** [comment]
![image](https://user-images.githubusercontent.com/531945/56600767-ca7d9280-65f9-11e9-8311-a33e8e0c06a1.png)
