### ISSUE TITLE
KNative components  0.4.1 installed with Kyma are not consistent part of Istio service mesh 

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#3324]
After the installation of Kyma with Knative, the following inconsistences between our deployment and the installed system exist:
- In the namespace "knative-eventing":
NATSS controller is part of service mesh on the running Kyma,  but without having an Istio annotation in its deployment. Is it necessary to have it as part of service mesh?

- In "knative-serving":
All KN components ( activator, autoscaler, controller, webhook ) are not part of service mesh on the running Kyma, but activator and autoscaler are deployed by us having the Istio annotation "true". 

In both cases, we have to check the original installation of Knative 0.4.1 and decide our approach to it.

**Comment by abbi-gaurav** [comment]
@radufa Please provide the description and the reasoning.

**Comment by abbi-gaurav** [comment]
The discrepancies could be due to the reason that `knative-serving` and `knative-eventing` get installed before `istio-kyma-patch`.

We need to check the security implications of disabling the service mesh for nats controller.

* Will this be acceptable from security standards?
* Can we have `nats-streaming` in Istio service mesh and controller not there and will it work with mTLS?

**Comment by abbi-gaurav** [comment]
This has been fixed by installing istio patch before knative.
