### ISSUE TITLE
Logging test failing on GKE postsubmit jobs

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/kyma#3435]
**Description**
Logging tests are failing for gke postsubmit jobs with the following error:
```
- Logging module is installed. Running tests for same
RUNNING: test-logging-logging
FAILED: test-logging-logging, run `kubectl logs test-logging-logging --namespace kyma-system` for more info
Error: 1 test(s) failed
```

**Expected result**
Logging microfrontend tests run successfully

**Actual result**
There is a failing test for logging microfrontend

**Steps to reproduce**

**Troubleshooting**

Prow logs:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1111546535927091200
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-central-connector/1111546535927091201
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1111546535931285504

**Comment by sayanh** [comment]
Turns out that the change in folder structure for `/var/log/pods` in GKE 1.12.6 is causing the issue for promtail pods. The test was fine with GKE 1.12.5. As there is no control over the minor versions of k8s in [here](https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/helpers/provision-gke-cluster.sh#L38), the issue started happening recently. It is also found that k8s version for aks is 1.11 as in [here](https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-aks-long-lasting.sh#L55)  which needs to be revisited.

**Comment by rakesh-garimella** [comment]
resolved by this PR: https://github.com/kyma-project/kyma/pull/3565. So closing the ticket.
