### ISSUE TITLE
Job failed: DeadlineExceeded

### ISSUE THREAD

**Issue by sjanota** [kyma-project/kyma#3590]
**Description**
It happens randomly that one of core jobs fail with timeout. The error log looks like this:
```
core:
Helm install error: rpc error: code = Unknown desc = Job failed: DeadlineExceeded
core:
Helm install error: rpc error: code = Unknown desc = a release named core already exists.
Run: helm ls --all core; to check the status of the release
Or run: helm del --purge core; to delete it
```
The problem is unrecoverable.

Unfortunately, helm does not provide information which job failed. Once I was able to list jobs on a cluster in such state and here's what I've found:
```
$ kubectl get jobs --all-namespaces
NAMESPACE     NAME                              COMPLETIONS   DURATION   AGE
kyma-system   apiserver-proxy-certs-job         1/1           26s        6m58s
kyma-system   core-documentation                1/1           85s        5m53s
kyma-system   core-documentation-azure-broker   0/1           4m28s      4m28s
```
but it's one case. I cannot confirm if it's the only one.

**Expected result**
Kyma installs successfuly

**Actual result**
Kyma ends up in unrecoverable state

**Steps to reproduce**
Random

**Troubleshooting**

**Comment by Tomasz-Smelcerz-SAP** [comment]
The logs clearly indicate three problems, but only one of them is the cause of failure
- problem with `istio`: not important, it's a recoverable error. There's an issue for that: #3589
- problem with `core`: `Helm install error: rpc error: code = Unknown desc = Job failed: DeadlineExceeded`. This is the cause of the failure.
- problem with `core`: `Helm install error: rpc error: code = Unknown desc = a release named core already exists.` - This is just an indication, that the Installer tried to reinstall `core` release which is in `error` state. It's not the root cause of the failure.

As for the failing job: We don't know which job failed. Helm itself doesn't report it.
One thing we could do is to improve the logging. Upon the error, we could, for example, report status of all Pods and Jobs. Or be even smarter and parse the actual error for 'Job failed' token and only then report the status of all jobs.
This should be done in the script that is watching the installation process.
It looks like the task for CI SIG for me.

**Comment by sjanota** [comment]
Question 1: Where to log? There are 3 options to approach extended logging:
* installer - I strongly oppose as the only way to find it out here is to parse helm error messages. Messy.
* `is-installed.sh` - We could add it here, however then we will need extended logging on production. Do we want it? If so that's the way to go.
* prow scripts - Almost the same as `is-installed.sh`, but it won't end up on production.

Question 2: What to log? I have really no preference. Every option is bad as we cannot cover every error scenario. Best we can do is `kubectl get all --all-namespaces`, but then we shouldn't log it on production I think.

**Comment by Disper** [comment]
Another failing run: https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-integration/1118085736633995265/build-log.txt

**Comment by swarnadeepsaha** [comment]
May be related - https://github.com/kyma-project/kyma/issues/5451

**Comment by piotrmsc** [comment]
It looks like this error was related to timeouts in communication with tiller, which had 5s. Timeout was increased to 30s, on KIND such errors occurred quiet often and after this change it did not occur anymore.
@michal-hudy provided this change and tested it on KIND

**Comment by Demonsthere** [comment]
We will look for a method of getting the information about failing jobs from Tiller and add them to the installer logs. Will keep this issue alive for tracking purposes.
