### ISSUE TITLE
Create configuration docs for Asset Store

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/kyma#3636]
**Description**

Create configuration documents for these Asset Store components: Minio, asset-store-controller-manager & asset-metadata-service -> see details [here](https://github.com/kyma-project/kyma/tree/master/resources/assetstore/charts).

They need to include the technical explanation of all values within a given component's chart and subcharts that are recommended for configuration.

Create a follow-up task for replacing hardcoded values in templates with placeholders and moving them to the given values.yaml file.

**Related issues**

See also #3540

**Comment by mmitoraj** [comment]
We (@kazydek and @mmitoraj) had a bunch of meetings with POs and developers. We learned that:
- Some teams would find having configuration documents useful (e.g. Framefrogs for the Application Connector) but for others, there are none or not many configuration details in the values.yaml files which can/should be configured and mentioned in a separate doc. 
- Any of the Wookiees' components (Asset Store, Headless CMS and Console Backend Service) doesn't require configuration of the values.yaml files. 
- However, configuration regarding values.yaml files is not the only one possible.

In conclusion, we could:
- have general info about configuration options (overrides, etc.) under Kyma Installation
- add an optional section **Configuration** to charts' and subcharts' README.md files with info about parameters from the values.yaml that can be configured --> update chart README.md template
- update values.yaml files with parameters description (using #)
- create a template for a configuration document regarding component-specific configuration basing on the Helm Broker configuration doc (https://kyma-project.io/docs/components/helm-broker/#configuration-configuration) and docs regarding switching to the Minio Gateway Mode for the Asset Store (see

**Comment by derberg** [comment]
Hey, thanks for a deep investigation. My comments below in 3 bullets, to you first 3 bullets:

* I do agree that not all components need/have specific values in helm values files that require official documentation. This doesn't mean others do not need it. It is the same case with documentatio types like CRD or CLI references
* actually, these components require values/yamls and proper documentation for it:
  * Asset store example value that needs documentation https://github.com/kyma-project/kyma/blob/master/resources/assetstore/values.yaml#L37 but not only, we need proper values for switching to minio gateway and also proper setup of resource limits
  * hCMS needs improvement as values that are here https://github.com/kyma-project/kyma/blob/master/resources/cms/charts/cms-controller-manager/templates/webhook-config-map.yaml should be possible to extend/validate through values.yaml
  * for console backend nothing is here https://github.com/kyma-project/kyma/blob/master/resources/core/charts/console-backend-service/values.yaml because a lot of values are hardcoded here https://github.com/kyma-project/kyma/blob/master/resources/core/charts/console-backend-service/templates/deployment.yaml#L36
* I guess you mean that some components have values on deployment or config map level, these should be simply moved to values.yaml

Regarding conclusion:
* yes, we need a general explanation of configuration options and recommended ways to do that
* why hide docs in chart readmes again? who is reading them?
* yes, they anyway should be properly documented by developers as this is best practice https://helm.sh/docs/chart_best_practices/#document-values-yaml like other practices they should follow https://helm.sh/docs/chart_best_practices/#naming-conventions
* we need template for helm configuration not the things mentioned above:
  * https://kyma-project.io/docs/components/helm-broker#configuration-configuration is not really a configuration type but a tutorial about how to add your own bundles to helm broker
  * switching to gateway mode is special case, driven by product vision. This is why it requires separate config tutorial but still the values from values.yaml about gateway mode should be in the configuration reference doc


Look how nicely minio documents all https://github.com/helm/charts/tree/master/stable/minio#configuration (although in my opinion it is not needed), of course they did it in readme because of the structure of their documentation website and chart location, this is why they just reference these config details from documentation https://docs.min.io/docs/deploy-minio-on-kubernetes.html
