### ISSUE TITLE
The prometheus-monitoring pod is restarting

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#3838]
**Description**

The `prometheus-monitoring` Pod is constantly restarting because of the OOMKilled.

```
Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 24 Apr 2019 13:01:30 +0200
      Finished:     Wed, 24 Apr 2019 13:02:59 +0200
```

```
prometheus-monitoring-0                                           2/3     CrashLoopBackOff   312        2d4h
prometheus-operator-69fbb7485-cpgc6                               1/1     Running            0          2d4h
```

**Expected result**

The prometheus Pod is working without restarts

**Steps to reproduce**

I've seen such restart on the weekly cluster which works 2 days
```
NAME                      READY   STATUS      RESTARTS   AGE
prometheus-monitoring-0   2/3     OOMKilled   321        2d5h
```

**Comment by sayanh** [comment]
Few things we can do here:
- With stability checker running, either we can increase the ResourceQuota, LimitRange for `kyma-system` and in turn increase prometheus’ memory limit.
- Or we can reduce the retention period and tune it for a degraded QoS.
- Or we can move `monitoring` chart out to a different namespace with its own ResourceQuota and LimitRange.

@joek @a-thaler And the question is: for how much workload we want this Prometheus to withstand?

**Comment by joek** [comment]
Removing the bug lable as it is working as designed. @a-thaler needs to decide how many metrics we need to support in default kyma setup and on the sizing for weekly and production clusters.

**Comment by tricky42** [comment]
> Removing the bug lable as it is working as designed. @a-thaler needs to decide how many metrics we need to support in default kyma setup and on the sizing for weekly and production clusters.

Not sure if I agree here. I just quickly checked the Prometheus documentation and it looks like there are config parameters allowing us to configure Prometheus in a way it will not constantly restart with OOM and instead evict old data to stay within the configured memory limits. 
If this has been tried please let me know, otherwise I think we can find a better configuration to solve this problem.

**Comment by a-thaler** [comment]
@tricky42 Do you mean the new feature of configuring a size based eviction strategy mentioned here: https://prometheus.io/docs/prometheus/latest/storage/
Sounds like an improvement to have a time AND size based eviction strategy in place, however, that will probably not solve the memory issues.

Anyway, we will debug the cluster to the see where the problems are coming from and as follow up as suggested by @joek we will come up with a sizing strategy for the different scenarios.

**Comment by a-thaler** [comment]
@hisarbalik increased the requested memory and lowered the retention time. That showed good results on the nightly cluster. However, we should check the cortex ring buffer setup to maybe decrease the chunk size or the flush ratio in order to save memory so that we don't need to lower the retention time.
As the storage is limited to 4GB, please also configure the size based eviction, see https://prometheus.io/docs/prometheus/latest/storage/

**Comment by hisarbalik** [comment]
Problem is the default heap-size respectively retention time configured for prometheus (6 hour by default). 

Current configuration will keep data for last 6 hour in memory to avoid read recent data from disk, we will reduce this time to last 2 hour in prometheus configuration we should also change grafana default query time range from last 6 hour to last 2 hour.

**Comment by hisarbalik** [comment]
#4633

**Comment by rthamrin** [comment]
mine restarting every 3 hours and data was gone, sick of tired of this issues
