### ISSUE TITLE
Troubleshooting guide for installation and service-mesh

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#3940]
**Description**

Recently we observed many topics related to installation which are duplicates, however, valid and we do not have documentation for it. For example problems with tiller and `transport is closing` and istio crds not being visible. Creating a troubleshooting guide with the most common topics which occur in the community will help developers and will help us with giving help on community channels.

AC: 

New documentation topic displayed on kyma-project.io in area installation and service-mesh covering most common topics such as tiller certificates, installer logs/retires, istio crds not being visibile.

**Reasons**
Improve developer experience by giving easy access to documentation describing most common states that may occur, but are not a bug itself.

**Attachments**

**Comment by tomekpapiernik** [comment]
Ideas for **Installation** troubleshooting: 

1. Extract the existing 4 common cases from the local installation guide. 
2. (local) Console throws errors - Kyma cert not added to trusted -> [SLACK LINK](https://kyma-community.slack.com/archives/CD2HJ0E78/p1554910765135500)
3. (local) [Restarting minikube the right way](https://kyma-community.slack.com/archives/CD2HJ0E78/p1554025362021300)
4. (local) Console UI isn't accessible - Istio ingressgateway doesn't get the necessary config - Pod must be restarted to get the config - Console starts working -> related to a bug in Istio. 


Can't think of any cluster-related issues that are common enough to be added to a troubleshooting doc.

**Comment by piotrmsc** [comment]
I would also add to installation area problems with analyzing logs output of "is-installed" script. People often get confused with istio installation and think this is the root cause although failed different component.

**Comment by piotrmsc** [comment]
For service mesh I would describe problems with connection refused - ports not being opened in the ingress gateway. Additionally, mention problems with mTLS - crucial for people who deploy apps without sidecar

**Comment by Demonsthere** [comment]
Installation problem:
- When using your own image, and putting in in the wrong place in `my-kyma.yaml` causes [this](https://kyma-community.slack.com/archives/CD2HJ0E78/p1557229975048600)

**Comment by Demonsthere** [comment]
# Troubleshooting guide

## Installation

### Network error when accessing kyma console

**Description:**

When accessing kyma console, a [Network Error](https://kyma-community.slack.com/files/UJUCGTL0M/FJX5DL2UX/image.png) is presented. This will happen on any cluster (minikube, or cloud provider) that uses a Self Signed TLS certificate, and means that the certificate is not present in the system trust store. 

**Fix:**

There are two methods of fixing this issue:

- Trusting the self signed certificates in your browser ([Chrome](https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate), [Firefox](https://origin-symwisedownload.symantec.com/resources/webguides/sslv/sslva_first_steps/Content/Topics/Configure/ssl_firefox_cert.htm)). This needs to be done for the following sites: `apiserver.foo.bar`, `console.foo.bar`,  `dex.foo.bar`, `console-backend.foo.bar`
- Adding the wildcard certificate to the OS trust store ([MacOS](https://tosbourn.com/getting-os-x-to-trust-self-signed-ssl-certificates/), [Linux/Debian based](https://askubuntu.com/questions/645818/how-to-install-certificates-for-command-line), [Windows](https://specopssoft.com/support-docs/specops-password-reset/reference-material/installing-the-self-signed-ssl-certificate-into-the-trusted-root-certificate-authorities-store/))

### Errors after restarting minikube 

**Description:**

In the case of restarting kyma in minikube (by rebooting your machine, or using `run.sh` when a cluster is already present) minikube can enter a state in which it is unresponsive, and may require a full reinstallation in order to work properly. 

**Fix:**

In order to properly halt the minikube and restart it, please follow [this document](https://kyma-project.io/docs/root/kyma/#installation-install-kyma-locally-stop-and-restart-kyma-without-reinstalling)

### Kyma-installer is stuck at *ContainerCreating* step

**Description:**
Since release `0.9.0` we have focused on security, which resulted in securing the connection between helm client and server. Because of that, the kyma-installer cannot start, if a set of client-server certificates is not present on the system. 

**Fix:**

A common reason for this, is an error in the user supplied `my-kyma.yaml`, when the user supplies his own image. As of `0.9.0` the `installer.yaml` has 2 `image` fields:

```
image: eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a
image: eu.gcr.io/kyma-project/develop/installer:0fdc80dd
```

Th **second** image is the one that needs to be replaced, not the first.

### Kyma-installer fails with error: `Unable create helm client`

**Description:**

If the kyma-installer is failing with the following error:

```
Unable create helm client. Error: could not read x509 key pair (cert: "/etc/certs/tls.crt", key: "/etc/certs/tls.key"): can't load key pair from cert /etc/certs/tls.crt and key /etc/certs/tls.key: open /etc/certs/tls.crt: no such file or directory
```

It means, you are probably trying to upgrade a pre `0.9.0` release to a newer one. In `0.9.0` we introduced a security feature: TLS connection between **Tiller** and **Helm**. Because of this, the kyma-installer expects a secret to be present in kubernetes, which is generated by our tiller deployment. If during the upgrade you didn't upgrade tiller, this error may happen.

**Fix:**

Upgrade your tiller deployment by calling: `kubectl apply -f https://raw.githubusercontent.com/kyma-project/kyma/{RELEASE_TAG}/installation/resources/tiller.yaml`, where `RELEASE_TAG` is your new desired release. 

## Service mesh

### Can't access console, or other endpoints

**Description:**

All endpoints presented by kyma, are exposed by a gateway. Those endpoints can be seen by calling `kubectl get virtualservice --all-namespaces`.
Receiving `503` errors by accessing any of those endpoints, may mean an error in the gateway exposing them.
This is an error in the istio gateway

**Fix:** 
In the case of a broken gateway, is enough to kill the current gateway pods, which should be recreated, and their configuration renewed. This can be done by calling:
`kubectl delete pod -l app=istio-ingressgateway -n istio-system`

### Istio error during installation

**Description:**

It may happen, that during the installation of kyma one will see the following errors in the kyma-installer error log:
 
```
 Step error:  Details: Helm install error: rpc error: code = Unknown desc = validation failed: [unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3", unable to recognize "": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
```
 
This behaviour is normal and expected. Istio is the first big component being installed, and it may happen, that not all of its CRDs are installed in time, for the next component. In such a case, the installation step is repeated, giving Istio more time for setup, and the error is displayed.

**Fix:**

There is nothing to fix, as the installation is repeated.

**Comment by piotrmsc** [comment]
`Kyma-installer is stuck at ContainerCreating step` and it's fix applies to a flow with using custom installer image(from sources). If this happens from release (w/o modification, there should also be fix described)
In the installation, I would also describe `transport is closing` from helm - missing `--tls` flag or `HELM_HOME` not set.

**Comment by Demonsthere** [comment]
Updated content

**Comment by Demonsthere** [comment]
Update 2

**Comment by Demonsthere** [comment]
Update 3
