### ISSUE TITLE
Admin user doesn't have permissions to manage the ServiceMonitors

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#4074]
**Description**

While testing [this](https://github.com/kyma-project/examples/tree/master/monitoring-custom-metrics) example I encountered the following trouble: 

<img width="475" alt="Screenshot 2019-05-14 at 11 49 07" src="https://user-images.githubusercontent.com/21159554/57690241-7fc3c900-7641-11e9-9fba-4cccebfb758c.png">

We need to update the admin user and allow him to manage all of the resources in the Kyma cluster.

**Comment by kubadz** [comment]
Instead of allowing the admin user to manage all of the resources, we should add appropriate roles for monitoring to the [cluster-users chart templates](https://github.com/kyma-project/kyma/tree/master/resources/core/charts/cluster-users/templates) similarly like it is done for example in [knative-eventing roles](https://github.com/kyma-project/kyma/blob/master/resources/core/charts/cluster-users/templates/clusterroles-knative-eventing.yaml) and add appropriate aggregationRules to kyma roles (kyma-edit, kyma-admin, kyma-view, ...).
