### ISSUE TITLE
We should rotate the certificates for load generator cluster.

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#4136]
**Description**

We are using lentencrypt certificates for Load generator cluster. These certificates are valid for 3 months. We need to rotate them.

**Comment by derberg** [comment]
Adding WIP label
This issue doesn't have enough details to process it

**Comment by nachtmaar** [comment]
The cluster certificate has been created once and now it is expired. See appended picture.
That means we should have an automated way of reissuing a new certificate before the old one gets invalid.

Current Behaviour:
* After 3 months the TLS certificate expires and it is not renewed automatically

Expected Behaviour:
* The load-generating cluster (where grafana is running) should always have a valid TLS certificate.

![Screenshot 2019-12-05 at 10.39.17.png](https://images.zenhubusercontent.com/5cd998c1172c9432dc564e76/38801d2c-f7d7-474b-be85-e11ee829bcd6)

**Comment by nachtmaar** [comment]
I think the certificate is created [here](https://github.com/kyma-project/test-infra/blob/1a928c5ab4d332d28ba6482ae7e832840f42fe3f/prow/scripts/cluster-integration/helpers/install-kyma.sh#L66) using [certbot](
https://github.com/kyma-project/test-infra/blob/074f02bb7693060b582495980e8c2fe08a115775/prow/scripts/cluster-integration/helpers/generate-and-export-letsencrypt-TLS-cert.sh#L32)

**Comment by derberg** [comment]
consider deploying on gardener after Kyma 1.10 release

**Comment by pbochynski** [comment]
We are not going to work on this.
