### ISSUE TITLE
Extended component test for monitoring

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4501]
**Description**
Assure basic functionality of monitoring stack in an automated way:

- Check if all targets are up and healthy
- Check if all alerts are up and healthy

**Reasons**
A non working servicemonitor might indicate non-working component

**Workaround**
Make a port-foward for the prometheus-dashboard and check if all targets are healthy
```
kubectl port-forward -n kyma-system svc/monitoring-prometheus 9090:9090

Go to http://localhost:9090/targets
```

**Comment by shorim** [comment]
**Merged Changes**

For monitoring integration test:
- Check that all targets are healthy
- Check that all rules are healthy
- Refactor HTTP client, so that it would be created only once

For monitoring upgrade test:
- Check that all targets are healthy before and after upgrade. Checking for target with job=istio-ingressgateway is excluded for now, because it is not healthy in release 1.11.1 and this check will be added in the next release
- Check that all rules are healthy before and after upgrade
