### ISSUE TITLE
Document the current SLOs and the used setup

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4544]
**Description**
Finally there are regular performance tests in place and we have some numbers on current performance constraints.
The used setup and the numbers must be documented public.

Leftover of https://github.com/kyma-project/kyma/issues/3456

**Reasons**
Kyma users needs to know the current constraints.

**Goal**
Have a page in public docu listing:
- links to perf results
- links to perf setup
- definition of production environment
- SLOs

**Attachments**
- Documentation of test setup: https://github.com/kyma-project/kyma/tree/master/tests/perf
- Continuous istio test results based on fortio: https://fortio.perf.kyma-project.io/
- Continuous component test results based on k6 and grafana: https://grafana.perf.kyma-project.io/d/ReuNR5Aik/kyma-performance-test-results?orgId=1&from=now%2Fy&to=now%2Fy&var-SHAID=All&var-Measurement=All

**Comment by nachtmaar** [comment]
Here are the numbers for lambdas.
- Please note that the numbers might change with https://github.com/kyma-project/kyma/issues/4370.
- We don't have any tests for function size L and XL yet. See https://github.com/kyma-project/kyma/issues/4368

# Test: Lambda test with blocking CPU code and HPA involved:

Throughput=requests/s=rps
Delay=mean

Function Size S:
Delay: 1.36 s
Throughput: 6,98 rps

Function Size M:
Delay: 326.70 ms
Throughput: 7,02 rps

Numbers taken from [Performance Test Grafana](https://grafana.perf.kyma-project.io/d/ReuNR5Aik/kyma-performance-test-results?orgId=1&from=1562319300354&to=1562319646236&var-SHAID=All&var-Measurement=All&var-component=serverless&var-testname=size-m)

Interpretation of numbers:
- Mean delay is very high: function requests are queued by nodejs server because each [request is blocking for 200ms](https://github.com/kyma-project/kyma/blob/master/tests/perf/prerequisites/serverless/setup.sh#L10)
- Initial delay is very low: between 280-350ms (min and max), note that function itself blocks for 200ms.
- Delay of size M is lower because it has more replicas to handle the requests
- There is no difference in the number of rps between function size S and M. Will be interesting to see if we can get more rps with function size L and XL 

# Test: Lambda-Test without blocking CPU

We will add some numbers then this test is implemented.

Ticket: https://github.com/kyma-project/kyma/issues/4371

**Comment by clebs** [comment]
@hisarbalik still needs to go through the documented SLOs and review that everything is as desired.

**Comment by a-thaler** [comment]
Performance tests are still not running continuously... no point in documenting them properly
