### ISSUE TITLE
GraphQL constraints should support mutations and queries

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#474]
Confirm these statements before you submit the issue:

- [ ] I have searched open and closed issues for duplicates.
- [ ] I have read the contributing guidelines.
---

**Description**

It should be possible to define separate roles for queries and mutations in the GraphQL in order to secure them.

@pbochynski please provide additional input to this if needed :) 

**Reasons**

**Attachments**

**Comment by piotrmsc** [comment]
Add back documentation which was removed here https://github.com/kyma-project/kyma/pull/1594/files

**Comment by piotrmsc** [comment]
For nondeterministic behavior of EnvoyFilter please create issue in the istio

**Comment by piotrmsc** [comment]
Please add test for GraphQL rbac

**Comment by kubadz** [comment]
This task is currently blocked because of higher priority of knative-related tasks. PR #1595 adds the envoy filter enabling securing specific resources in GraphQL, but currently, that will work only for queries. There will be another PR needed to add support for mutations and to make defining separate roles for queries and mutations possible.

**Comment by piotrmsc** [comment]
Closing this issue since we are moving authorization and authentication model to `ui-api-layer` directly witihin https://github.com/kyma-project/kyma/issues/2147. Mentioned issue will bring documentation how to secure any query or mutation or subscription
