### ISSUE TITLE
Support setup of backup as part of installation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4835]
**Description**
Currently the velero chart is not configurable from installer perspective, see also https://github.com/kyma-project/kyma/issues/4755

Assure that it is possible to configure velero with a storage and also to setup a periodic backup job.

Action Items:
- Have the customer facing installer overrides documented
- Have a meaningful default in place so that velero can start without custom config (if not possible, document it transparent)
Have storage configurable with installer overwrites
- Have a periodic backup job configurable with installer overwrites
- Have a default backup configuration in place

**Reasons**
Make backup usable for customers

**Comment by clebs** [comment]
As discussed, the following has been done:
- Create a user friendly Velero installation guide suppporting GCP and Azure -> https://github.com/kyma-project/kyma/pull/4909
- No default configuration will be provided since it is not possible within a storage outside the cluster. A default configuration with an in-cluster storage is possible but does not help in case of a disaster, therefore an installation guide is provided to properly setup backups.
- Backup and restore are already well documented, no further work is required there for now.

**Comment by clebs** [comment]
Blocked by:
https://jira.hybris.com/browse/IDEFIX-2984

No Azure subscription is available to Huskies to test the Azure installation guide.

**Comment by clebs** [comment]
Created follow up ticket to add a tested sample configuration for Azure: #4972
