### ISSUE TITLE
Evaluate Event Bus components resources consumptions

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#4856]
**Description**

In order to reduce the overall resources consumption of initial Kyma provisioning and running acceptance tests, we need to evaluate the resources consumption of Event Bus components including Knative. 

**Note**
- Reach out to @a-thaler and/or @hisarbalik to align how to evaluate the resources and on-going situation.  
- Overall set release theme was that provisioning of a Kyma cluster + running acceptance tests should succeed within 18GB Memory and 3 VCPUs.

**AC**
- Evaluate the requests for the charts.
- Evaluate the acceptance tests requests. 
- Consider all Event Bus components memory and CPU consumptions. 
- Consider all Knative Eventing components memory and CPU consumptions.
- Consider NATSS memory and CPU consumptions
- If there are quick fixes then consider creating a PR or creating separate issues for big ones.
- Document findings per component and test.

**Comment by rakesh-garimella** [comment]
A hint please look into `resourcequotas` and `limitranges`. I think `resoucequotas` does not allow pod to be provisioned if its over all node memory

**Comment by sayanh** [comment]
These are related issues:
https://github.com/kyma-project/kyma/issues/4862
this for KPI definition
https://github.com/kyma-project/kyma/issues/4863
this is the resource optimization epic
https://github.com/kyma-project/kyma/issues/4865
and this is the test creation to measure KPI

**Comment by anishj0shi** [comment]
## Event Bus Resource Configuration

Currently event-bus components have the following resource *limit*

##### Publish Service
- Memory: **32M** and **unbounded cpu resource requested**
##### Subscription Controller
- Memory: **32M** and **unbounded cpu resource requested**

| Action | Observation |
|------|-------------|
|Create a GKE Standard Cluster with 3vCPU and 19.5GB Memory and Kubernetes version: 1.12.8-gke.10 | Cluster Created |
|     Trigger Kyma Installation with the default resource configuration    |      Kyma installation doesn't complete and suspends (in my case) at installing service catalog components as there's insufficient cpu resources available to complete its installation.       |
| Change Cluster configuration to 4vCPUs and 20GB Memory and Retry Kyma installation | cms Component was not scheduled by Kubernetes due to insufficient CPU resources |
| Added one more Node to the Cluster and changed Cluster configuration to 5vCPUs and 25GB Memory and Retry Kyma installation | logging Component was not scheduled by Kubernetes due to insufficient CPU resources |
| Change Cluster configuration to 12vCPUs and 30GB Memory and Retry Kyma installation | Kyma successfully installed |

**Comment by anishj0shi** [comment]
## Bursty traffic results
- Run was mediated via kubectl port-forward(Actual results to be monitored on kyma performance cluster)

cpu peak: *70m*
memory peak: *22.2MiB*

<img width="1591" alt="Screen Shot 2019-08-12 at 1 15 21 PM" src="https://user-images.githubusercontent.com/30645797/62851440-b4f4bb80-bd03-11e9-8fe2-427890b66127.png">
