### ISSUE TITLE
Kyma console UI cannot be accessed after updating the TLS certificate

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#4974]
**Description**
After following the [tutorial](https://kyma-project.io/docs/1.2/components/security/#tutorials-update-tls-certificate) and updating the certificate, I was not able to access the Kyma console UI.

**Kyma Version** : 1.2.2

> **Note **: I added the new certificate to my OSX trust store and verified the same.

**Expected result**
Post certificate update, Kyma console UI is accessible as earlier.

**Actual result**
* Chrome browser shows the error on accessing the console. I have to follow Advance and ignore the errors.
* On providing the login credentials, I get 401. Also verified by @strekm 

**Steps to reproduce**
* Follow the [tutorial](https://kyma-project.io/docs/1.2/components/security/#tutorials-update-tls-certificate) to update the certificate in Kyma console.

**Comment by piotrmsc** [comment]
Root cause of the problem is information of new certificate not being populated to other components that requirem the such as console-backend or apiserver-proxy (for token authentication). Console-backend cannot fetch public keys because it has an old certificate and therefore refuses the call with 401. The infromation is not populated because re creating tls certificate will not inform other conponents. Insetad, update should be done with updated configmap holding the certificate. In case the cluster was deployed without domain and certificate (self signed scenario) the net-global override should be deleted and then update run.

Unforutnately our procedure is broken in the documentation, however, we will not update it. Instead, we will push forward toward automatic cert-management with cert-manager.
