### ISSUE TITLE
Have acceptance tests for Function controller

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5147]
**Description**
We need to have acceptance tests for knative-function-controller.

**AC**
- non-exhaustive:
  * deploy valid function
  * deploy invalid function (including attributes the webhook is supposed to reject)
  * deploy a function to different namespaces, including the one hosting the controller

**Comment by nachtmaar** [comment]
One additional test case I have in mind:
- deploy function with wrong value (e.g. nodejs5 instead of nodejs8) which should be declined by webhook (`config/samples/serverless_v1alpha1_webhook_invalid_function.yaml`

**Comment by antoineco** [comment]
We could source some ideas from https://github.com/triggermesh/knative-local-registry to simplify the management of images, and automatically throw them away at the end of the test.

**Comment by antoineco** [comment]
The linked PR is blocked because we don't have a reliable way to push/pull container images to/from a container registry inside a test suite. This is required to test that a Function can be created, built, and run.

Summary of the issues I'm facing:
1. The container runtime enforces that communications with the container registry are **secure** (TLS), which requires configuration of said runtime on _each host_ to accept a custom CA.
2. There is one exception to the above rule: when the registry is behind a hostname with the `.local` extension (`cluster.local`). However, this also requires _configuring nodes_ to enable resolution of this name by the container runtime.
3. GKE nodes do resove that domain 🎉 However, the pulling of images fails on Kubernetes <1.15 due to a kube-proxy issue (kubernetes/kubernetes#74840)

**Comment by antoineco** [comment]
I worked around 1. and 2. by  adding an entry to the local /etc/hosts file at the beginning of each test, and removing again it at the end.
The code is robust, resilient to panics and other failures, so I believe we can roll with it for now.

The dependency on 3. (Kubernetes 1.15) is still there unfortunately.

**Comment by Abd4llA** [comment]
We need a proposal about creating and using a container registry in the test.

**Comment by michal-hudy** [comment]
Already implemented
