### ISSUE TITLE
Upgrade Event Bus dependencies to Kubernetes 1.15

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#5168]
**Description**

Upgrade Event Bus subscription controller to Kubernetes 1.15 . 

**Notes**

- Coordinated with other components *UPFRONT* regarding merging strategy. 

**AC**

- Subscription controller starts error free on a Kubernetes  1.15 cluster.
- Event bus publish starts error free on a Kubernetes 1.15 cluster.
- Event bus acceptance tests pass on a Kubernetes 1.15 cluster.
- Event bus upgrade tests are passing correctly.

**Comment by marcobebway** [comment]
@montaro, why these [tests](https://github.com/kyma-project/kyma/blob/cc65bfa42a855aa4f70549a460a83a8e6681b86f/components/event-bus/internal/knative/subscription/controller/subscription/reconcile_test.go#L109) were commented out? Please reactivate them and make sure that they are working correctly.

**Comment by marcobebway** [comment]
Moving back to todo, because these [tests](https://github.com/kyma-project/kyma/blob/cc65bfa42a855aa4f70549a460a83a8e6681b86f/components/event-bus/internal/knative/subscription/controller/subscription/reconcile_test.go#L109) were commented by mistake. The tests should be uncommented and verified to be working correctly.

**Comment by derberg** [comment]
Removed from epic https://github.com/kyma-project/kyma/issues/5077 as it is not related

**Comment by montaro** [comment]
Blocked by #5058

**Comment by Abd4llA** [comment]
unstalling

**Comment by anishj0shi** [comment]
event-bus deps are already on 1.15.3
