### ISSUE TITLE
Improve event bus current external SLOs to match Knative Eventing SLOs

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#5173]
**Description**

Currently Event Bus external SLOs are very far from Knative Eventing SLOs.

**AC**

- Event Bus external SLOs are within acceptable variance from Knative Eventing SLOs

**Comment by davyodom** [comment]
As of Kyma 1.4, we have seen that the event-publish-service app is bottlenecking and only allowing about 10 events / second.  This performance can be improved marginally by scaling the number of pods, but does not scale at anything approaching linear.  When looking through the code, it seems likely that the bottleneck is caused by calling the kubernetes api server (http) to get the correct channel for every event without any caching in use (as far as I can tell).  The client-go library being used has an internal default of 5 queries per second which it allows.  The combination of repeated querying and the scarce internal resource of connections to the k8s api server could explain a significant part of the slowness
