### ISSUE TITLE
Improve Asset Store and hCMS documentation

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#5174]
**Description**

Current documentation for Asset Store and hCMS doesn't describe well how to create a service for webhooks. We need to improve that and also add other missing things:
 - Describe webhooks (mutation, validation, metadata) and requirements for services (API, port, etc.) ✅
 - Remove duplicated description of webhooks: 
    - https://github.com/kyma-project/kyma/blob/master/docs/asset-store/06-01-asset.md#validation-and-mutation-webhook-services ✅
    - https://github.com/kyma-project/kyma/blob/master/docs/asset-store/06-03-clusterasset.md#validation-and-mutation-webhook-services ✅
 - Describe `status.reason` types ✅
 - Describe CMS AsyncAPI Service ✅

**Reasons**

Asset Store and hCMS documentation should well describe how to work with these components.

**Comment by mmitoraj** [comment]
- [Application Connector](https://kyma-project.io/docs/components/application-connector/#overview-overview-supported-ap-is)
  - in [this](https://kyma-project.io/docs/components/application-connector/#overview-overview-supported-ap-is) section update info regarding supported specs and their version: OpenAPI 2.0, AsyncAPI (all version because we have the Converter) and OData (all versions)
  - in [this](https://kyma-project.io/docs/components/application-connector/#details-application-registry) section change `Docs topic` to `DocsTopic`
- HCMS or/and Console
  - add a document about supported specifications and their versions
  - in the doc add info what sources (from the DocsTopis CR) we support and advise that we can save all files but in the UI we support only specific versions
  - create a diagram showing what sources we support 
  - mapping - which spec displays in which tab in the UI
  - Markdown - documentation; AsyncAPI - events; OpenAPI and OData - API; Headless CMS supports raw docu, messaging docu (AsyncAPI) and API docu (OpenAPI and OData)
  - link to official OpenAPI, AsyncAPI, OData documentations
  - formats: OData - `.xml`, OpenAPI -  `.yaml` or `.json`, AsyncAPI - `.yaml` or `.json`
  - add config docs for converter and validator
  - write in a way that the documentation does not need to be changed once HeadlessCMS becomes as an independent project out of Kyma  - Console vs Headless CMS

**Comment by mmitoraj** [comment]
Also, think about [this](https://kyma-project.io/docs/components/headless-cms/#details-markdown-documents) doc and its place in the whole structure - should it stay in HCMS or be moved to the Console documentation?

**Comment by kazydek** [comment]
This issue relates to #https://github.com/kyma-project/kyma/issues/5467.
