### ISSUE TITLE
cni network plugin not happy with names > 63 chars

### ISSUE THREAD

**Issue by Morriz** [kyma-project/kyma#5185]
When trying to connect Google as app provider I get:

Warning  FailedCreatePodSandBox  47m   kubelet, gke-otomi-cloud-cpu4-mem15-81142c2d-kpf5  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "a7cfda6f28ff445522ef4165e2802054263da04aa9da06409cf585e2722e4405" network for pod "gcp-service-broker-docu-checker-n75wg": NetworkPlugin cni failed to set up pod "gcp-service-broker-docu-checker-n75wg_test" network: error with field Metadata.Labels (value) = 'hb-gcp-service-broker-default-7e7c2b0d-b5f4-11e9-bb1c-docu-checker' (must be no more than 63 characters)

**Comment by Demonsthere** [comment]
Hi there,
The 63 character limit is a [well known convention](https://stackoverflow.com/questions/32290167/what-is-the-maximum-length-of-a-dns-name#32294443) and limitation for DNS naming. It has nothing to do with kyma in general, as it is defined by [RFC-1123](https://tools.ietf.org/html/rfc1123)

**Comment by Morriz** [comment]
Fine, can the name not be made too long in the chart then? They exist as resource in your repo so under control it seems

**Comment by m-wcislo** [comment]
@Demonsthere it is not a problem of DN but rather k8s resource name limit, that is often set to 63. Actually I have the same problem for Azure broker.

To be more specific, this occurs when creating instance of broker, and -doc-checker pod fails on creation step. By checking the name seems the problem is with service account name, formed as 
```
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ template "fullname" . }}-docu-checker
```
with helper defining fullname as
```
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```
so we have max 63 chars + -docu-checker which breaks validation. In original azure broker chart they are using mostly 
```
metadata:
  name: {{ template "fullname" . }}
```
which works fine due to trunc mechanism.

I didn't dig into how release name is generated on Kyma side, but seems its length is env specific, that is why I suppose it mostly works, but at least to my understanding this looks like a problem with azure-service-broker chart in https://github.com/kyma-project/addons.

**Comment by m-wcislo** [comment]
@Morriz google service broker chart was changed in later versions than 0.6 and it is not using docu-checker anymore. You can try it out by going to Add-Ons config and add url https://github.com/kyma-project/addons/releases/download/0.7.0, but not sure if your Kyma and addons versions are fully compatible.
