### ISSUE TITLE
Expose Knative Function using API

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#5582]
Currently Functions created by the function controller are getting exposed using the default knative mechanisms. We need to enable exposing using api-objects in order to fully integrate into kyma.

**Comment by michal-hudy** [comment]
To achieve that few things need to be done:
 - Internal functions need to point to the mesh (#6867)
 - Function controller should create only internal functions (#5580)
 - API rule should point to function placeholder service that will be handled by Istio
 - CBS should filter out revision and private function services

Thanks to that we don't need to modify API controller and API UI will be compatible with functions.

**Comment by michal-hudy** [comment]
Generally, it works, but I noticed one issue:
![image.png](https://images.zenhubusercontent.com/5b85435e6092773c0b8551d0/ee5e2972-3ed7-49dd-8213-e8ecc7a5893b)

Such a label shouldn't be visible on `function` CR. Yes, if someone explicitly set this value it should override the default that we are configuring on `kservice`, but by default, we should set any label on `Function` CR, especially label that is not possible to remove.

**Comment by michal-hudy** [comment]
@magicmatatjahu Generally, it works, but I noticed one issue.

Label `serving.knative.dev/visibility: cluster-local` should be set by Function Controller on `kservice`, it shouldn't be visible on `Function` CR. It is something that can confuse the user because there is a label, so he can think that as he will remove that label, the lambda will be public. Another problem is that it is not possible to remove that label from `function` CR.

So, label `serving.knative.dev/visibility: cluster-local` should be set only on `kservice` not `function` CR.

**Comment by michal-hudy** [comment]
@kazydek we should also remove the sentence that says the label is set on `function` CR from https://kyma-project.io/docs/master/components/serverless-v2/#details-exposing-lambdas
