### ISSUE TITLE
[PoC] Refactor Kyma cluster installation docs

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/kyma#5591]
**Description**

Most of the steps in the Kyma cluster installation on GKE and AKS are the same. Check if it is possible to get rid of the duplicated content and write one instruction with toggles only in particular steps which actually differ.

Investigate if we can:
- unify the Kyma cluster installation guidelines for GKE, AKS, and Gardener
- add the instruction on how to install Kyma with your own domain as a step at the end of the cluster installation (patch)
- move GCP Marketplace installation to a separate doc

**Reasons**

Duplicated content is more difficult to maintain. We want to have more user-friendly docs.

**Comment by mmitoraj** [comment]
- Kyma installation on all three providers (GKE, AKS, and Gardener) was successful.
- The guidelines were refactored and only the steps that actually have tabs per provider (**Prerequisites** and **Prepare the cluster**).
- Kyma installation through the GCP Marketplace was moved to a separate doc
- Kyma Installation with your own domain as a step at the end of the cluster installation (patch) is not possible at the moment. @michal-hudy is to create an issue.

**Comment by mmitoraj** [comment]
Preview: https://deploy-preview-442--kyma-project.netlify.com/docs/refactor-installation-docs/root/kyma/#installation-install-kyma-on-a-cluster

**Comment by mszostok** [comment]
I've checked the new installation docs. IMO they are much clearer and more precise I now I can see what is really different between given hyperscaler. LGTM 👍  Below I've described two minor suggestion

---
**Proposed enhancement**
When you switch one tab in a given section then other tabs are also automatically switched.

**Current problem**
When I'm reading the installation docs then I have dedicated sections for different hyperscalers. When I'm switching e.g. to GCP then all other sections should be also changed to GCP, thanks to that I have installation docs in one specified context. Right now I need to do that for each section manually, and user can easily forget about that and copy wrong commands.

Check the desired behavior here:
https://cloud.google.com/storage/docs/access-control/making-data-public
_(when you change tab in one section then it's automatically adjusted in other places)_

---
About the 
> Kyma Installation with your own domain as a step at the end of the cluster installation (patch) is not possible at the moment. @michal-hudy is to create an issue.

Ok, so we do not want to touch that part at the moment?
IMO we can at least extract the **Install Kyma** section from GKE and AKS tabs because they are exactly the same:
https://deploy-preview-442--kyma-project.netlify.com/docs/refactor-installation-docs/root/kyma#installation-use-your-own-domain--provider-domain--gke--install-kyma

**Comment by mmitoraj** [comment]
Thank you @mszostok for your review! 

The first suggestion looks like a great feature. @magicmatatjahu is it doable? 

Regarding installing Kyma with your own domain, I will at least try to get rid of the duplicated steps as you suggested.

**Comment by mmitoraj** [comment]
I created a feature request for the automatic tab adjustment - https://github.com/kyma-project/website/issues/443.

**Comment by mmitoraj** [comment]
After voting on the public Kyma Slack [channel](https://kyma-community.slack.com/archives/CD2HJ0E78/p1568721087011100) the new version of the installation documentation was accepted by the majority. Updating the documentation will be continued in the same issue.
