### ISSUE TITLE
Reduce the number of requests to API server

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#6036]
**Description**

Based on metrics provided by (https://github.com/kyma-project/kyma/issues/6035) number of requests to API server should be reduced to an absolute minimum.

AC:
 - Identified components/tests are generating fewer requests (calculate the improvements)
 - Based on fixes create a document that will describe best practices for Kyma developers

**Reasons**

As we already have a list of components that are making too many requests to API server we need to improve them. Thanks to that Kyma will be a lighter solution and probably performance will be also improved.

**Comment by derberg** [comment]
@michal-hudy please specify exactly what and in which component things have to be improved and provide data that proves how we know it is a big problem. At the moment it is impossible to decide who can execute

**Comment by adamwalach** [comment]
This issue is killing our long-leaving-cluster - weekly. The api-server is hammered down by the traffic. Basically we can't run any kubectl queries.
We increased number of nodes from 3 to 6 and it improved situation a bit. 
These are charts describing api load on a 6 node weekly cluster:
<img width="1362" alt="Screen Shot 2019-11-13 at 12 22 32" src="https://user-images.githubusercontent.com/8530211/68760034-3ca6da80-0611-11ea-840b-b7b4ed721c67.png">


<img width="1342" alt="Screen Shot 2019-11-13 at 12 22 45" src="https://user-images.githubusercontent.com/8530211/68760063-4d575080-0611-11ea-936a-0fb1c8882196.png">

**Comment by adamwalach** [comment]
By suggestion from GCP support we changed type of weekly and nightly clusters to [regional](https://cloud.google.com/kubernetes-engine/docs/concepts/regional-clusters). Since we did the change the clusters are more stable, and we could not observe any issue with api-server not being available.

**Comment by kasiakepka** [comment]
Looking at the AC I believe we can't assume that this issue can be closed.
Goats already implemented [dashboards](https://github.com/kyma-project/kyma/pull/6079) that help us to measure potential improvements.
@piotrmsc did you notice any improvements in the number of requests to API?

If we want to create "document that will describe best practices for Kyma developers" I think we should push this issue further. Can POs take care of that?

**Comment by kasiakepka** [comment]
On SIG Quality meeting it was agreed to close the issue and create separate one focused on Mixer (the biggest contributor when it comes to the number of requests to the APiserver).
Potential Mixer improvements are documented here: https://github.com/kyma-project/kyma/issues/6348
