### ISSUE TITLE
Guidance document is missing for handling any issues encountered during 1.6 upgrade.

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6157]
**Description**
Kyma 1.6 has major changes with regard to the Service catalog. In case there are some orphan resources related to the service catalog, the upgrade process can fail and becomes difficult to recover.

**Expected result**

Provide a step-by-step guide about possible actions to take while encountering upgrade issues in 1.6

**Actual result**

Currently, there is no such documentation. Working directly with Service catalog experts from the Kyma team (their help is highly appreciated). Having a guide would help scale better.

**Comment by mszostok** [comment]
We need to create the migration guide for 1.6 release and merge it to https://github.com/kyma-project/kyma/tree/release-1.6 branch. Similar as we had between 1.4-1.5: https://github.com/kyma-project/kyma/blob/release-1.5/docs/migration-guides/1.3-1.4.md


**In this migration guide we should:**
- state that the PV should never be removed because you will lose your data and backups will be not possible. 
- Create a sanity check script which will check that non of the Service Catalog resources are not in unfinished/deleted stated. (check for deletion timestamp and for inprogress operations).
- add info how to execute the sanity check script
- state that upgrade should be done only when the service catalog state is accepted by the sanity check

**Comment by mszostok** [comment]
update also migration guide on Service Catalog repo: https://github.com/kubernetes-sigs/service-catalog/blob/master/docs/migration-apiserver-to-crds.md

- add there info about sanity check
- add info about restoring the data from pvc in the **Rollback** section
