### ISSUE TITLE
Services do not show up in the Catalog after binding an application with namespace

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6168]
**Description**

After binding an application (commerce cloud) with the namespace, the services (Commerce Events and OCC APIs) are not available in the Catalog of the bound namespace.

**Expected result**

The events and APIs registered with the application are available in the catalog of the bound namespace.

**Actual result**

The Catalog --> Services Section of the namespace did not have any services.

**Steps to reproduce**

This issue occurs randomly. Not easy to reproduce. Unfortunately, it occurred when working with the customer to set up the commerce Kyma connectivity. This gives a bad impression to the users that Kyma is not mature enough.
 
**Troubleshooting**

Restarting the `application-broker` pod solved the issue. In general, this is a generic issue with all the controllers in Kyma where they can randomly start misbehaving. This should be possibly solved once for all.

**Comment by abbi-gaurav** [comment]
Raising the priority to critical. This issue is being faced by other teams also who are preparing for Tech-ed BLR.

**Comment by PK85** [comment]
what Kyma version do you use?

**Comment by abbi-gaurav** [comment]
Kyma version 1.6

Both times it happened on someone else's cluster to which I did not have access. In the app broker, only logs were from the health checks. (No errors or any resource handling)

**Comment by PK85** [comment]
Ok, team, we need to implement same sanity check for AppBroker as we have in SBUController.

**Comment by ksputo** [comment]
Removing critial label:
There is [Service Catalog test](https://github.com/kyma-project/kyma/blob/master/tests/service-catalog/test/binding_usage_test.go) which verifies the described scenario - it creates application, application mapping and check if service classes are created properly. We've been monitoring weekly and nightly clusters for whole week and there are no signs of failure caused by service classes not being available after binding. However, as @PK85 said, we are implementing a sanity check which will make application broker restart automatically if the described procedure fails.

**Comment by PK85** [comment]
everything great, but why it is in accepted column when that version is not used in Kyma, see:
https://github.com/kyma-project/kyma/blob/master/resources/application-connector/values.yaml#L61

**Comment by ksputo** [comment]
@PK85 my bad, now covered in #6386
