### ISSUE TITLE
POC: Make Service Catalog awaiting time reasonable

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#6320]
**Description**

We need to assure that user can create ServiceInstance, ServiceBinding and ServiceBindingUsage at the same time and ServiceCatalog will give proper time to accomplish all the operations, for example in 24hours.

_Assumption: ServiceBroker is already registered and ServiceClass names/ids are known and static._

**Reasons**

This enhancement will open the way for automation. For example single helm chart which activates Services and make use of them in Lambda.

**AC**
- make sure that creation of SB pointing to not existing SI will work (I think reconcile on failed SB will do a job)
- make sure that creation of  SBU which points to not existing SB_name and App/lambda_name will work (I think reconcile on failed SBU will do a job)
- find how to configure time to be ready per SI,SB,SBU and pickup/document reasonable values like hours (6,12,24hours)
- create an integration test (could be with shorter timeouts in ServiceCatalog)
- documentation with summary and estimation about all implementations that needs to be done in the next release 1.10

**Comment by mszostok** [comment]
**Hints:**

Consider pinging the ServiceBinding when the ServiceInstance is done.
In SBU think about having informers for the ServiceBinding.

**Comment by jasiu001** [comment]
**ServiceCatalog - ServiceBinding**
- If SB is in the `failed` state each informer synchronization will put this resource to the queue and reconciliation for this resource is processed. Delay of time duration for informer synchronization is set in chart values [file](https://github.com/kubernetes-sigs/service-catalog/blob/master/charts/catalog/values.yaml#L63) (default values is 5 min). The resource is removed constantly from a queue when achieving ready/true status. 

Below test was made for: 1 controller worker, 0 `maxRetries` value for the controller and setting synchronization time to one minute, you can see reconciliation for SB is made each minute:
```
I1217 08:20:44.845061       1 controller_binding.go:171] ServiceBinding "default/test-binding" v6317: beginning to process resourceVersion: 6317
I1217 08:21:43.943260       1 controller_binding.go:171] ServiceBinding "default/test-binding" v6317: beginning to process resourceVersion: 6317
I1217 08:22:43.974794       1 controller_binding.go:171] ServiceBinding "default/test-binding" v6317: beginning to process resourceVersion: 6317
I1217 08:23:43.347174       1 controller_binding.go:171] ServiceBinding "default/test-binding" v7305: beginning to process resourceVersion: 7305
```

(The longest period for the test was made for 1h)

- Removing ServiceInstance if ServiceBinding still exists is impossible, SI got `DeprovisionBlockedByExistingCredentials` status and cannot be removed until SB will be removed. Reconciliation for SB after removing SI is not necessary. 

- Simple solution [#1](https://github.com/jasiu001/service-catalog/blob/binding-trigger/pkg/controller/controller_instance.go#L2996) can reduce the time of reconciliation for SB when SI appears in ready/true state. When SI reconciliation is finished with success (sync/async), SB annotation is updated what causes instant SB reconciliation.

***Problem with integration test***
To write integration tests, you need to consider two emerging problems:
- `fakeClient` used in the controller integration test has an issue, it puts resources with ready/false status without any delay time, which means for these resources reconciliation is made a hundred times per second. This means you can't get a stable failed status to test the above solution [#1](https://github.com/jasiu001/service-catalog/blob/binding-trigger/pkg/controller/controller_instance.go#L2996).
- Values such as the maximum number of repetitions are permanently entered in the controller, which means that the e2e test would take a minimum of 80sec.

**SC - ServiceBindingUsage**
- Similar to SB controller, if SBU is in the `failed` status, the informer will put those resources to the queue during synchronization. The delay in time duration for informer synchronization is hardcoded (default value is 30 minutes). After changing the delay time to 1 minute, it can observe the described behavior:
```
{"level":"info","log":{"message":"new add event with key \"default/deploy-redis-client\" triggered","service":"controller:service-binding-usage","time":"2019-12-17T08:49:29.76Z"}}
{"level":"info","log":{"message":"new update event with key \"default/deploy-redis-client\" triggered. Updated object: default/deploy-redis-client","service":"controller:service-binding-usage","time":"2019-12-17T08:50:29.609Z"}}
{"level":"info","log":{"message":"new update event with key \"default/deploy-redis-client\" triggered. Updated object: default/deploy-redis-client","service":"controller:service-binding-usage","time":"2019-12-17T08:51:29.636Z"}}
{"level":"info","log":{"message":"new update event with key \"default/deploy-redis-client\" triggered. Updated object: default/deploy-redis-client","service":"controller:service-binding-usage","time":"2019-12-17T08:52:29.657Z"}}
{"level":"info","log":{"message":"new update event with key \"default/deploy-redis-client\" triggered. Updated object: default/deploy-redis-client","service":"controller:service-binding-usage","time":"2019-12-17T08:53:29.594Z"}}
{"level":"info","log":{"message":"new update event with key \"default/deploy-redis-client\" triggered. Updated object: default/deploy-redis-client","service":"controller:service-binding-usage","time":"2019-12-17T08:54:29.62Z"}}
{"level":"info","log":{"message":"new update event with key \"default/deploy-redis-client\" triggered. Updated object: default/deploy-redis-client","service":"controller:service-binding-usage","time":"2019-12-17T08:55:29.462Z"}}
```
- Removing ServiceBinding automatically deletes ServiceBindingUsage. Reconciliation for SBU after removing SB is not necessary.  
- Solution [#2](https://github.com/jasiu001/kyma/blob/sbu-trigger/components/service-binding-usage-controller/internal/controller/controller.go#L205) can reduce the time of reconciliation for SBU. The controller listens of any update SB action, if the action occurs, SBU `spec.ReprocessRequest` is updated what causes instant reconciliation.
- Creation of informers that will listen for all elements belonging to `UsageKind` (like deployment, function) is difficult to implement. Informer synchronization can solve the problem when SBU is created without existing `usageKind`, the problem is when `usageKind` is removed for ready/true SBU. In this case SBU will stay in ready/true status even if e.g. connected deployment does not exist anymore. Solution [#3](https://github.com/jasiu001/kyma/blob/sbu-trigger/components/service-binding-usage-controller/internal/controller/guard.go) is a worker which trigger each ready/true SBU to reconcile again. 
- Integration tests share the same problems like ServiceCatalog, fake client and hardcoded retry amount.

The solution [#3](https://github.com/jasiu001/kyma/blob/sbu-trigger/components/service-binding-usage-controller/internal/controller/guard.go) is tested but has some shortcomings: 
- removing SBU key from the list if SBU was delete
- conditions which SBU should be reconciled (maybe for each SBU `usageKind` should be checked if exist)
- tests

It requires some extra work time (from 3 to 8 story points), other solutions except integration tests (which require consideration or repair of the `fakeClient`) are ready to use.

**Comment by polskikiel** [comment]
The solutions that you provided are good, IMO the first two propositions are the best:
1. Annotate SB when SI is ready - https://github.com/jasiu001/service-catalog/blob/binding-trigger/pkg/controller/controller_instance.go#L2996
2. Watch SB in SBU controller and reconcile SBU if SB is ready  - https://github.com/jasiu001/kyma/blob/sbu-trigger/components/service-binding-usage-controller/internal/controller/controller.go#L205

3. The guard from solution nr [3](https://github.com/jasiu001/kyma/blob/sbu-trigger/components/service-binding-usage-controller/internal/controller/guard.go) seems to me like a more complex solution, then solution nr 2 and provides us the same feature.

I think we should consider that repair of the `fakeClient` that you mentioned, to not be blocked in the future.
