### ISSUE TITLE
Service management components upgrade time without changes must be reasonable and short 

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#6322]
**Description**

Helm upgrade without input parameters and chart changes should be as much as possible short, ideally 0 seconds.

**Reasons**

Updating Kyma (for example adding one new module like compass) without any changes takes around 10 minutes. Service management components take significant amount of time.

**AC**
- find and eliminate unnecessary actions and/or steps when upgrading components
- only 1) overrides changes,  and 2) chart modifications should restarts components
- investigate certificate/secret rotation (casue right now we are doing that in every upgrade action)
- think how to add a metric that will show how long upgrade takes

**Components**

- ApplicationBroker
- HelmBroker
- ServiceBindingUsageController
- ServiceCatalog
- PodPresetController

**Comment by mszostok** [comment]
TIMEBOXED: 13SP

**Comment by ksputo** [comment]
Summary of investigation done during this task:

The helm client used in Kyma installer needs to render all the charts for each component first and then it creates a [ConfigMap describing Helm Release](http://technosophos.com/2017/03/23/how-helm-uses-configmaps-to-store-data.html). Inside the ConfigMap there is  After that the comparison is made - only if the newly created Release differs from the previous one pods are restarted. If there is no difference, all the pods from deployment remain untouched. Considering the case described in the issue - the time consumed by the upgrade process does not depend on changes made/not made in any of charts. This leads to a conclusion that AC "only 1) overrides changes, and 2) chart modifications should restarts components" is always true.

I have checked all service management components for possible upgrade time optimisation by first checking which components do change on upgrade. This was done by applying a proper label to trigger update and watching resources of interest on cluster with command `kubectl label installation/kyma-installation action=install`:

| **Component**                     | **Restarts after upgrade?** |
|-------------------------------|-------------------------------------|
| ApplicationBroker             | NO                                  |
| HelmBroker                    | NO                                  |
| ServiceBindingUsageController | NO                                  |
| ServiceCatalog                | YES                                 |
| PodPresetController           | YES                                 |

In both cases restarts are necessary, because we are generating CA certificates in each Webhook. The possible workaround could be using an external tool to manage certificates (like cert-manager), but it won't change the upgrade time in a significant way - e.g. restarting cluster-essentials-pod-preset-webhook took between 3 and 5 seconds while the whole installation step took 49.5s (details below). However the service-catalog-webhook fails on every upgrade with CrashLoopBackoff error and then restarts again:
<img width="1440" alt="Screenshot 2020-01-13 at 09 02 11" src="https://user-images.githubusercontent.com/26189888/72240196-ad537e80-35e3-11ea-8694-8a10c8fa773c.png">

It crashed with an error: `Readiness probe failed: Get http://10.52.3.55:15020/healthz/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)` which is related with [istio](https://github.com/istio/istio/issues/12653) - setting longer `global.proxy.readinessInitialDelaySeconds` parameter seems to fix the problem, but needs to be consulted with team responsible for networking and istio.

Last but not least, the metrics proposal was created: #6695 - using kyma-operator image from this PR allows to log time consumed by each step of installation/upgrade.

**Comment by ksputo** [comment]
Summary for metrics-related AC as a follow-up:

Currently we are not collecting information about installation time of Kyma components. To achieve that, a slight modification is needed in the installer. Here is a minimal example draft: #6695 

After building the installer with image from this PR and installing Kyma, we could use those logs along with GCP tools to collect those numbers from clusters where Kyma installation and updates are performed. Another minimal example thanks to @adamwalach , just to start with something if someone wants to reproduce it:
**Prerequisites:**
- Cluster with Kyma installed using pre-build kyma-operator from #6695 - just follow the [docs](https://kyma-project.io/docs/master#installation-use-your-own-kyma-installer-image).

**Steps:**
1. Create Sink in Logs Router on GCP with query:
```
resource.type="k8s_container"
resource.labels.cluster_name="{YOUR_CLUSTER_NAME}"
resource.labels.namespace_name="kyma-installer"
resource.labels.container_name="kyma-installer-container"
"...DONE!, "
```

![Screenshot 2020-02-05 at 13 59 15](https://user-images.githubusercontent.com/26189888/73844012-051a8980-4820-11ea-97a6-a9f5c32d89f7.png)


This query filters out logs from kyma-installer when a single component finishes installing.

2. Using BigQuery on GCP, run an example query:
```
SELECT
      CAST(REGEXP_EXTRACT(textPayload, r'component(.*)...DONE') AS string) AS step_name,
      CAST(REGEXP_EXTRACT(textPayload, r"(\d+\.\d+)") AS float64) AS step_time
FROM `{YOUR_GCP_PROJECT_NAME}.components_installation_time.stderr`
```

![Screenshot 2020-02-05 at 14 03 28](https://user-images.githubusercontent.com/26189888/73844161-50cd3300-4820-11ea-8d57-ecfb5a431b97.png)

Extracting component name and time from a single log line allows to aggregate installation/upgrade time from Kyma installer. It can be forwarded to Data Studio tool to create some charts or other visualisation. The last thing to consider is how to actually process the data - like counting the mean value (and handling possible broken data samples in case of mean value) or proposing any other reasonable indicator.
