### ISSUE TITLE
Enable Service Manager integration as a new installation module

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#6325]
**Description**
If credentials passed as a Installer overrides module should install and configure Service Manager.

**AC**
- provide a new module in installation that installs service-broker-proxy and provide a way to pass credentials
- find a way for waiting when ServiceManager offering is ready
- add additional installation yaml to Kyma with that module enabled + ServiceManager module in
- add new component and prow pipeline for releasing

**Draft PR**
- https://github.com/kyma-project/kyma/pull/6223

**Comment by mszostok** [comment]
Update:

After discussion with Florian we confirmed that we are not able to test if SM proxy is working properly. Because of that, the best option is to just install the proxy and then in uaa-activator wait for the XSUAA service class.

Additionally, there is an issue https://github.com/kyma-incubator/compass/issues/399 for providing a way for specifying the list of installed components. As a result, we do not have to have the dedicated installation YAML as we will be able to pass the list of components when invoking the provisioning API.


Those AC are not still valid:
- ~find a way for waiting when ServiceManager offering is ready~
- ~add new component and prow pipeline for releasing~
- ~add additional installation yaml to Kyma with that module enabled + ServiceManager module in~

AC: 
- provide a new module in the installation that installs service-broker-proxy and provide a way to pass credentials

**Comment by mszostok** [comment]
Discussion:
> Question: Should we add the istio rbac for Service Manager brokers (ServiceRole, ServiceRoleBinding) in the same way as we have for e.g. Helm Broker

Answer: Right now we are not adding any istio rbac. The URL for Service Manager broker is public and in general available from the internet. The endpoint is secured with basic auth. Setting the internal istio rbac in the cluster does not make any sense.
