### ISSUE TITLE
Gardener installation docs use the Kyma CLI 

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#6353]
**Description**
The Kyma CLI is now the standard for installing Kyma and is able provision a gardener cluster and install kyma on top. Therefore we want to update the Kyma Docs on how to install Kyma on Gardener to use the CLI.

**Reasons**
- Get rid of old scripts and docu
- Standarize the CLI

**Comment by bszwarc** [comment]
What needs to be changed/ investigated: 

Installation docu: https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster 
What should be changed:

[Prerequisites](https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster-prerequisites):  
- Gardener account *NOT* seed cluster

[Prepare the cluster](https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster-prerequisites)
- Instead of describing how to create a secret in the Gardener UI, maybe we can use [gardenerctl](https://github.com/gardener/gardenctl) for that.  Here are examples of basic usage: https://github.com/gardener/gardenctl#examples-of-basic-usage 
- Provision an AKS or GKE cluster through Gardener using Kyma CLI.

[Install Kyma](https://kyma-project.io/docs/#installation-install-kyma-on-a-cluster-install-kyma) 
- Install Kyma on the cluster using CLI
