### ISSUE TITLE
Validation of API / event specifications

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#6576]
**Description**

Currently, the support of API / Event specifications across different Kyma components is inconsistent and limited. Because of that, we investigated which components support which versions and formats of specifications and came with proposition of how the goto specifications' support could look like. For details see attached document with results of the investigation.

**Reasons**

Consistent support and validation of API / event specifications would allow us to:
- Warn user early about invalid input
- Avoid pushing invalid data through many different components just to return error because one of them doesn't support it
- Avoid the situation where even though most components support specific data, said data would be rejected early because of too restrictive validation

**Attachments**

[API / event specifications support proposal](https://github.com/kyma-incubator/compass/blob/master/docs/architecture/api-specs-support.md)

**Comment by derberg** [comment]
@tgorgol great investigation!
2 comments from my side:
- add to 2nd table, first column about rendering info that all the UI components by default also do validation because to render elements they need to parse them and parsers have validators, only for AsyncAPI and OpenAPI components you have a parameter that allows to switch off/on errors found by validator in the UI
- in next months there is no plan to add extension services to rafter for conversion and validation of OpenAPI and ODATA, so you have AsyncAPI covered only for now

**Comment by PK85** [comment]
Closing due to long inactivity.
