### ISSUE TITLE
Validate Knative Metrics PoC

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6656]
**Description**

In order to figure out where Knative Eventing is standing with regards to metrics compared to Kyma, we need to run a PoC with following deliverables
1. Validate the feasibility of integrating Knative metrics with Kyma prometheus wrt the Knative Eventing mesh alpha architecture.
1. Review existing Knative metrics of:
    - Broker
    - Trigger and trigger filters
    - In Memory Channel
    - NATSS Channel
1. Compare between Event Bus metrics and Knative, highlight missing ones.
1. Propose next steps and needed work to replace Event Bus with Knative Eventing mesh wrt metrics.

**AC**
1. Questions and requirements stated above are documented in the issue

**Comment by antoineco** [comment]
ℹ️ **Work in progress**

---

## Event Bus metrics

### Subscription controller

_TODO_

### NATSS Channel

The controller and dispatcher both expose only default [controller metrics](https://github.com/knative/eventing/blob/release-0.10/vendor/knative.dev/pkg/controller/stats_reporter.go#L55) from `pkg/controller`.

General metrics spec for Channels are documented at [eventing/docs/spec/channel](https://github.com/knative/eventing/blob/master/docs/spec/channel.md#metrics), but currently not implemented.

## Event Mesh metrics

### Broker (ingress) / Trigger (filter)

Documented at [eventing/docs/metrics](https://github.com/knative/eventing/blob/master/docs/metrics.md#metrics). The information is up-to-date and matches my observations.

### HTTP Event source

Default source metrics only. Identical to [core sources](https://github.com/knative/eventing/blob/master/docs/metrics.md#sources).

**Comment by antoineco** [comment]
## Comparison

The only thing missing from the new Event Mesh would be the readiness metrics currently exposed by our very own _Subscription controller_. However, I would argue that we should not try to provide an equivalent because
1. Knative controllers manage a lot of resources, it may not be realistic to expect them to expose a readiness Boolean for each and every managed API object (we can ask them what they think about it).
2. Telemetry should, in my opinion, provide measurements (e.g. number of ready vs. number of notReady, ...), not expose monitoring data for individual objects.
