### ISSUE TITLE
Event-Bus Subscription Controller restarts frequently

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#6753]
On Testing Kyma-version 1.9.0-rc1. Event Bus Subscription Controller restarts frequently. 

**POD STATE**
```
    State:          Running
      Started:      Thu, 02 Jan 2020 10:30:07 +0100
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Thu, 02 Jan 2020 10:12:47 +0100
      Finished:     Thu, 02 Jan 2020 10:30:06 +0100
    Ready:          True
```

Not sure if related, But Subscription Controller also logs the following:
```
event-bus-subscription-controller-6698767f9f-r2gnc subscription-controller W0102 09:30:05.355396       1 reflector.go:302] 
k8s.io/client-go/informers/factory.go:133: watch of *v1.ConfigMap ended with: 
too old resource version: 2208795 (2210508)
```

**Comment by antoineco** [comment]
Here's the evolution of the heap size over a 10min period from a pprof execution trace. The heap size grows gradually from **9MiB** to **19MiB** (the memory limit of the container is **32MiB**)

![image](https://user-images.githubusercontent.com/3299086/71677837-11747800-2d84-11ea-9387-46bb3b2f6a84.png)

At a later point, I captured a second execution trace for 3min, and noticed the heap size decreasing back from **25MiB** to **9MiB**. The container was nevertheless OOMKilled about 2 min later.

![image](https://user-images.githubusercontent.com/3299086/71680056-65ce2680-2d89-11ea-94db-e59a59f480d9.png)

First of all, Knative's shared main causes _all_ ConfigMaps inside the `kyma-system` namespace to be cached by a ConfigMap watcher. This represents a total usage (inuse_space) of only **2MiB** at the time of the capture, but I observed values as high as **6MiB** in other captures.

<img src="https://user-images.githubusercontent.com/3299086/71678723-189c8580-2d86-11ea-82d9-ab719ef3748a.png" height="200px" />

Our second biggest memory consumer is the Prometheus exporter, with also roughly **2MiB** (inuse_space). This number seems to remain stable.

<img src="https://user-images.githubusercontent.com/3299086/71679038-e8091b80-2d86-11ea-9459-dd71e69dc7a8.png" height="200px" />

**Comment by antoineco** [comment]
Just like I expected, the `alloc_space` pprof sample shows that a fairly large portion of memory allocations can be attributed to the ConfigMap informer due to caching and de-serialization.

![image](https://user-images.githubusercontent.com/3299086/71681907-4e456c80-2d8e-11ea-9756-f697500b7e98.png)

I made 2 experiments, both leading to an absence of process termination for 30 straight minutes:

**Increase the memory limit from 32MiB to 48MiB**

This seems enough to accommodate the 86 ConfigMaps as well as regular cache refreshes and their associated de-serialization operations.

**Set SYSTEM_NAMESPACE value to "knative-eventing"**

Because we are only interested in Knative ConfigMaps (config-logging/observability), it is more reasonable to point the ConfigMap watcher at a namespace that contains only Knative related configurations. Besides, there is absolutely no reason to maintain copies of those ConfigMaps in multiple namespaces.
