### ISSUE TITLE
Deprovisoning an addon fails

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6814]
**Description**
 I have created a new addon. https://github.com/abbi-gaurav/xf-addons/tree/generic-addon/generic-addon.

This addon gets provisioned successfully. However, on deprovisioning, I see the following errors and it fails to deprovision.

```
Warning  DeprovisionCallFailed    17s (x12 over 38s)  service-catalog-controller-manager  Deprovision call failed: deprovisioning failed on error: while deleting helm release "hb-generic-connector-default-0101db46-0974-46d4-94d9-": while deleting release name: [hb-generic-connector-default-0101db46-0974-46d4-94d9-]: rpc error: code = Unknown desc = invalid release name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 5
```

**Expected Results**
* Deprovisioning should succeed without any errors.
* Any validation errors should occur during provisoning.

**Comment by ksputo** [comment]
FYI:
Me and @polskikiel investigated it and here are some conclusions:

The release name in Helm Broker is generated based on pattern: **prefix**-**$ADDON_NAME**-**$ADDON_PLAN_NAME**-**$GUID**. As stated in error, maximum length is 53 characters and the implementation follows this idea: 

https://github.com/kyma-project/helm-broker/blob/9df179097a8d34cfb030f26bfbf2b4e7591ef6ab/internal/broker/provision.go#L296-L303

As you can see, if the generated release name is longer than 53 we just take the only 53 characters from the whole string. Most of the times it is longer than 53, because prefix, hyphens and GUID length sums to 41 which leaves only 12 characters capacity for both Addon Name and Addon Plan Name.

The name generated in reported case is really unfortunate, because it is exactly 29 characters long without GUID. After the process described above the resulting string will always **end with a hyphen (-)**. The name ending with a punctuation sign does not fulfil the given regular expression `^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$`.

The problem lies in helm-client which is used in Helm Broker for installing charts. Somehow it allows the release creation with a badly formatted name, but checks the release name on deletion. The interesting thing is **it seems that the addon doesn't really get provisioned properly**. I recreated the bug on my cluster, and after adding your addons repository in Kyma and provisioning generic-addon the console UI show that its state is RUNNING and provisioned correctly, but if you list all helm releases on the cluster with command `helm list --tls` it is not listed here. It means that the installing may fail silently caused by a bug in a dependency - helm client.

One of possible fixes is probably to check the generated release name against this regular expression before passing it to helm client.
