### ISSUE TITLE
[POC] Investigate alternative to Function Controller

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#6875]
**Description**

To speed-up migration from Kubeless to Knative we should investigate ready to use solutions that overlaps Function Controller functionality. For example, we should take a look at [Riff](https://projectriff.io/).

Consider the usage of bare Tekton and Knative with a pipeline that will orchestrate all resources.

**Reasons**

Speed-up migration to Knative

**Attachments**

**Comment by pPrecel** [comment]
Conclusions after estimating alternative solutions to function-controller:

 1. I found a lot of solutions similar to function-controller and no one from the list below can be used as an 
alternative:
- [riff](https://github.com/projectriff/riff)
- [keda](https://github.com/kedacore/keda)
- [fn](https://github.com/fnproject/fn)
- [fission](https://github.com/fission/fission)
- [openfaas](https://github.com/openfaas/faas)
- [appscale](https://github.com/AppScale/appscale)
- [nuclio](https://github.com/nuclio/nuclio)
- [openwhisk](https://github.com/apache/openwhisk)
- [camel-k](https://github.com/apache/camel-k)
- [virtual-kubelet](https://github.com/virtual-kubelet/virtual-kubelet)

2. Only the riff can be used as an alternative to function-controller, because of possibilities to image building and cooperation with the knative but from my observations, it delivers a lot of problems, for example, small test coverage,  bad documentations of whole functionalities and small configuration potential.

**Comment by magicmatatjahu** [comment]
Conclusions after investigation of using Tekton and KNative Serving without our abstraction (function-controller).

Advantages:
- more possibilities and ways of creating function, not only by our CR

Disadvantages:
- more complex creation of function - user will have to know how to create pipeline and knative service (complex know-how)
- we still need minimal abstraction for triggering creation of function in console - console-backend service is not good place, because it's only a middleware between console and k8s resources, so applying high-end logic is not acceptable (only solution is creating service for that)
- harder maintenance for users and administrators
- more complex migration from one solution to another 
- more complex presentation on the console 

So, from my point of view, we should develop further function-controller with our abstraction on knative and tekton, but maybe in future add possibility to use tekton as standalone component without function-controller.

**Comment by michal-hudy** [comment]
Ok, thanks. According to investigations made by @pPrecel and @magicmatatjahu we will continue work on Function Controller.
