### ISSUE TITLE
The Kyma documentation contains duplicated examples

### ISSUE THREAD

**Issue by lszymik** [kyma-project/kyma#700]
**Description**

The Kyma documentation, like the one in a file: 036-gs-publish-service-image-and-deploy.md contains information about the deployment of `http-db-service` which is stored in `example` repository.

The sentences like `In your terminal, go to the examples/http-db-service` are misleading because users are not aware of the need to check out a separate repository.

**Expected result**

We should maintain examples in one place and only reference to it where needed.

**Comment by clebs** [comment]
The mentioned file (https://github.com/kyma-project/kyma/edit/master/docs/kyma/docs/036-gs-publish-service-image-and-deploy.md) does indicate that examples are in a separate repository:
> If you did not follow the **Sample service deployment on local** guide and you do not have this directory locally, get the` http-db-service` example from the `examples` repository.

Passing this issue to Technical Writers to make the section more clear since users expected an examples folder in the Kyma repository

**Comment by lszymik** [comment]
If everything is clear, please close that ticket.
