### ISSUE TITLE
 Nightly gardener job is failing because of kyma installation timeout

### ISSUE THREAD

**Issue by lilitgh** [kyma-project/kyma#7068]
**Description**

Recent jobs on for nightly gardener job](https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-gardener-azure-integration) are failing because of kyma installation timeout.  We need to investigate if it is a general problem with gardener or something changed on our side

**Comment by suleymanakbas91** [comment]
First finding: The job uses a low cpu - low memory machine type: `Standard_D2_v3`

**Comment by suleymanakbas91** [comment]
Second finding: When `--nodes 4` passed, hydroform creates 4 workers resulting in 12 nodes. 4 different workers might be affecting the speed.

**Comment by suleymanakbas91** [comment]
With [this PR](https://github.com/kyma-project/test-infra/pull/2038), I changed the machine type to `Standard_D4_v3` (recommended by Kyma docs) and passed `--nodes  1` which creates 2 nodes with only one worker.

**Comment by suleymanakbas91** [comment]
Third finding: the first pod created by `azure-coredns-monitoring-kyma-patch` job gets killed with OOM and the second pod errors because it cannot find the service which was deleted by the first pod. Hisar is working on a fix.

**Comment by suleymanakbas91** [comment]
I increased the worker count to 4 again as 1 didn't work: https://github.com/kyma-project/test-infra/pull/2049

**Comment by suleymanakbas91** [comment]
Forth finding: Installation usually fails in core component. Right before the failure, I saw that all the pods were running, but there was this warning on tiller: 

<img width="1680" alt="Screenshot 2020-02-19 at 10 54 08" src="https://user-images.githubusercontent.com/5543238/74825260-ea5d1000-5309-11ea-8719-7753ea95ddda.png">

This is the related service: 

<img width="1680" alt="Screenshot 2020-02-19 at 10 55 08" src="https://user-images.githubusercontent.com/5543238/74825292-f779ff00-5309-11ea-9f96-16c0504e4786.png">

So, I suppose it takes too long to generate a load balancer IP on Gardener Azure. That's why the installation times out. 

Then, installer fails again and again on core component. The other failures after the first one might be related to this log on tiller:

<img width="1119" alt="Screenshot 2020-02-19 at 11 18 04" src="https://user-images.githubusercontent.com/5543238/74825445-3c059a80-530a-11ea-96c6-e909b3207603.png">

**Comment by suleymanakbas91** [comment]
I created [this bug](https://github.com/kyma-project/cli/issues/379) on CLI, which prevents seeing the failure reason when the installation times out.

**Comment by rakesh-garimella** [comment]
The multiple nodes issue is handled via:https://github.com/kyma-incubator/hydroform/pull/91. We still need to fix https://github.com/kyma-project/cli/issues/379 so that we have better logs and see the failure issue

**Comment by a-thaler** [comment]
The job is still failing, please investigate why the "core" module installation is timing out.
Furthermore I propose to not wait for finishing the deprovisioning. The Gardener based deprovisioning can last for days (It first tries to uninstall all custom deployments/CRDs. With kyma that fails. So it will wait for a periodic cleanup job doing the forced deletion)

**Comment by clebs** [comment]
After investigations, we found out that the core component was failing because the API Server Certificate was failing on creation with the following error message:
```
the Common Name is limited to 64 characters (X.509 ASN.1 specification), but first given domain apiserver.grdnr-hnq8dx.kyma-prow.shoot.canary.k8s-hana.ondemand.com has 67 characters
```

Reduced the length of the cluster name so that the full domain fits in 64 characters here: https://github.com/kyma-project/test-infra/pull/2117

Now the installation goes through as expected.

Therefore, it is very important for managed offering that the cluster full domain, including the `apiserver` prefix, does never exceed 64 characters.
