### ISSUE TITLE
Provide ability to customers/developers to define tests that can be run during upgrade

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#7213]
**Description**

As a customer, I know my business scenarios better than anyone. They have been implemented by me or my partner.

_So it makes sense that I should have the ability to define tests that should be run during the upgrade process._ 

They will ensure that none of my business scenarios or transactions will be messed up post-upgrade.

**Reasons**

**Comment by jose-cortina** [comment]
What would happen if any one of the scenarios would fail?
- (automated) rollback of the upgrade?
- manual intervention to analyze and fix the issues?

**Comment by abbi-gaurav** [comment]
I would leave that to the upgrade team to decide how to handle such behavior.
One suggestion would to have customer the power to decide

**Comment by pbochynski** [comment]
I think that the story is unlikely to be implemented in the near future. I am not also sure if we should even go in that direction. You can run the tests only when the upgrade is done. So technically it is just running the tests after the upgrade and trigger some action on failure (rollback or just notification). For Kyma managed offering we wouldn't like to block upgrade because of external test fail - as it can block upgrade process forever because of broken test. We would like to depend on our own tests. For customers who run Kyma on their own it should be relatively easy to run some tests with the CI/CD of their choice and test framework of their choice.
Right now we put more effort into checking backward compatibility and extensive update tests what should ultimately resolve the root problem.
