### ISSUE TITLE
[CBS][Checkmarx] SSRF Header security issues

### ISSUE THREAD

**Issue by Wawrzyn321** [kyma-project/kyma#7293]
**Description**

Checkmarx scan has detected a medium issue:

> The application sends a request to a remote server, for some resource, using WithContext. However, an attacker can control the target of the request, by sending a URL or other data in Header. 

**Affected files**
* components\console-backend-service\internal\authn\middleware.go
* components\console-backend-service\pkg\tracing\handler.go

[Checkmarx](https://cx.wdf.sap.corp/CxWebClient/ViewerMain.aspx?scanid=5487494&projectid=79752)

**Comment by kwiatekus** [comment]
- components\console-backend-service\internal\authn\middleware.go
middleware server splits the `sec-websocket-protocol` header and prepares `Authorization` header out of it's content before forwarding it to token validation. 
This operation doesn't expose any ways to inject malicious headers. 
Any manipulations done to `sec-websocket-protocol` are then subjected to access token validation.
**FALSE POSITIVE**

 - components\console-backend-service\pkg\tracing\handler.go
 We pass request headers to a  open-tracing library so that requests with specific header values can be traced via tools like Jeager. Its a standard in the distributed tracing
**FALSE POSITIVE**

**Comment by sergio-oss** [comment]
@kwiatekus if false positive may we close it ?
