### ISSUE TITLE
Not enough admins permissions

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/kyma#7343]
**Description**

Runtime and Namespace Admins don't have required permissions.

Missing permissions for Runtime Admin:

```
apiGroups: ["applicationconnector.kyma-project.io"]
resources: ["applications"]
verbs: ["get", "list", "watch"]

apiGroups: ["applicationconnector.kyma-project.io"]
resources: ["applicationmappings"]
verbs: ["create", "list"]
```

Missing permissions for Namespace Admin:

```
apiGroups: ["addons.kyma-project.io"]
resources: ["addonsconfigurations", "addonsconfigurations/status", "addonsconfigurations/finalizers"]
verbs: ["get", "list", "watch", "create", "update", "delete"]

apiGroups: ["rbac.authorization.k8s.io"]
resources: ["roles", "rolebindings"]
verbs: ["get", "list", "create", "update", "delete"]
```

Additionally, Namespace Admin should be able to create/update/delete all namespace-wide resources like pods etc.

**Expected result**

Runtime Admin should be able to manage also applications, Namespace Admin should be able to manage all namespace-wide resources in his namespace.

**Actual result**

Runtime Admin doesn't have permissions to manage applications. Namespace Admin doesn't have permission to see addons and permissions or to create pods etc.

**Steps to reproduce**

**Troubleshooting**

**Related**
https://github.com/kyma-project/kyma/issues/7803

**Comment by Tomasz-Smelcerz-SAP** [comment]
Unable to verify.

I understand the ticket as follows

- the term "Runtime Admin" refers to the subject mapped to the group "runtimeAdmin". This value is visible in "groups" claim in JWT used to authenticate.

- the term "Namespace Admin" refers to the subject mapped to the group "runtimeNamespaceAdmin".
This value is visible in "groups" claim in JWT used to authenticate.

Naming of groups / XSUAA subjects has changed recently, that's why I am making this clarification.

Assuming the above, I have extended our tests to cover cases described in the ticket, all tests are passing.
I have also created a cluster and set up XSUAA connector manually

Manual verification confirmed that:

As a "Runtime Admin" I can
- create and list applications
- create and list applicationmappings


As a "Namespace Admin" I can
- create a role (from kubectl, I don't see any option to do it using UI)
- list role and see it's details
- delete a role in the namespace I've created

- create rolebinding in the namespace I've created
- list rolebindings in the namespace I've created
- delete rolebinding in the namespace I've created

- manage addonsconfigurations (only from kubectl, the option to do it from UI looked disabled)

**Comment by kwiatekus** [comment]
@Tomasz-Smelcerz-SAP  I confirm.

I downloaded kubeconfig as `runtimeNamespaceAdmin` and I can perform all the above mentioned operations:

```
kc auth can-i create applicationmappings --namespace my-nmspc
yes

kc auth can-i create addonsconfigurations.addons.kyma-project.io --namespace my-nmspc
yes

kc auth can-i create roles --namespace my-nmspc
yes

kc auth can-i create rolebindings --namespace my-nmspc
yes
```

@dariadomagala There are two situations where UI indicates insufficient RBAC settings:

- Namespaced Addons View - create addon disabled
<img width="846" alt="Screen Shot 2020-03-04 at 14 49 29" src="https://user-images.githubusercontent.com/6783567/75885786-6e91b600-5e27-11ea-8ebc-995e46f80391.png">

- API Rules view - fetching services 
<img width="1362" alt="Screen Shot 2020-03-04 at 14 49 42" src="https://user-images.githubusercontent.com/6783567/75885797-73ef0080-5e27-11ea-910b-0ec81cf8b822.png">

Lets investigate in our team.

**Comment by kwiatekus** [comment]
Found a related problem:
https://github.com/kyma-project/kyma/issues/7803

**Comment by kwiatekus** [comment]
Found a problem with gql configuration for service query:
https://github.com/kyma-project/kyma/pull/7809
