### ISSUE TITLE
Docker registry development setup

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#7370]
**Description**

 - It must be possible to download images when Kyma is installed with a self-signed certificate
   - On production created solution shouldn't be executed
   - >**HINT**: Use DaemonSet
   - Check on AKS, GKE, Minikube and Gardener

**Reasons**

**Attachments**

**Comment by aerfio** [comment]
After #7451 is merged fun-controller will work on GKE, Azure, Minikube and Gardener. Pipelines with tests will be run after function-controller replaces kubeless as default solution.

After some tests pipelines with minikube unfortunately timeout, it may be due to too low resources. To enable those tests one would have to either add `{function-name}.kyma.local` to `/etc/hosts` file, or make a request to $(minikube ip):{correct ingress port} with appropriate headers -> the problem that I've experienced is that it redirects to https, which fails afterwards
