### ISSUE TITLE
 Hard-coded passphrases in Dex

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#741]
The Dex config map contains a section of static passphrases. This includes hashes of predefined passphrases for high-privileged default users.

**Risk:**

Users who run a Kyma cluster with these default users, will be vulnerable to unauthorized access by arbitrary attackers. This fully compromises confidentiality, integrity, and availability of the respective Kyma cluster.

This risk persists even if the plaintext passphrases were documented elsewhere.

**Suggested mitigation:**

Don't use hard-coded passphrases!

Instead, generate strong, securely random passphrases during the install process. Print these passphrases (and the corresponding users) to the console. Or emit them to a local file (which must only be readable by the current OS user.)

Alternatively, elicit the passphrases interactively, or make them configurable via env-vars or CLI arguments.

**Comment by derberg** [comment]
Please share how you plan to fix this before you do as this must developer friendly:
- printing on local install to console is not enough as we also might have cluster installation 
- this must be introduced well in documentation because it must be easy to use https://github.com/kyma-project/kyma/pull/198/files
- it must be properly communicated so people from projects like https://github.com/kyma-project/console/tree/master/tests know there is additional work need

**Comment by kubadz** [comment]
@derberg 
Sorry, I didn't see your comment. All the documentation related to creating the static users or logging to the UI was updated. There was also an appropriate information in the slack. For users it will be communicated in the changelog of the new release.

**Comment by meeque** [comment]
Sorry, I know this is already closed. But could you have a look at my comment in PR #1245?
