### ISSUE TITLE
Lambda dashboard is empty for few key KPI's

### ISSUE THREAD

**Issue by himanshu-sv** [kyma-project/kyma#7463]
Kyma version 1.9

I created a few lambdas and then looked into the dashboard to check the KPIs.
A few key KPIs showed "No data"
Screenshot attached. 
<img width="1353" alt="Screen Shot 2020-03-04 at 11 57 16" src="https://user-images.githubusercontent.com/4199500/75874662-83b01a00-5e12-11ea-9519-afc7a8ccd59d.png">
<img width="1391" alt="Screen Shot 2020-03-04 at 12 03 53" src="https://user-images.githubusercontent.com/4199500/75874670-86ab0a80-5e12-11ea-8c69-d0773e7b8876.png">

**Comment by VishnAndr** [comment]
Same here. Experiencing exactly the same. Also looks very similar to https://github.com/kyma-project/kyma/issues/2541 but 
```
$ kubectl get servicemonitor istio-mesh -n kyma-system                      
Error from server (NotFound): servicemonitors.monitoring.coreos.com "istio-mesh" not found
```
so that fix is not applicable.

**Comment by a-thaler** [comment]
Thanks for your feedback, it turned out that there are several issues.
- the main variables for selecting the namespace and the function used outdated queries
- there were some few outdated widgets used
- the variables were overcomplicated, there were 6 in use where only 2 are needed

I re-created the dashboard and now it looks good (see related PR)
I tested it with kyma 1.9 and had problems to get it running as the `istio_requests_total` metric somehow changed.
With kyma 1.10 it works out of the box. As a workaround just apply the dashboard manually and don't forget to remove the few escapings for helm templating before applying via kubectl. mainly change {{`{{pod}}`}} to {{pod}}
