### ISSUE TITLE
POC Advanced retry in kyma-installer

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#7629]
**Description**

The latest change in the installer brings retries of single release instead of retrying the whole installation/upgrade process. This simplifies the process and shortens time, however, it brings up other issues like weak chart design of releases. Let's take release core as an example : 

It's an umbrella chart for multiple components and resources likes `console, cbs, istio rbac, cluster users` etc. When something will fail installer is retrying installation/upgrade of core release, however, ends up with an error `release core already exists` and eventually it reaches maximum number of retries(5) and stop the entire process. A similar issue happens when tiller has problems with connectivity to apiserver, for example `connection refused` happens, such error is propagated by installer and is a subject of retry.

We need to do a **POC**  for improved retries.

If an error occurs during : 

1. Installation - do helm delete before retrying
2. Upgrade - find last deployed revision of release and perform the rollback. If we find all revisions failed we need to do helm delete and then install

In case of `Installation` we can set `atomic` which from tiller docs says : ```If set, installation process purges chart on fail, also sets --wait flag```

On `Upgrade` we could also use `atomic`, tiller docs mentions : `If set, upgrade process rolls back changes made in case of failed upgrade, also sets --wait flag` or  

`cleanup-on-fail `      
` Allow deletion of new resources created in this upgrade when upgrade failed`

**Reasons**

Identify how we can improve retries handling for helm releases. Which will be base for future implementations.

**Attachments**

**Comment by aerfio** [comment]
There were some changes on Gardener that make this issue with Tiller being unable to connect to apiserver really painful. While investigating https://github.com/kyma-incubator/compass/issues/980 and discussing things with Gardener guys they've explained that while they detect high load they scale up apiserver, which results in Tiller losing connection. 

On our side it manifests by kyma-installler trying to install release once again, which fails and prevents Kyma installation, and it's not really dependent on any component, because we've seen it fail on istio, knative serving, knative eventing, dex and logging (see that compass issue for Tiller logs, they all look the same).

**Comment by BenceJ** [comment]
my suggestion would be to upgrade and use helm 3 instead of 2, which didn't use Tiller, could be a way (hopefully) to go around this problem

**Comment by piotrmsc** [comment]
Helm 3 is planned for the future with in general installation topic, currently, we want to make installer bit more resilient for tiller issues.
