### ISSUE TITLE
Assure that namespace admin can follow backup guide

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#7862]
**Description**
With https://github.com/kyma-project/kyma/issues/7861 there will be a new guide on how to create volume snapshots and restore them. Please assure that the namespace-admin role can execute that guide

**Reasons**

**Attachments**

**Comment by clebs** [comment]
The tested role `kyma-namespace-admin-essentials` does not have the necessary permissions to do anything other than creating namespaces.
The following permissions are missing in order to be able to create a volume snapshot (optional permissions in brackets):
- `StorageClass`: get, create, (delete)
- `PVC`: get, create, (delete)
- `Deployment`: get, create, (delete)
- `Pods`: get, (delete)
- `Snapshot Class`: get, create, (delete)
- `Snapshot`: get, create, (delete)

**Comment by clebs** [comment]
Retested with the correct setup as the previous role information was incomplete.
Currently the namespace admin role has 2 issues preventing the backups:
1. Can't create a `Snapshot Class` since it is a non-namespaced resource: Gardener team will add a default `Snapshot Class` out of the box that customers can use when provisioning.
2. Can't create, get, list, delete or update `Snapshot` resources on their namespace: #8382 adds those permissions to the namespace admin.

With both things in place, customers will be able to create persistent volume snapshots by following the guide.
