### ISSUE TITLE
Application Gateway incompatible with OAuth2 Server

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#7901]
**Description**

Dear Colleagues,

when configuring API Gateway v2 to issue OAuth tokens, these can not be consumed by the application gateway.

When the application gateway calls it uses both Basic Auth as well as client_secret & client_id body values.

The token endpoint responds to that with:

```
{
    "error": "invalid_client",
    "error_description": "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)",
    "error_hint": "The OAuth 2.0 Client supports client authentication method \"client_secret_basic\", but method \"client_secret_post\" was requested. You must configure the OAuth 2.0 client's \"token_endpoint_auth_method\" value to accept \"client_secret_post\".",
    "status_code": 401
}
```
Kyma Version is 1.11.0 on K8S 1.16.8 Gardener

**Expected result**

Kyma components are compatible

**Actual result**

Kyma components are incompatible

**Steps to reproduce**

**Troubleshooting**

**Comment by piotrmsc** [comment]
The Oauth2 client does not have proper authentication method set, in this case it should be `client_secret_post` , however, application connector is sending token in both header and a body and this is not supported in oathkeeper/hydra.
https://www.ory.sh/docs/hydra/sdk/api#create-an-oauth-20-client

I will check RFC how it defined such situation and if it allows sending token in both header and body at the same time I will create issue in ory and link it here :)

**Comment by aeneasr** [comment]
https://openid.net/specs/openid-connect-core-1_0.html (Section 9) defines that!

**Comment by aeneasr** [comment]
So to clarify - the client authN method is specified in OpenID Connect Core. It's part of the certification and as far as I'm aware the OpenID Connect Dynamic Client Registration does not support defining more than one authN method for the client.

Programming languages like Go actually select the authN method for OAuth2 client_credentials flows automatically, because many providers solve this in different ways.

On ORY Hydra's end, we will not relax the security policy for client_credentials grants because enforcing e.g. private_key_jwt is important. I understand that this can be a bit frustrating from a user's perspective but unfortunately that's what the spec implies...
