### ISSUE TITLE
Ory installation Fails with Override Own Domain and Certificate

### ISSUE THREAD

**Issue by thaer899** [kyma-project/kyma#7903]
**Description**

Using AKS 1.16.7
When doing the installation with our own domain and certificate, Ory installation faills after those 3 warnings

```
2020/04/04 08:22:03 Warning: Merging destination map for chart 'oathkeeper-maester'. Overwriting table item 'envs', with non table value: [map[name:mutatorsAvailable value:noop,id_token,header,cookie,hydrator]]
2020/04/04 08:22:03 Warning: Merging destination map for chart 'oathkeeper'. Overwriting table item 'envs', with non table value: [map[name:mutatorsAvailable value:noop,id_token,header,cookie,hydrator]]
2020/04/04 08:22:03 Warning: Merging destination map for chart 'oathkeeper-maester'. Overwriting table item 'envs', with non table value: [map[name:mutatorsAvailable value:noop,id_token,header,cookie,hydrator]]
2020/04/04 08:22:03 Step error:  Details: Helm install error: rpc error: code = Unknown desc = a release named ory already exists.
Run: helm ls --all ory; to check the status of the release
Or run: helm del --purge ory; to delete it
2020/04/04 08:22:03 Error during install/update:  Details: Max number of retries reached during step: install component ory
E0404 08:22:03.891900       1 controller.go:262] Max number of retries reached during step: install component ory
```

**Expected result**

Installation finishes as expected

**Actual result**

Ory Helm release fails

**Steps to reproduce**

```
kubectl apply -f configmap-owndomain-overrides.yaml
apiVersion: v1
data:
  global.domainName: kyma.com
  global.tlsCrt: xxx
  global.tlsKey: xxx
kind: ConfigMap
metadata:
  name: owndomain-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    kyma-project.io/installation: ""  

```

**Troubleshooting**

We tried first to do an upgrade and it didn't work so we reprovisioned a new cluster and did the installation from scratch.
Installation works fine with xip generated domains. (We also tried that)

And all component are created just fine the only one that keeps failing is Ory after the 3 warnings..
Maybe we should add an override for Ory?
We tried though but not sure that we chose the right fields..
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ory-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: ory
    kyma-project.io/installation: ""
data:
  global.ory.hydra.persistence.enabled: "true"
  global.ory.hydra.persistence.postgresql.enabled: "true"
  global.ory.hydra.persistence.gcloud.enabled: "false"
  hydra.hydra.autoMigrate: "true"
  oathkeeper.deployment.resources.limits.cpu: "800m"
  oathkeeper.deployment.resources.requests.cpu: "200m"
  hpa.oathkeeper.minReplicas: "3"
  hpa.oathkeeper.maxReplicas: "10"
```
We also tried 
  global.ory.hydra.persistence.enabled: "false"
  global.ory.hydra.persistence.postgresql.enabled: "false"

Thanks!

**Comment by piotrmsc** [comment]
Hey! @thaer899  

What overrides (please provide them, in terms of cert/sensitive data just put values like XXX) have you used for a) upgrade b) pure install? Reading your notes, did you use mentioned ory overrides in bot upgrade and install or you have added them later? Thanks!

**Comment by piotrmsc** [comment]
After having an offline discussion we installed kyma with own domain and certificate. Here's a short summary.

One of the first errors was connection failure with apiserver, done by tiller. Helm release of the component had FAILED status and then retries on failed release produced error message like `release XXX already exists` from tiller. Normally this is a manual step that the cluster operator needs to perform (cleanup). We are working on improvements, adding a bit more automation for the operator but not everything will be possible to solve therefore depending on the case there still will be manual action needed. 
However, new cluster on xip.io domain with self signed cert did work, so later after trying to upgrade it to own cert and domain ory was not installing because disk was unmounted/deleted when `helm del ory --pruge --tls` was done manually. Depending on cloud provider storage class definition, it may be automatically deleted when stafeul set and PVC are deleted or not. In this case after we have deleted old disk and new one was attached installation succeeded. It was not installing on older disk because on it there was already different user saved for porstgress and hydra was trying to connect with new one. 1.12 will bring refactoring for connection handling, already done but not released yet, which simplifies ory usage with own DB/managed DB with single secret, which is not directly relevant here, but also tried to reuse old username and password if exists on cluster (override or created secret). 

The own domain override was ok, it was not the root cause of the error.
