### ISSUE TITLE
CORS for OAuth2 Server

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#7934]
**Description**

Dear Colleagues,

when calling the OAuth2 Authorization server from within a UI hosted inside another Kyma Application I get CORS errors from Chrome.

Example:

UI is hosted as ui.kyma.cx, Corresponding OAuth2 Authorization Server would be oauth2.kyma.cx. Calls from within a swagger ui to oauth2.kyma.cx are blocked due to CORS preflight issues.

Cheers

Andreas

**Expected result**

No CORS error
**Actual result**

CORS errors

**Steps to reproduce**

see above

**Troubleshooting**

N/A

**Comment by shilpa-kulkarni2** [comment]
I am facing exactly same issue. any solution on this?

**Comment by tehret77** [comment]
Same problem here. Any proposal how to workaround this?

**Comment by strekm** [comment]
as of [kyma 2.2](https://kyma-project.io/blog/2022/5/4/release-notes-22#ory-stack-deprecation-note) ORY stack is deprecated since we decided that we would like to invest in closer integration with Istio. any work related to ORY will be discontinued. thank you for your understanding and stay tuned for new features :)
