### ISSUE TITLE
Enable tracing for GraphQL server in UI API Layer

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#849]
**Description**

As `Jaeger` is used in Kyma it would be nice to monitor GraphQL queries. `gqlgen`, library that is used for GraphQL server, has support for `OpenTracing`. Enabling this is relatively simple, just set up a connection to `Zipkin`.

I have created small POC and Query will look like that in `Jaeger`:

![image](https://user-images.githubusercontent.com/26445970/45865754-c7c67080-bd7e-11e8-812e-7dca02064148.png)

AC:
 - [ ] Tracing enabled for GraphQL queries, mutations, and subscriptions
 - [ ] GraphQL tracing information displayed in the same chain as whole HTTP query, so it will look like that: `istio -> ui-api -> graphql`

We can also add more tracing information, for example from services (follow up task).

**Reasons**

Sometimes it is difficult to find the reason why query works slow or why it fails. If we will have such information displayed in `Jaeger` it will be much easier to investigate.

**PoC**

https://github.com/michal-hudy/kyma/tree/ui-api-monitoring

**Comment by derberg** [comment]
Please first check in jaeger how tracing for ui-api-layer looks like before the implementation and create a screen shot so we have it for later to show how it looked like before

**Comment by jcwiekala** [comment]
During investigation of this topic I was analysing Envoy's documentation, because I thought that it might be possible to achieve goals just by changing Envoy's configuration. I couldn't find anything more useful that is already in Kyma.

I have also set up solution based on branch `https://github.com/michal-hudy/kyma/tree/ui-api-monitoring`, I tried to do some changes using library `github.com/opentracing/opentracing-go`, to wrap all incoming `ui-api-layer`'s request with additional tracing logs, unfortunately I ran out of time which I had to complete this task.

Screens below show what jaeger traces look like without `OpenTracing` adjustments:
![service_catalog.png](https://images.zenhubusercontent.com/5bf3e1d198990d7460dcccb1/2dbaef73-04fa-4744-95e2-4a03c9a7c2d9)
![service_instances.png](https://images.zenhubusercontent.com/5bf3e1d198990d7460dcccb1/ca5cdc5f-7eb0-4966-9227-a1f2ddb0f7e0).

**Comment by michal-hudy** [comment]
still valid

**Comment by m00g3n** [comment]
![image.png](https://images.zenhubusercontent.com/5c7942937063e223386f44c9/caca378b-1683-4467-9c82-5368ddad58f0)

**Comment by m00g3n** [comment]
![image.png](https://images.zenhubusercontent.com/5c7942937063e223386f44c9/80014d72-6d77-4d67-a40c-c52bc96f6a29)

**Comment by m00g3n** [comment]
To verify change `PILOT_TRACE_SAMPLING` value in `istio-pilot` `deployment` to `100`
