### ISSUE TITLE
Helm3 support for kiali component

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#8603]
**Description**
Migrate the logging component to be helm3 compliant

AC:
- helm3 linting will not complain
- No helm2 specific labels applied to resources
- helm install works

**Reasons**
Support for Helm3 in Kyma

**Attachments**

**Comment by clebs** [comment]
Kiali chart is migrated to helm 3 except for the non-backwards compatible changes to be finished when the kyma operator is on Helm 3.

Uninstall does not fully work on Kiali because of the following issue:
https://github.com/kiali/kiali/issues/2866

**Comment by jmazzitelli** [comment]
Removing just the operator resources and the namespace where the operator exists is not enough. When you install Kiali (which is done when you create the Kiali CR, which triggers the operator to install Kiali), you will be getting resources that potentially live outside the namespace which is why you need to remove the Kiali CR first - this allows the operator to uninstall/clean up Kiali - then you can remove everything else operator-related.

You do this by ensuring your uninstall process removes the Kiali CR *first* - let that complete - and then remove the rest of the operator resources.
