### ISSUE TITLE
Migrate monitoring component to v2 version of Istio Telemetry

### ISSUE THREAD

**Issue by Demonsthere** [kyma-project/kyma#9101]
**Description**
Since Istio 1.5 the telemetry component has moved from apiVersion v1 to v2, and has been merged into the IstioD service. Due to that the current configuration of Prometheus and Grafana dashboards are empty, as most of the metrics and labels are missing. 

**Requirements**
- Update Prometheus to get metrics and labels from new sources
- Import new Grafana dashboards
- Validate that Kiali still works
- Validate that jaeger is working, check if mixer spans are still there or remove them: https://github.com/kyma-project/kyma/issues/1139, https://github.com/kyma-project/kyma/issues/6549

**Attachments**

**Comment by a-thaler** [comment]
Documentation can be found at https://istio.io/v1.5/docs/reference/config/telemetry/. Sounds very experimental still.

**Comment by rakesh-garimella** [comment]
The prometheus has been adapted to the telemetry v2 provided by istio by migrating the service monitor to podmonitor. During the migration we had issue with increased memory usage in prometheus due to hight number of cardinality to mitigate this we dropped several labels and mapped label to a static value. With these changes the memory usage was under control and comparable to telemetry v1 levels.
