### ISSUE TITLE
Monitoring: Kubelet patch cleanup not working

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#9107]
**Description**
The monitoring kubelet patch cleanup is not working on Prow and it also breaks the retry mechanism because the pre-install hook that does the cleanup is not removed properly when deleting the helm release.

See the relevant errors:

```
! Installation error occurred while installing Kyma: installation error occurred: install component monitoring. Details: Installation errors: 
Component: monitoring, Log: Helm installation of release "monitoring" failed: failed pre-install: warning: Hook pre-install monitoring/templates/kyma-additions/aks-kubelet-monitoring-patch-pre-upgrade-cleanup.yaml failed: Post https://100.64.0.1:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: unexpected EOF
Deleting release before retrying.
Helm delete of release "monitoring" was successfull
Component: monitoring, Log: Helm installation of release "monitoring" failed: failed pre-install: warning: Hook pre-install monitoring/templates/kyma-additions/aks-kubelet-monitoring-patch-pre-upgrade-cleanup.yaml failed: serviceaccounts "aks-kubelet-monitoring-cleanup-patch" already exists
```

**Expected result**

- Kubelet cleanup is successful.
- If monitoring needs to be retried, the pre-install hook is deleted accordingly.

**Actual result**

- Kubelet cleanup job fails.
- Pre-install hook of the cleanup job is not removed when deleting the helm release, making retry impossible.

**Troubleshooting**

Full job logs:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-integration-gardener-azure/1286511648592367618

**Comment by a-thaler** [comment]
We figured out that the mentioned patch job is a helm hook having `helm.sh/hook-delete-policy: hook-succeeded` So a failure caused by api-server connectivity will keep the related resources. The re-try logic then fails as the resource already exist.
It should have `helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded` so that resources are staying in case of an error for debug reasons but will be deleted in case of a new execution.
The attached PR will fix all occurrences of the problem in the kyma charts.
