### ISSUE TITLE
Create a Proxy Service for the Cloud Event Gateway

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#9232]
In order to reach out to Enterprise Messaging Cloud-Event Gateway, it'd be more sensible to have a no auth proxy handler which would be under service mesh. This proxy handler captures event publishing request from the cluster workloads (microservice or serverless functions) and redirects it to the cloud event gateway of Enterprise Messaging Service.

**Given Assumptions**
- A Secret available with the Authorisation principle of Enterprise Messaging.

**AC**
- [x] Proxy handler should have a cloudevent receiver where the workloads can publish events.
- [x]  Based on the authorisation principle of Enterprise Messaging, this proxy handler should create a connection to the cloud event gateway in the most efficient way to ensure best performance.
- [x] Request Received on the proxy handler should synchronously be redirected to the Cloud Event gateway so that the response can be propagated back to the invoker to tell the publishing status.
- [x] Mechanism to check the network connection status (network layer b/w this proxy layer and cloud event gateway)
- [x] Project Structure should have a Dockerfile and respect the generic Makefile guidance.

P.S: No Prow job for this implementation.

**Comment by nachtmaar** [comment]
Task list:

- [ ]

**Comment by marcobebway** [comment]
Hi @anishj0shi

> Based on the authorisation principle of Enterprise Messaging, this proxy handler should create a connection to the cloud event gateway in the most efficient way to ensure best performance

**Comment by marcobebway** [comment]
Hi @anishj0shi, regarding:

> Based on the authorisation principle of Enterprise Messaging, this proxy handler should create a connection to the cloud event gateway in the most efficient way to ensure best performance.

Does it make sense to have a follow-up ticket for benchmarking and performance evaluation?

**Comment by marcobebway** [comment]
**Response time benchmarking**

We agreed to have some initial comparison for the publish response times between:

- **Workload** → **Cloud Event Gateway Proxy** → **Enterprise Messaging Service**
- **Cloud Event Gateway Proxy** → **Enterprise Messaging Service**

```json
| Workload Response Time              | Cloud Event Gateway Proxy Response Time | Diff  |
| ----------------------------------- | --------------------------------------- | ----- |
| ID: 16001231020 - Time: 549.44 ms   | ID: 16001231020 - Time: 533.28248 ms    | 16 ms |
| ID: 16001231031 - Time: 58.742 ms   | ID: 16001231031 - Time: 53.656689 ms    |  5 ms |
| ID: 16001231032 - Time: 35.358 ms   | ID: 16001231032 - Time: 30.557865 ms    |  5 ms |
| ID: 16001231033 - Time: 32.890 ms   | ID: 16001231033 - Time: 28.230864 ms    |  4 ms |
| ID: 16001231044 - Time: 20.216 ms   | ID: 16001231044 - Time: 15.802753 ms    |  5 ms |
| ID: 16001231045 - Time: 24.443 ms   | ID: 16001231045 - Time: 20.030488 ms    |  4 ms |
| ID: 16001231046 - Time: 19.858 ms   | ID: 16001231046 - Time: 15.841242 ms    |  4 ms |
| ID: 16001231047 - Time: 20.523 ms   | ID: 16001231047 - Time: 16.111565 ms    |  4 ms |
| ID: 16001231048 - Time: 19.529 ms   | ID: 16001231048 - Time: 15.390811 ms    |  4 ms |
| ID: 16001231049 - Time: 26.445 ms   | ID: 16001231049 - Time: 22.213384 ms    |  4 ms |
```

**Conclusion**

- There is a slight difference between the two response times because of the network cost needed for a workload to reach the Cloud Event Gateway Proxy pod which is exposed via a K8S service. However, the difference is acceptable.

- The first publish request response time is significantly big, because of the time taken to acquire an access token from the Authentication Server. However, this access token will be cached (until it expires) and the next publish requests shall be noticeably faster.
