### ISSUE TITLE
Inconsistency in tables for production profiles

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#9238]
**Description**

We received feedback from a customer that tables with configurable parameters in production profiles docs are not consistent and do not always reflect the full path of the actual production override in the [`installer-config-production.yaml.tpl`](https://github.com/kyma-project/kyma/blob/master/installation/resources/installer-config-production.yaml.tpl).

See [Hydra OAuth2 server](https://kyma-project.io/docs/components/security/#configuration-o-auth2-server-profiles-oathkeeper-settings-for-the-production-profile) as an example but all docs wth production profiles should be verified against `installer-config-production.yaml.tpl` and corrected if needed.

**Expected result**

**data.oathkeeper.deployment.resources.limits.cpu**

![image](https://user-images.githubusercontent.com/40655785/90023713-549caf00-dcb4-11ea-8e27-91e657bfd611.png)

**Actual result**

![image](https://user-images.githubusercontent.com/40655785/90023796-7007ba00-dcb4-11ea-834e-f5d4dcd4a84f.png)

**Comment by Demonsthere** [comment]
This is invalid, the override path is supposed to be missing the `data` part, as it is a field in the configmap/secret and not a part of the override path.

**Comment by klaudiagrz** [comment]
This issue is no longer valid. We will no longer document profile-specific values in the official documentation. The path to the files containing values specific for both evaluation and production profile is described in the [generic document about profiles](https://kyma-project.io/docs/master/root/kyma/#installation-overview-profiles). The [PR](https://github.com/kyma-project/kyma/pull/10578) with the docs clean-up is in review.

**Comment by klaudiagrz** [comment]
This issue will be resolved by https://github.com/kyma-project/kyma/issues/10654 .

**Comment by klaudiagrz** [comment]
This issue will be resolved by https://github.com/kyma-project/kyma/issues/10654 . The progress will be monitored there so I'm closing this ticket.
