### ISSUE TITLE
Azure upgrade job is failing

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#9275]
**Description**

The test-integration-test-external-solution gets stuck at prepare-data stage while registering a test service.

Details are [here](https://github.com/kyma-project/kyma/issues/9210#issuecomment-674266000).

**Expected result**

The job should succeed.

**Comment by janmedrek** [comment]
@sayanh Can you provide more details along with the logs? You have linked the same ticket twice. To which part of Kyma this is tied? 

Please link logs or examples on how to reproduce this error. I do not see a reason to link that to Application Connector, the last issue was caused by a missing chart as far as I can see.

**Comment by sayanh** [comment]
@janmedrek Sorry about the double mention of the same link. I fixed the description. [Here's](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-azure/1306397761528139776/build-log.txt) a recent occurrence of the issue.

This is reproducible. Most of the failures of the `kyma-upgrade-gardener-azure` job is failing due to the same reason. Details are [here](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-azure).

**Comment by sayanh** [comment]
Closing this as it is a duplicate of https://github.com/kyma-project/kyma/issues/9604
