### ISSUE TITLE
Receiving event in secured workload

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9563]
As Matthew i want to be able to receive events in my workload without compromising on security, so that I can be sure that I only receive valid events.

AC:
- [x] workload receives events
- [x] workload exposed in a secure way (oauth)

**Comment by nachtmaar** [comment]
Task List:

Assumption: Controller is already able to reconcile on Subscription CRD and BEB Subscription created

- [ ] Generate exactly one global `OAuth2Client` CR via eventing Helm chart
- [ ] Assume you have secret as environment variables for clientID + clientSecret
- [ ] CRUD on APIRule and include Oauth credentials (clientID + clientSecret)
- [ ] Add Informer on APIRule
- [ ] Reflect APIRule in Subscription status

Open question:
- [ ] what happens if e.g. Kyma upgrade happens => will the clientID + clientSecret still be the same
