### ISSUE TITLE
Evaluation profile for serverless

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#9738]
**Description**

Limit resources for serverless components for evaluation profile. Change CPU requests to 10m for both components. 
Is serverless-docker-registry-self-signed-cert required at all? 

**Reasons**

Serverless components request too much CPU.
```
  Namespace                   Name                                                           CPU Requests  CPU Limits   Memory Requests  Memory Limits  AGE
  ---------                   ----                                                           ------------  ----------   ---------------  -------------  ---
  kyma-system                 serverless-docker-registry-5b685d6cb7-m9kn6                    100m (2%)     400m (10%)   300Mi (2%)       800Mi (5%)     14d
  kyma-system                 serverless-docker-registry-self-signed-cert-lwlp9              70m (1%)      100m (2%)    70Mi (0%)        100Mi (0%)     14d
```

**Attachments**

**Comment by aerfio** [comment]
After cert-manager is merged as kyma component we'll be able to use some global value in chart to detect whether runtime uses proper not-self-signed certs, so that we'll be able to cut serverless-docker-registry-self-signed-cert in some cases. Contact goat team for details.

As for serverless-docker-registry itself please check it's cpu and memory consumption during it's actual work, not during idle time.
