### ISSUE TITLE
Evaluate node-js k8s client as a in-cluster backing service

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#9832]
Use node-js k8s client as in-cluster backing service to manage pods in console UI

**Description**

**AC**
- define backend as a kyma resource, determine reasonable resources and replication policy for the backend (2)
- User can view, delete pods from the list & user can edit pod via drawer (5)
- check 401/403 responses from api server ( maybe some extra messages needed ) (2)
- STRETCH : check how to scrape metrics (i.e requests per second, distinct tokens per 15 min ) [time-box : 1d]
- design testing strategy and implement smoke tests (5) 

**Reasons**

 - We want to deprecate CBS and its authorisation middleware
 - We want to swap CBS with low-maintanance component

**Comment by kwiatekus** [comment]
We have managed to install an experimental UI backend container ( based on node-js k8s client ) as a in-cluster backing service for UI.
It consumes a bearer token issued by DEX and hits api-server-proxy ( it does not have any authentication middleware)
It serves back information about pods.

Our plan would be to continue working on it ( as it has potential for a thin, low-maintenance backend )
 - we want to challange it with more use cases (label selectore, health status for dashboards)
 - we want to scrape custom metrics for it - to have observability on ammount on requests, error rates, number of distinct sessions in a unit of time

We need to know if its ok to continue using api-server-proxy and gradually get rid of CBS.
@pbochynski @piotrmsc 

We can also run the backend on the client side. So it would also be future-proof if we decide to shift into a UI served from client ( like octant)

**Comment by piotrmsc** [comment]
@kwiatekus for this new component I would not use proxy anymore. API Server proxy is mean to be deleted, ofc won't happen in one release due to a couple of different reasons but we already learned that if we remain with a deprecated component then it's really hard to get rid of it ;-)

In general, we want to change kubeconfig format to have OIDC plugin support for it :) Also, we want to give direct access to apiserver.

What I would propose is : 
- Use that client with user token like you mentioned and call apiserver directly - apiserver with do the authN + authZ.
- Impersonate user (apiserver proxy is doing such thing), your backend application will need privileges (RBAC) which you can grab from proxy chart :) Impersonation in terms of calling k8s API is just adding the proper headers (impersonate-user & impersonate-groups).
- Try to use kubeconfig in that backend container with oidc-plugin set- this plugins needs to open browser in order to authenticate the user so I'm not sure if is going to work out of the box

The biggest challenge here will be open source based on managed k8s where users sometimes cannot configure apiserver with for example OIDC settings. In such cases passing user tokens to apiserver calls will not work ;-) 

Ping me if you need more details.

**Comment by kwiatekus** [comment]
Thanks @piotrmsc 
We will try going the 'Impersonate user' way

**Comment by kwiatekus** [comment]
Done.
As a result, component named [pamela](https://github.com/kyma-incubator/pamela) was born
