### ISSUE TITLE
Enable external link validation on PR

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#994]
**Description**

External link validation should be enabled on PR, not only on master. On PR it should check only files that have been changed, and on master all files.

AC:
 - [ ] External link validation enabled on PR
 - [ ] Scan only changed files on PR (in case of external links)
 - [ ] Scan all files on master

**Comment by magicmatatjahu** [comment]
The governance jobs always with checkout to the newest revision, so there are a problems:
- we can't use the `currentBuild.changeSets` array by reason of newest revision - only changes from the last commit on PR are visible,
- making `git diff` is impossible, because we only have a `HEAD rev from origin/master` local branch (or something like this).

Propositions to resolve problems:
- first: make `git diff` in `orchestrator` job for creating array of changed `.md` files, and then pass this array to the `governance` job in params of job,
- clone `master` and `PR` branches in `governance` job and then create array of files by `git diff`.

**Comment by clebs** [comment]
Hi @magicmatatjahu,
It is possible to calculate it in the same way the orchestrator does. The orchestrator provides **both** the **git revision** to build and also the **branch** to downstream jobs.

Probably currently the revision is used, if you use the branch and run the following for PRs you will have the md changeset:
```
git --no-pager diff --name-only origin/master...origin/${params.GIT_BRANCH} | grep '.md'
```

For master just checkout master (instead of the revision) and get the commit from the last successful build and run:
```
return sh (script: "git --no-pager diff --name-only $lastSuccessfulCommit 2> /dev/null | grep -v 'vendor\\|node_modules' || echo ''", returnStdout: true)
```

**Comment by pkosiec** [comment]
Review: @pkosiec @michal-hudy
